### ISSUE TITLE
Capital letters in "Element Name" and "Title" fields throws error

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1013]
**Describe the bug**
Title and Element name fields are not accepting capital letters.
When the user enters any capital letter, it throws an error and not allows to submit the HSM template for approval.

**To Reproduce**
1. Fill in all the details in the HSM template.
2. Enter a capital letter in the Title and Element name fields.
3. In this case "D" was capital in the "Data submission reminder" text.
4. Click on the "Submit for approval" button.
5. It throws an error. "**Shortcode: only "_" and alphanumeric characters are allowed.**"
6. Change the capital letter into a small letter. Click on the "Submit for approval" button. It will get submitted successfully.

**Expected behavior**
It should accept both small and capital letters.

**Screenshots**
<img width="1109" alt="HSM_template_issue" src="https://user-images.githubusercontent.com/16541548/106257287-59452780-6242-11eb-876a-0fed2059d3a8.png">

**Comment by pankaj-ag** [comment]
This is fixed. Closing this one now.
