### ISSUE TITLE
Managing Staff members

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1014]
@abhi1203 Assign this document to you for review. Let me know if you have feedback or suggestions.

**Managing Staff members**
https://glific.slab.com/posts/managing-staff-members-gg6fkw8h

**Comment by pankaj-ag** [comment]
@mohitsharma-22 I think the document needs a bit more improvements. 
Can we add what each role access and rights?
Can we also make the heading a bit more clear? Currently, it starts with User registration just after the role?
@abhi1203 can you provide some more feedback whenever you have time?

**Comment by abhi1203** [comment]
@mohitsharma-22 added some comments please check.

**Comment by mohitsharma-22** [comment]
Thanks @abhi1203 @pankaj-ag for your feedback. I have updated the document as per your suggestion. Please check and suggest if you have any further suggestions.
