### ISSUE TITLE
Block Spam messages in chatbot.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1015]
**Is your feature request related to a problem? Please describe.**
Generic way to block spam messages in the chatbot.

**Describe the solution you'd like**
The request is to restrict on a conditional basis. 
For Example. Block contacts using country code, other than +91 bot should not accept the optin?

**Case:**
STIR received a spam message with a video attachment form +92 phone number.

**Comment by dlobo** [comment]
Am closing this issue since this is not in our short or medium-term priority. We'll keep this as a feature request. For now, this can be done by the NGO either via an API and/or manually. Since the amount of SPAM reported by NGOs so far has been pretty minimal, this issue seems a bit less relevant
