### ISSUE TITLE
Get metadata from a webpage to show link previews

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1019]
**Is your feature request related to a problem? Please describe.**
Currently, for showing a link preview we are using a CORS proxy server to get data from various URLs. The proxy server only excepts 50 requests per minute and the link previews can't be shown after the limit is reached.

**Describe the solution you'd like**
A link on the backend where we get the metadata of the website such as the title, image, and description so that we can easily show link previews without any restrictions.

**Comment by pankaj-ag** [comment]
This is fixed. Closing this issue now.
