### ISSUE TITLE
Message are being received twice when sending to collections

### ISSUE THREAD

**Issue by Ankitkukreti** [glific/glific#1026]
**Describe the bug**
 When sending messages to the collection the message is being received twice on the receivers end. flows are working fine

**To Reproduce**
1. Go to collection
2. Send message to any collection

![image](https://user-images.githubusercontent.com/71115895/106634868-38643580-65a6-11eb-9412-65c70f8818b8.png)

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you work with Ankit and find out the issue ?
