### ISSUE TITLE
Migrate unread/not responded/replied to messages table

### ISSUE THREAD

**Issue by dlobo** [glific/glific#1040]
The messages_tags table, is getting a bit too busy especially since we are always adding/removing the unread/not replied-responded tags for every incoming or outgoing message. we can do this directly in the DB via triggers and two columns that are indexed. That will also make the counts a lot faster. 

- add is_read column, applicable only for inbound messages
- add is_replied column, which serves two different purposes
   * for inbound, the NGO has not read the message
   * for outbound, the recipient has not responded to the message

The above two columns will cover the three tags in the system. The trigger rules for a contact_id are:

We will need to figure out how to set a message to have been read, since it happens when the frontend requests a specific contact's messages

- For any incoming message, set
   * set is_read = false, is_replied = false
   * set any inbound message where is_read = false to true (ideally should be only one)
   * set any outbound messages where is_replied = false to true (can be many, since we could have sent a bunch of messages)

- For any outbound message, set
  * is_replied = false
  * set any inbound messages where is_replied = false to true (can be many, since we could have recd a bunch of messages)

Restructure collections count to use these fields to return the count of unread/not replied/not responded which should be a lot faster. This is the only info we send in the collection count

Work on this is being done in feature/tags

**Comment by pankaj-ag** [comment]
This is complete and merged. 

@AkhileshNegi @mdshamoon can you test this and confirm.
