### ISSUE TITLE
Consistency for error messages

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1048]
**Is your feature request related to a problem? Please describe.**

Can we have errors with the same format for flow name and flow keyword
![image](https://user-images.githubusercontent.com/32592458/107371016-bfb32b00-6b09-11eb-8ee6-119c0901887d.png)

**Describe the solution you'd like**
```
{
key: "name",message: "Activity has already been taken"
}
```

**Comment by dlobo** [comment]
PR will be merged later today. Deployed tonite
