### ISSUE TITLE
Have a reserved key for the deafult searches

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1063]
**Is your feature request related to a problem? Please describe.**
Currently, we can edit and delete the default searches and it can cause issues with user understanding if these searches gets modified.

**Describe the solution you'd like**
Add an isReserved key in the savedSearches query so that we don't allow those searches to be modified.

The following searches should be kept reserved:

- All
- Unread
- Not Replied
- Not responded
- Optout

**Comment by pankaj-ag** [comment]
Closing this one as complete.
