### ISSUE TITLE
CollectionStats API not working for staff or manager role

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1094]
**Describe the bug**
Collection stats API not working for any other role than admin

**Expected behavior**
The API should work for manager and staff role

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/108161643-75393c00-7111-11eb-910a-3667b4dc021c.png)

**Comment by AkhileshNegi** [comment]
@mdshamoon  This is fixed
