### ISSUE TITLE
Give one minute gap in between optin message and first message from the flow

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1101]
**Is your feature request related to a problem? Please describe.**
Currently, when any user sends a message to the bot for the first time. The user gets an optin message and also gets the first message of the default flow. Users get confused about what to do. Generic behavior is to start responding to the flow questions and optin link preferences left unattended.

**Describe the solution you'd like**
The suggestion is to give a default gap of 1 minute in between optin message and the first message of the flow. This will give time to beneficiaries to complete the optin preferences and then they can start responding to the flow.

**Comment by pankaj-ag** [comment]
This is complete. Closing it now.
