### ISSUE TITLE
Add support for keywords in Glific Tags

### ISSUE THREAD

**Issue by dlobo** [glific/glific#111]
**Is your feature request related to a problem? Please describe.**

(revising this from my first idea)

Extends tags functionality to associate keywords that can be linked to a tag. All incoming texts, are automatically parsed and if there is a keyword match, we associate the tag with the message

Thus Hello/hi/hola/namaste/good morning could all be keywords for the tag "greeting"

numeric tags are automatically parsed by the system and have a value

We can drive automation both on the tag, and the value of the tag

I've started work on this in the genstage branch, and will merge into master by end of day

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abhi1203** [comment]
Looks good. So in a way the platform will be initiated with some keywords for the tag 🏷 
Users will add keywords while creating a tag. The automation then will happen at two levels:
1. matching keywords get associated to the message
2. system picks up keywords from tag associations which are made manually by the users and learns the patterns for future associations 

In extension to point 2, a future consideration might be to show the keywords to the users and allow them to approve if the picked up keyword is correct. It can be a part of the training process.

**Comment by pankaj-ag** [comment]
We have set up the keywords workflow for tags. 
We will close this issue after completing the message tag automation workflow.

**Comment by pankaj-ag** [comment]
Closing this one as complete. Feel free to open it if I am missing anything here.
