### ISSUE TITLE
Multiple messages are being sent when we start the Flow

### ISSUE THREAD

**Issue by pooja1425** [glific/glific#1121]
**Describe the bug**
Multiple messages are being sent when we start the Flow

**To Reproduce**
1. Create one flow
2. Login in another tab
3. Start the same flow for any contact
4. Notice the sent messages.

**Expected behavior**
It should send single message.

**Screenshots**
![Glific_ Two way  (2)](https://user-images.githubusercontent.com/62100957/108674745-c11e2380-750b-11eb-90d7-0eb8ee0643e3.png)

**Comment by dlobo** [comment]
This is the duplicate subscription bug
