### ISSUE TITLE
Chatbase integration enhancements

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#1123]
- Create chatbase jobs when we update the credentials. 
- Disable chat bases job when we deactivate the credentials

**Comment by dlobo** [comment]
I would recommend we disable chatbase from now, and avoid linking to it till we have a better handle on what it will be used for etc

**Comment by dlobo** [comment]
We'll reopen this issue when we decide to bring back chatbase and have a better idea what it is useful for
