### ISSUE TITLE
Validation issue: Name field in Flow

### ISSUE THREAD

**Issue by pooja1425** [glific/glific#1163]
**Describe the bug**
Error validation is not working for duplicate flow name.

**To Reproduce**
1. Create a flow with any name
2. Try to create a flow with same name

**Expected behavior**
It should give us "Name already exists" error message while typing.

**Expected behavior - updated**
Change the text of the error message to:
```
Sorry! The flow name already exists.
```

**Screenshots**
![Glific_ Two way ](https://user-images.githubusercontent.com/62100957/107472978-e9b22f00-6b95-11eb-9bbc-071acd452dc8.png)

**Comment by dlobo** [comment]
Fixed in backend validation code
