### ISSUE TITLE
Improvements to the `Glific.Contacts.Import`'s importer

### ISSUE THREAD

**Issue by madhavmalhotra-3089** [glific/glific#1264]
**Is your feature request related to a problem? Please describe.**
The current contact importer does not provide the following functionality:
1. The importer does not create a group if it does not exist.
2. The importer can only work with a local file path. It cannot work with URL/string of data to be importer.
3. The importer does not allow optional opt'ins.

**Describe the solution you'd like**
The following use cases will be added to the import function:
1. Importer will create a group if it does not exist.
2. The importer will have 3 modes: file_path, url and string text for importing contacts.
3. The importer will not call the glific optin api if the optin_date is not provided (And will just create the contact)
4. The importer should have a column that deletes the contact. This makes it easier for orgs to keep their contact list in sync with their DB

**Comment by dlobo** [comment]
This is now part of 1.2.x. Future improvements will go in 1.3
