### ISSUE TITLE
Contacts with no messages are not showing up in the search query for a staff

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1272]
**Describe the bug**
Contacts that have no messages are not showing up in the search query for a staff

**To Reproduce**
1. Go to the chat screen with the staff role
2. Clear all conversations for a contact
3. Hit refresh
4. The contact will not be present in the list

**Expected behavior**
The contact should be present in the list even if there are no messages present.

**Comment by dlobo** [comment]
I think some changes we made yesterday fixed this. i cannot reproduce this, but did fix a bug in clear conversations :)

**Comment by mdshamoon** [comment]
This is fixed
