### ISSUE TITLE
Add an attribute isDraft in flows query

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1309]
**Is your feature request related to a problem? Please describe.**

Need an attribute isDraft in the flows query to know whether the flow is currently in draft version or the published version.

**References**

Link for the design mockups- https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=1846%3A275

**Comment by dlobo** [comment]
@Ankitkukreti can you rework this a bit

* We should create a draft date column and populate it only IF draft date > published date or published date is nil
* We can add the keyword draft the name, but in general, that is semi-misleading, since floweditor saves revisions so aggresively
*

**Comment by Ankitkukreti** [comment]
I have created the design for the same, here's the link https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=1846%3A2042
