### ISSUE TITLE
Ensure phone number verification via WhatsApp

### ISSUE THREAD

**Issue by dlobo** [glific/glific#131]
**New Flow**

Please re-read the issue, using Whatsapp and glific itself to validate a contact rather than SMS

**Is your feature request related to a problem? Please describe.**
All our login names will be phone numbers. We need to verify that the phone number is valid and verified when we create a user.

While we are doing this, we should also add a Name to the user table. We should check and see if we can integrate a roles and permissioning packages into our user management system.

Create User Flow is as follows:

a. The user goes to the NGO landing page on glific and enters "Create an Account" page

b. At this stage, the user uses one of the 5 mechanisms offered by Gupshup to optin to the Whatsapp business account of the NGO.

b. The user enters name, phone number and password.

c. Frontend, requests us to send an OTP to phone number via Glific

d.  1. We verify that the phone number is a contact in the DB.
     2. We send an WhatsApp HSM or Session Message to the user with an OTP 
     3. The user uses the OTP to fill in the number on the frontend screeen

e. If user enters valid OTP code, frontend request backend to create user with minimal permissions and Logged In User Roles (basically the user can do nothing)

f. NGO Admin, needs to upgrade the user to a higher role so user can see anything

At a later stage, we will also introduce 2FA and send the user a Whatsapp message to authenticate. But we'll file an issue for that later. Mentioning it here in case it involves design decisions

**Comment by tttp** [comment]
Is it possible to verify the phone number via whatsapp?

**Comment by ansh14j** [comment]
**Tasks**
1. - [x] User creation in not verified state
1. - [ ] Phone number verification
   1. - [x] Send SMS API
      1. - [x] Context function
      1. - [ ] Handle existing number
      1. - [ ] Unit test
      1. - [x] Graphql resolver function and schema mutation
      1. - [ ] Graphql unit test
   1. - [ ] Verify OTP context function and unit test
      1. - [x] Context function
      1. - [ ] Handle wrong otp and already verified
      1. - [ ] Unit test
      1. - [ ] Update user with verified state
      1. - [x] Graphql resolver function and schema mutation
      1. - [ ] Graphql unit test 

1. - [ ] Passwordless_auth
   1. - [x] Understanding source code for changing SMS provider
   1. - [ ] Integrate Gupshup for send sms
   1. - [ ] Implement multiple SMS provider to switch between twilio, gupshup etc., based on configuration.
   1. - [ ] Unit test

1. - [ ] Investigate on permission and role management

**Comment by pankaj-ag** [comment]
@dlobo @ansh14j is this issue complete or we are waiting for some of the cleanups ?

**Comment by pankaj-ag** [comment]
We need to integrate this with Gupshup Service provider.

**Comment by dlobo** [comment]
> Is it possible to verify the phone number via whatsapp?

yes, we are actually switching to verification via Whatsapp, so we have a unified channel
