### ISSUE TITLE
Language detection/question

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#132]
**Is your feature request related to a problem? Please describe.**
Whenever a new beneficiary initiates a conversation, NGOs need to understand what their preferred language for interaction would be so that the content can be sent in that language.

**Describe the solution you'd like**
Based on the user message, system should be able to detect the language and tag it to that conversation.
Based on the detection, a message can be sent to the user for confirmation - initially it will be English and Hindi.

**Describe alternatives you've considered**
If the language is not detected, a message in both the languages can be sent. 
@dlobo how will the case be handled when we increase the support beyond hindi and english?
Would this also be something like: "We detected your preferred language to be 'Marathi' would you like to continue with that or choose different language. Options 1, 2, 3, 4...'

**Comment by dlobo** [comment]
@abhi1203 based on the saajha demo, we changed the flow to the following:

1. send language question with new user welcome message
2. ask them to type English for English in English. हिन्दी for hindi etc. we can then match on the language picked and set it up
3. all system messages need to have a version in all languages
4. the NGO should be able to assign a default language that is automatically set for all users (in case they dont choose)

I've got a version of the above working in my sanbox. need to write tests now

**Comment by abhi1203** [comment]
@dlobo sounds good. 
Does this work for the requirements. https://docs.google.com/document/d/1Q7ozYAHl1wcVQlXcg3iZjQZPHaUQJzQCYHTLaajncrs/edit#heading=h.cqcaz7nrm1l0
To this we'll need to find a way to give options for more languages.
Maybe typing 1, 2 will be easier for setting or we need them to enter the word?

I'll include point 4 also in the requirements. Somewhere we're managing Conversation/contact settings.

**Comment by dlobo** [comment]
For the early versions, we'll keep hindi/english etc

we'll switch to giving the NGO the flexibility when we add answers associated to the most recent question.

right now the keywords are all global, hence 1 or 2 wont work (since typing them anywhere will switch language)
