### ISSUE TITLE
Request for API's to complete stripe integration

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1358]
Need the following API's to complete the stripe integration:

- [ ] An API endpoint to check whether the organization is already subscribed to a plan
- [ ] API endpoint to get customer and their subscription plan details
- [ ] Handling 3d secure support if needed (this needs an additional confirmation from the frontend) https://stripe.com/docs/billing/subscriptions/metered#manage-payment-authentication
- [ ] If needed, an unsubscribe option

**Comment by pankaj-ag** [comment]
Tracking this issue in #1334
