### ISSUE TITLE
Issue with multi-search for login user contact

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#1374]
**Describe the bug**
There are messages that appear on the multi-search screen but not on the chatting screen for the login user (NGO Main Account).

**Comment by pankaj-ag** [comment]
@DigneshGujarathi I this NGO main account is the default organization account and we are not supposed to login with the user. 

Are you able to replicate this issue on production or local?

**Comment by pankaj-ag** [comment]
@DigneshGujarathi closing the issue for now. We will come back on this later and change the default contact. Please reopen in case I am missing something here.
