### ISSUE TITLE
Add GraphQL support for user table

### ISSUE THREAD

**Issue by dlobo** [glific/glific#143]
**Is your feature request related to a problem? Please describe.**
user table now has roles and user name. We need to allow an admin to modify those.

Please add graphql support for the user object. they cannot create an user object nor edit the phone/password. but should be able to delete and edit the name/role

lobo

**Comment by ansh14j** [comment]
For context test cases, need to find a way to create a user for each test case. 
(As user creation step is in registration flow)

**Comment by ansh14j** [comment]
While updating User roles validation is not working.
