### ISSUE TITLE
Enhancements: Contact Field

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#1515]
**Describe the solution you'd like**
We are using contact fields to support flow editor and allow the user access to NGO specific fields.
Currently we can only create a contact field as:
1. Go to Flows
2. Click on configure
3. After wait for response node create another node as Update_contact
<img width="769" alt="Screenshot 2021-05-12 at 3 43 18 PM" src="https://user-images.githubusercontent.com/40158831/117958623-d5b6ce80-b338-11eb-8d41-83392e225c98.png">

4. Type the field name you want to create and field is created

**Design:**
1. Adding manage contact field option in flows screen
<img width="1439" alt="Screenshot 2021-05-12 at 3 35 23 PM" src="https://user-images.githubusercontent.com/40158831/117957594-dbf87b00-b337-11eb-94bd-b512d82db6cf.png">

2. Adding separate screen to list contact fields for an organization and manage them

**Backend:**
 Adding APIs for Creating, updating, deleting, listing and count for contact Field

**Comment by pankaj-ag** [comment]
@AkhileshNegi We also need to define the global variables.
@abhi1203 can you please suggest the design for that.
