### ISSUE TITLE
Add REST API endpoint to upload files to GCS

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1519]
**Describe the task**

Since the flow editor does not support GraphQL can we a REST API endpoint for the flow editor to upload files.
Also, we will need an endpoint to check if GCS is enabled or not.

**Comment by pankaj-ag** [comment]
@mdshamoon this is fixed in this pull request.
https://github.com/glific/glific/pull/1537

To check the attachment in the flow editor 

Url: flow-editor/attachments-enabled (get request)

To upload the attachment

Url: flow-editor/flow-attachment (Post request with multipart form data)

**Comment by pankaj-ag** [comment]
Let me know in case you need any other modifications to this.
