### ISSUE TITLE
Consulting hours amount should be added in stripe invoice

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1592]
**Describe the task**
Consulting hours amount for the current month should be added to the stripe invoice before the invoice is finalized for the month.

**Expected behavior**
The usage should be added to the subscription when the consulting hour is recorded.

**References**
API's to look for- usage Record (it helps to record the usage of the service in a subscription)
https://stripe.com/docs/api/usage_records/create

**Comment by pankaj-ag** [comment]
This is complete.
