### ISSUE TITLE
Query cleanups

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1603]
**Is your feature request related to a problem? Please describe.**
We have API's like getOrganizationBilling, getOrganizationExtension, organizationServices that we use to get various things from an organization

Rather than having these separate queries, let's add them to the organization object, and then we can easily fetch them through the organization itself.

**Comment by pankaj-ag** [comment]
@mdshamoon how you will handle the pagination with this?

**Comment by pankaj-ag** [comment]
@mdshamoon closing this one now since we don't have any good idea about the requirements here. Feel free to open the issue again if you have any thoughts.
