### ISSUE TITLE
Improve ability to send messages to contacts

### ISSUE THREAD

**Issue by dlobo** [glific/glific#161]
**Describe the bug**
We need to record, that a message was created and stored in DB, but NOT send to the contact due to either OptOut and/or past session time limit

We might need to create a glific status, since we dont even bother to hand this off to the provider

This will also impact things like send an opt-out messages, since we need to ensure that the message is sent before the optout status is recorded

One thing to keep in mind (but probably not address at this stage) is, when should we do this check? Just before handoff to the provider or much early on in the cycle.

As we introduce scheduled sends and/or the systems gets slow, the status can change before message handoff to glific and glific's handoff to provider. We might want to do it in both places

**Comment by pankaj-ag** [comment]
This is complete for the v0.1 feature.  We will come back on this on v0.2 for further improvements.

**Comment by pankaj-ag** [comment]
Closing this one as complete.
