### ISSUE TITLE
Organization status cleanups 

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1610]
**Describe the task**

Organization status:

- [ ] Once the organization is set into a suspended mode, its monthly subscription decreases, but switching back to active the subscription does not revert to the original amount.
- [ ] We should cancel the subscription on stripe end after one day of changing the status `Ready to delete`
- [ ] Glific admin should not be allowed to change the status of the default organization.

**Comment by dlobo** [comment]
closing since we are not using stripe subscriptions a whole lot, and we need to revisit this
