### ISSUE TITLE
Create ability to save  searches

### ISSUE THREAD

**Issue by dlobo** [glific/glific#162]
**Is your feature request related to a problem? Please describe.**
We need to save searches to create collections.

Examples shipped by default include:

- All unread conversations
- Conversations read but not replied

The structure should be fairly flexible to accommodate filters and future changes. We should store things in a json format similar to how the function processes it

I suspect the structure will be:

id, label: args: jsonb (these are all the args the function processes stored in jsonb format)

**Comment by pankaj-ag** [comment]
This is complete. 

Currently, the filters will apply to the contact ids instead of full-text search.
