### ISSUE TITLE
Update floweditor completion endpoint with the latest nyaruka changes

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1695]
**Is your feature request related to a problem? Please describe.**
The latest flow editor update removed the completion and function endpoint support and combined both into an editor.json file

**Describe the solution you'd like**
Update the completion endpoint to give a JSON in the format

```
{
 context: [previous completion.json],
 functions: [previous functions.json]
}
```

**Code reference of the updates**
https://github.com/nyaruka/temba-components/commit/e4f38abeb99c9688fa7c26b245818df94e143621

**Comment by pankaj-ag** [comment]
This is complete.
