### ISSUE TITLE
Sometimes sender name doesn't show with the message

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#1763]
![image](https://user-images.githubusercontent.com/16714604/132825761-36b888d3-dd86-4fa5-aa54-4deea4534c04.png)

Here, the steps i took was select the HSM template, enter name in variable and send the message

**Comment by dlobo** [comment]
I have merged a patch for this in master. however not sure how to test it on local :(

**Comment by mdshamoon** [comment]
Can we add seed data with published HSM's? I think we can test then since we get only the published HSM list on the chat screen and I will also write cypress test cases for the HSM sending flow from the chat screen.
