### ISSUE TITLE
Page to view monthly consulting hours and amount for invocies

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1795]
**Is your feature request related to a problem? Please describe.**
There is no page to track the hours and amount we need to invoice for consulting hours on monthly basis. Especially for the NGOs who have deleted their credit cards and opted for manual quarterly billing.

Need a page where the hours and amounts of each month can be viewed to easily refer to avoid missing any invoice.

It can be in the below format.
NGO | Month | Consulting Description | Billable hours | Hourly Rate | Amount INR

**Comment by pankaj-ag** [comment]
@mohitsharma-22 let me know whatever you need in the consulting page.

**Comment by mohitsharma-22** [comment]
@pankaj-ag I need details to generate consulting invoices monthly.

We can have the below details on the consulting page.
NGO | Month | Consulting Description | Billable hours | Hourly Rate | Amount INR

**Comment by mohitsharma-22** [comment]
@pankaj-ag Thanks for checking on this. Can we add a billable and not billable filter also, which can help me to get the exact billable hours for invoices monthly?

**Comment by pankaj-ag** [comment]
From Mohit Sharam 
We need an indicator that will tell us how much probono hours are spent on each NGO monthly.

Add an option in the consulting page in Glific.
See if it can be shown in the dashboard for reporting purposes.
