### ISSUE TITLE
Upgrade to latest Phoenix Framework

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#1798]
Phoenix Framework has released the stable version 1.6.0. 
We also need to upgrade that.

Upgrade guide 
https://gist.github.com/chrismccord/2ab350f154235ad4a4d0f4de6decba7b

**Comment by dlobo** [comment]
We should do this as part of the OTP 24 upgrade. maybe the week of Diwali?

**Comment by pankaj-ag** [comment]
This is complete.
