### ISSUE TITLE
Allow uploading of bulk HSM templates as CSV

### ISSUE THREAD

**Issue by jk979** [glific/glific#1805]
Problem description: We must upload HSM templates one at a time; however, we have a need to upload and get approved 5-10 per month, with a backlog of about 100-150 messages currently needing to be uploaded as templates. 

Solution requested: Allow for bulk uploading of HSM templates as CSV, with a column for each of the fields/dropdown just as exists currently in the Add a New HSM Template feature. 

Alternatives: We have registered a few using the regular Add a New HSM Template feature, but it's not feasible to register so many individually given our backlog and current needs.

**Comment by pankaj-ag** [comment]
We will explore APP script for that.
