### ISSUE TITLE
Need to remove old subscriptions in stripe.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1819]
**Describe the bug**
I noticed that NGOs (who have requested to remove their card) are getting emails every week from stripe saying your payment is not successful.
NGOs who have moved to quarterly manual billing, we have removed their cards in stripe. But all those NGOs are getting emails that are not relevant. We need to remove all those subscriptions from stripe so that NGOs don't get these emails.

**Screenshots**
<img width="474" alt="Screenshot 2021-10-15 at 3 55 01 PM" src="https://user-images.githubusercontent.com/16541548/137473459-4497db7e-7e69-4105-8679-a2fa4db6c8aa.png">

**Comment by pankaj-ag** [comment]
This is complete. Closing this one now. 
Please open a new issue if there are some other requirements.
