### ISSUE TITLE
Reset password is not working because of common OTP HSM templates

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1825]
**Describe the bug**
Dost education reported OTP messages are not received while doing the password reset.
Able to replicate it on the ColoredCow account. This may be an issue for other NGOS also
Pankaj Created a ticket for the Gupshup team.

**Comment by pankaj-ag** [comment]
@mohitsharma-22 this is fixed. We have submitted all the all templates again and they got approved.
