### ISSUE TITLE
Keep trail of contact history

### ISSUE THREAD

**Issue by dlobo** [glific/glific#1837]
* Create a unified history table which records some of the significant events that a contact goes thru in its lifecycle
* Some of the events include:
  * Contact Created
  * Contact Field XX updated with value VV
  * Contact Language updated to LL
  * Contact Name updated to NN
  * Contact added/removed from Collection A
  * Contact started on Flow A
  * Contact ended Flow A
  * Contact ended all Flows
* Potential Contact History Table fields would include (in addition to the common ones)
  * Contact ID
  * Event Name (e.g. Contact Added to Group, Contact Started Flow)
  * Event occurred date time
  * Event Subject (Group Name, Flow Name)
  * Event Data (Field Value)
  * Additional Data (json)

**Comment by pankaj-ag** [comment]
- [ ]  Contact Created
     event name: contact_created
     event label:  "contact created on 2 Dec, 2021"
- [ ]  Contact Field XX updated with value VV
     event name: contact_fields_updated
     event label:  "Value for state is updated to Haryana"
- [ ]  Contact Language updated to LL
     event name: contact_language_updated
     event label:  "contact language set to Hindi via flow Langauge Flow"
- [ ]  Contact Name updated to NN
     event name: contact_name_updated
     event label:  "contact name changed to Ram"
- [ ]  Contact added/removed from Collection A
     event name: contact_groups_updated
     event label:  "Contact added to the group"
     event label:  "Contact removed to the group"
- [ ]  Contact started on Flow A
     event name: contact_flow_started
     event label:  "Flow (Help workflow) started for the contact"
- [ ]  Contact ended Flow A
     event name: contact_flow_ended
     event label:  "Flow (Help workflow) ended for the contact"
- [ ]  Contact ended all Flows
     event name: contact_flow_ended_all
     event label:  "All flows are ended for the contact"

**Comment by pankaj-ag** [comment]
This is complete. Closing this now.
