### ISSUE TITLE
Restructure starting a collection on a flow

### ISSUE THREAD

**Issue by dlobo** [glific/glific#1839]
The current design is not very robust and does not keep track of failures, successes and will not scale for collections with large number of contacts (across machine or system restarts). We need to design this from the ground up for the backend. A first cut of the design follows:

* Create a new table called flow_broadcast with the following fields:
  * flow_id
  * group_id
  * message_id
  * started_at
  * completed_at
  * user_id

This table is populated when the user schedules a flow on a collection (or when we trigger a flow on a collection)

* Create a new table called flow_broadcast_contacts with the following fields:
  * flow_broadcast_id
  * contact_id
  * processed_at
  * status (can we meaningfully fill this? sent or error)

When we schedule a flow, this table is created with a nil processed at and status. 

A unique cron job that runs every minute processes the first 300 unprocessed flow_broadcast_contacts for each organization and starts the flow. It updates the processed_at time. The status field is updated by the flow runner (we can leave this as an exercise for later). Most of this code is already written and can be reused. The advantage is at any give time in the case of a machine or system reboot we have a pretty good idea of where we are in starting the contacts on the collection

**Comment by pankaj-ag** [comment]
Backend APIs for stats 
https://github.com/glific/glific-frontend/issues/1667#issue-1006215602

**Comment by pankaj-ag** [comment]
Closing this one as complete. We need to work on the stash API.
