### ISSUE TITLE
Wait for response translation section is not working.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1851]
**Describe the bug**
Wait for response translation section doesn't work to accept the valid response in another language. The user needs to add translated text in another language in the default Wait for response window. Today a similar issue was reported by Bandhu.
Can we remove this section, as it gives confusion to users?

**To Reproduce**
1. Go to flows
2. Open any flow inflow editor.
3. Add wait for response node with values
4. Click on another language.
5. Click on the wait for response section, to see the window.

**Screenshots**
<img width="638" alt="Screenshot 2021-10-31 at 6 02 10 PM" src="https://user-images.githubusercontent.com/16541548/139583513-83c0efb9-bc75-42a3-a607-0f1450df1c84.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 this is complete, Please test and close this issue.

**Comment by mohitsharma-22** [comment]
@pankaj-ag It is working fine. Closing it now.
<img width="264" alt="Screenshot 2021-12-10 at 11 20 19 AM" src="https://user-images.githubusercontent.com/16541548/145524028-ed8210f4-09ef-406f-ac5a-8736f1eaa57d.png">

<img width="640" alt="Screenshot 2021-12-10 at 11 21 03 AM" src="https://user-images.githubusercontent.com/16541548/145524082-4f847a0e-f0eb-4f3c-8608-d0d08a37ec24.png">
