### ISSUE TITLE
Automated email on creating a new account

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#1878]
**Is your feature request related to a problem? Please describe.**
Right now I need to send email regarding creating user accounts after glific setup. I need to share the steps manually for each and explaining the account creation process is a bit challenging.

**Describe the solution you'd like**
We can trigger a well explaining email describing the process to create account. It can be triggered on setting the status to active. 

**Describe alternatives you've considered**
Right now it’s a manual process

**Comment by mdshamoon** [comment]
@glific/glific-backend, please check the feasibility for this issue.

**Comment by pankaj-ag** [comment]
duplicate @2038
