### ISSUE TITLE
Validate media api gives incorrect result for media of type sticker

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1907]
**Describe the bug**
Validate media API gives incorrect results for media of type sticker

**To Reproduce**
1. Go to the chat screen
2. Click on add attachment option and select type Sticker 
3. Enter the public URL of the sticker: http://www.buildquickbots.com/whatsapp/stickers/SampleSticker01.webp

or use this endpoint: /flow-editor/validate-media?url=http://www.buildquickbots.com/whatsapp/stickers/SampleSticker01.webp&type=sticker

**Expected behavior**
It should not give an error for the correct URL and type

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/146140857-5bb9ca50-bc84-49d8-856c-a7b86aa9401a.png)

**Comment by pankaj-ag** [comment]
@mdshamoon can you check now?

**Comment by pankaj-ag** [comment]
Closing this one as we have merged this on master.
