### ISSUE TITLE
Wait for response options in other languages are not clearly define.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1911]
**Describe the bug**
1. The options where Wait for response values are expected in other languages, somehow gives a feeling to enter the category. whereas it should have values expected as a response from contacts. Please make it clear, so that the user enters a value in the same

2. Also, all the options of the values are not available. Like number in between is not showing two fields to ender the range of numbers

**Screenshots**
<img width="643" alt="Screenshot 2021-12-16 at 4 05 08 PM" src="https://user-images.githubusercontent.com/16541548/146356088-e45ee6b5-b02a-497a-8934-96287340682a.png">

<img width="636" alt="Screenshot 2021-12-16 at 4 05 35 PM" src="https://user-images.githubusercontent.com/16541548/146356117-720f3873-eec3-470a-8d91-b6ae6055dee2.png">

**Comment by AkhileshNegi** [comment]
This is merged and live in production
