### ISSUE TITLE
Feature to identify new vs returning contacts in Glific 

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1927]
**Is your feature request related to a problem? Please describe.**
It is a request from many NGOs. They want to know which all contacts are returning one and not the new contacts. Recently Nayi Disha has asked for the same requirement.

As discussed in the stand-up, creating this task to track this request. We will brainstorm how we can show this data to NGOs.

**Comment by dlobo** [comment]
I thought about this, and the easiest way for someone to do it, is to set a contact field in the new contact flow. They might want to set the date the contact joined, and then use that field to decide if its a new contact or returning contact
