### ISSUE TITLE
Issues with message triggers

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#1942]
**Describe the bug**
Setting up trigger with a message flow doesn't go out at the defined time. 

**To Reproduce**
1. Went to triggers
2. Selected the settings : flow, time, date 24/12 to 25/12 for the message blast on 25th, does not repeat, collection, 
3. The message triggered instantly and not at the specified time.
4. When changed the setting `does not repeat` to repeat, while keeping all the other details same, the message didn't trigger at all.

**Comment by pankaj-ag** [comment]
duplicate #1935
