### ISSUE TITLE
Upload contact issues

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#1943]
**Describe the bug**
While uploading contact using google sheets. I had following observations:
- The name were not showing. Names were added in Hindi. Only numbers were showing for the uploaded contact.
- The contacts didn't get added to the selected collection. I had to upload the sheet twice to get them added.
- Since the contacts list were opted in, they should show with grey `0` in their session timer. But when i uploaded they showed up with the block sign indicating that we couldn't even send template to them.

**Comment by pankaj-ag** [comment]
@abhi1203 I am not able to replicate it. Can you share the excel you were using ?

**Comment by abhi1203** [comment]
@pankaj-ag sent you on DM chat

**Comment by pankaj-ag** [comment]
Closing this one. Please reopen if you see this issue again.
