### ISSUE TITLE
Send Audio File from Glific to DialogFlow

### ISSUE THREAD

**Issue by madanprerak** [glific/glific#1948]
**Is your feature request related to a problem? Please describe.**
We are Planning to analyse the intent of audio shared and check its relevance with the flow using dailogflow.

**Describe the solution you'd like**
We should be able to send that audio file directly to dailogflow.

**Describe alternatives you've considered**
We are sending audio file to a seprate Data Base using webhook from there we are sharing it with the dailogflow.

**Additional context**
We are able to share text directly with the dailog flow.

**Comment by pankaj-ag** [comment]
We have fixed this. We will reopen in case some issue came up. 
@dlobo do we need documentation for this one?
