### ISSUE TITLE
Adding wait for result node stops the working of a flow

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#1963]
**Describe the bug**
Adding wait for result node is causing issues while creating and testing flows

**To Reproduce**
1. Create a new flow
2. Add a wait for result node after a webhook node
3. Try to preview or publish the flow
4. See an error

**Expected behavior**
There should be no error

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/148340594-fa53af73-18d5-423e-8df5-1aabe371a31a.png)

Use this frontend PR for testing: https://github.com/glific/glific-frontend/pull/1825

**Comment by AkhileshNegi** [comment]
@mdshamoon you can checkout this `features/dialogflow-audio` branch and run mix setup

**Comment by mdshamoon** [comment]
Thanks, @AkhileshNegi. Sorry I was checking it with the master branch.
