### ISSUE TITLE
Add Glific Based Provider which proxies message to itself

### ISSUE THREAD

**Issue by dlobo** [glific/glific#197]
**Is your feature request related to a problem? Please describe.**
We need an easy way to test and interact with the system without external HTTP calls to a BSP

The basic idea is that all contacts communicate with their proxy. so each contact has a proxy in the system.

**Solution**
* Create a Glific Provider that follows the Gupshup payload for now
* Two types of Contacts: Regular Contact and the same Contact as a Proxy Contact with phone number starting with "00" (or some defined prefix). Modify both the phone number and name, so we can reverse it easily
* Messages sent to a regular contact number, are reported delivered to the frontend (at a later stage we will randomly have errors and timeouts).
* The messages delivered, then get sent to a proxy handler, which transforms the same message and sends it back to the front end as a message from Proxy Contact.
* Messages sent by a Proxy Contact do the reverse, and are delivered. The proxy handler then sends the same message back to the frontend as coming from Contact

Seems like we will need to add two functions to a simple BSP

1. Switch a contact from proxy contact to regular contact and back
2. transform an incoming payload to an outgoing payload by switching proxy contact to regular and vice versa and by changing sender/receiver id

**Comment by pankaj-ag** [comment]
@dlobo I think this is complete. 
Let me know in case  I am missing anything here.
