### ISSUE TITLE
Headstream subscription are still going from Stripe. Please remove it.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1980]
Headstream has requested to pay quarterly and their subscription invoices are still getting generated from Stripe.
Can you please remove it, so that monthly invoices are not getting generated?

<img width="1165" alt="Screenshot 2022-01-17 at 4 14 42 PM" src="https://user-images.githubusercontent.com/16541548/149755661-d1cc399c-e3f9-454f-8bba-c637ee6f62f4.png">

Thanks,

**Comment by AkhileshNegi** [comment]
Made DB cleanups and sync to prevent any such cases in future
