### ISSUE TITLE
HSM Messages getting multiple times while sending out to collections

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1985]

**Comment by mohitsharma-22** [comment]
1. Collections that were used to send the HSM messages.
 2. HSM sent to the collection is removed from the collection logs
<img width="1330" alt="Screenshot 2022-01-18 at 7 12 55 PM" src="https://user-images.githubusercontent.com/16541548/149949098-cab43906-57f6-4fce-8f58-4546e616c0a4.png">


The contact received multiple messages. 
<img width="1319" alt="Screenshot 2022-01-18 at 7 14 22 PM" src="https://user-images.githubusercontent.com/16541548/149949193-90221211-e577-4f4d-8e69-b3edab6b1565.png">

Tried to replicate it with the TEST collection, but was unable to replicate it.
<img width="1317" alt="Screenshot 2022-01-18 at 7 17 38 PM" src="https://user-images.githubusercontent.com/16541548/149949393-000e2006-6b9a-4650-b9f4-691998fdbd94.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 I am not able to replicate this. Will try to do that for a few more days. Let me know in case this comes up again.

**Comment by pankaj-ag** [comment]
Closing this one. Please re open if you see this issue again.
