### ISSUE TITLE
Split by Contact Field new node in flow editor

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#1992]
As per the discussion in today's standup creating a ticket to track.

Create a new node  Split by Contact Field, which will help NGO users to use it to split the decision on the basis of any contact filed.
Split by flow result is not allowing Contact Fields to use for split the response in flows.

https://community.rapidpro.io/blog/how-use-split-steps-rapidpro/

**Comment by pankaj-ag** [comment]
@mohitsharma-22 we have released the first cut of this. 
Currently, it has some additional fields which we will remove in the future. 

Can you please check the basic functionality and let us know how it's working. 

![image](https://user-images.githubusercontent.com/10670690/152344263-0a461668-f620-4c0b-85f0-144df79c969b.png)

**Comment by mohitsharma-22** [comment]
@pankaj-ag It is working fine as expected. 
https://cc.tides.coloredcow.com/flow/configure/ff1d0486-b095-4360-be0f-935572b57a44
