### ISSUE TITLE
Flow stops abruptly in between - Mukamaar flow.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2001]
First
1. Date - 21 /Jan/2022
2. User- Bhavesh Koli
3. FLow - Optin
![1](https://user-images.githubusercontent.com/16541548/150792261-2065a21e-c860-4964-a448-c6f02290f6e0.jpeg)

Second
1. Date - 24 /Jan/2022
2. User- Jsi Maa Durga
3. FLow - Non- Physical day 10
![2](https://user-images.githubusercontent.com/16541548/150792274-5e0f51de-4815-494c-93af-8f40b2a2c316.png)

**Comment by pankaj-ag** [comment]
@mohitsharma-22 assigning this to @AkhileshNegi. He will take care of this.

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 can we close this as we have shared observation over discord?

**Comment by mohitsharma-22** [comment]
@AkhileshNegi Did we get the reason for stopping the optin flow? Do you want to post the details of that here?

**Comment by AkhileshNegi** [comment]
No @mohitsharma-22 we did not find any details for that and the issue was not replicable as discussed. You can share steps to replicate the issue and we can take a look at it again else we can close the issue
