### ISSUE TITLE
Improve seeders and tests

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#201]
**Is your feature request related to a problem? Please describe.**
Currently, we have all the seeders in one place. We need to clean them up and divide them into necessary and good not have a category

**Describe the solution you'd like**
We will create 3 files 
1. seeds_prod.exs - this will have all the necessary seeders for the system. The test should load this file at startup (or after reset if easier). Tests should not modify any of this, they can however assume that they are present. This will also simplify our testing a bit. This should be a .exs file, with minimal elixir code.
  * language
  * organization
  * 1 organization contact
  * tags (no testing tags)
  * saved searches
  * session templates used in automation

2. seeds_dev.ex - This will be the rest of the current data which includes
* Additional Contacts
* Some sample messages
* Media Messages
* 4 users with different roles
* 2 groups
* Users -> groups
* Contacts -> groups
* One Group

This should expose functions, that the tests can call to seed more data into its db when. a test is running

3. seeds_scale.ex(s) - No work needs to be done for this

We also need to clean the tests for seeders and remove the fixtures until it's necessary and rethink this. We can do a few of them during the standup meetings

**Comment by ansh14j** [comment]
Remaining test files to be fixed

- [ ] test/glific/repo_test.exs (Lobo)
- [ ] test/glific/tags_test.exs (Lobo)
- [ ] test/glific/settings_test.exs (Pankaj)
- [ ] test/glific/searches_test.exs (Pankaj)
- [ ] test/glific_web/schema/contact_test.exs (Anshul)
- [ ] test/glific_web/schema/language_test.exs (Anshul)
- [ ] test/glific/templates_test.exs (Anshul)
