### ISSUE TITLE
Not receiving FRP program messages - Nayi Disha

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2012]
**Describe the bug**
Issue reported by Tania from Nayi Disha
Flow name: Z_Made By Glific team. (Please don't delete)
Date issue was faced: 29th Jan
Contact name who faced issue: Prachi Deo
Contact phone number who faced issue: 919398186534
Observed behaviour: Not receiving FRP program messages 
Expected behaviour: To receive messages at 8am everyday 
Was issue replicable: No, Just this user for now

**Comment by AkhileshNegi** [comment]
I looked into the issue but it seems the phone number  919398186534 was blocked and then deleted as there is no previous messages before 31st. Already communicated with Taniya from ND
