### ISSUE TITLE
Flows are getting executed itself, without any trigger

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2013]
**Screenshots:**
<img width="425" alt="Screenshot 2022-01-31 at 1 58 52 PM" src="https://user-images.githubusercontent.com/16541548/151761369-29eb7fa7-930a-41e3-bae3-be83a9216796.png">

**Comment by mohitsharma-22** [comment]
<img width="425" alt="Screenshot 2022-01-31 at 1 58 52 PM" src="https://user-images.githubusercontent.com/16541548/151761369-29eb7fa7-930a-41e3-bae3-be83a9216796.png">

**Comment by mohitsharma-22** [comment]
Organization name: Nayi Disha
Flow name: 02- ND - User type flow
Date issue was faced: 27-01-2022
Contact name who faced issue: Yesudas
Contact phone number who faced issue: 96893203190
Observed behaviour: Flow started itself
Expected behaviour: only keywords or triggers should start the flow
Was issue replicable: No, but it happened for more users (Varadarajan)
Steps to replicate: N/A

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 
```
Contact: Yesudas
History: 
1. Sent message on 27 Jan
2. As message was not a keyword it triggered default flow `01-ND Initial Workflow`
3. User sent second message
4. As part of the initiated flow `01-ND Initial Workflow` on receiving second message it moves to next node which in this case was `enter another flow `02-ND UserType Flow`


Contact: Varadarajan
History: 
1. Sent message on 27 Jan
2. As message was not a keyword it triggered default flow `01-ND Initial Workflow`
3. User didn't send second message, so flow moved to `no response node`
4. As part of the initiated flow `01-ND Initial Workflow` on not receiving any message it moves to no response node which in this case was `enter another flow `02-ND UserType Flow`
```
