### ISSUE TITLE
Upload the arogya world responses to GCS in the given CSV format

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2015]
## Task

Upload the arogya world responses to GCS in the given CSV format.

CSV format: https://docs.google.com/spreadsheets/d/1FbL2Ahg9JLbYLpJDxXVMldlLlMzyfJnJkJJ3uxCTdmY

**Comment by pankaj-ag** [comment]
@mdshamoon can we close this issue?

**Comment by mdshamoon** [comment]
Yes Pankaj. It is fixed now
