### ISSUE TITLE
Flows: Publishing empty flow 

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2020]
**Describe the bug**
When publishing an empty flow throws an error and the screen freezes.

**To Reproduce**
1. Create a new flow
2. Click on publish button 
3. Click on any option `Publish & Stay` or `Publish & go back`

**Expected behavior**
Empty flow should send a warning that flow contains no node similar to other flow validation errors without option to `Publish`

**Screenshots**
Sample screenshot of warning when publishing invalid flow
![image](https://user-images.githubusercontent.com/40158831/152101281-ad25f229-e925-4e78-a3aa-834de23e957b.png)

**Comment by pankaj-ag** [comment]
@AkhileshNegi check this one also. #1997 

Looks same to me.

**Comment by dlobo** [comment]
I treat this as a normal error. users can override and still publish the flow
