### ISSUE TITLE
HSM templates are not received by users on their whats App

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2034]
**Describe the bug**
TAP reported an issue, where they have started a flow for a collection and many users are not receiving the first HSM template on their What's APP. Checked all users are optedin before the date of execution of the flow.

Collection Name - **TLMP_Students**
Flow Name  - **TLMP Activity 1**
Contact who have not received the messages.
1.Shaiks
2.Faizan
3. Arsalan

Date executed on 3rd Feb 2022

**To Reproduce**
Not able to reproduce.

**Screenshots**
<img width="697" alt="Screenshot 2022-02-09 at 3 12 58 PM" src="https://user-images.githubusercontent.com/16541548/153177805-1a25ef00-bed1-461b-8e86-3e7af85f922b.png">

<img width="594" alt="Screenshot 2022-02-09 at 3 12 20 PM" src="https://user-images.githubusercontent.com/16541548/153177825-8698f673-26bf-46c6-be68-3e60519c4870.png">

<img width="690" alt="Screenshot 2022-02-09 at 3 13 25 PM" src="https://user-images.githubusercontent.com/16541548/153178191-ea401424-b53c-4868-ad70-7b5202e1b06d.png">

<img width="291" alt="Screenshot 2022-02-09 at 3 47 23 PM" src="https://user-images.githubusercontent.com/16541548/153177924-fb4922f0-6e98-457b-b6ea-b518cbc804e6.png">

<img width="885" alt="Screenshot 2022-02-09 at 3 14 47 PM" src="https://user-images.githubusercontent.com/16541548/153178041-4ba4fc44-7470-4bda-b2db-d039cc0f839f.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 I have sent an email to Gupshup about this. 
I will share more updates on this as soon as I receive the response.

**Comment by pankaj-ag** [comment]
@mohitsharma-22 it looks like it was the same WABA limit issue. We can close this since we are targeting this in a new issue.

**Comment by mohitsharma-22** [comment]
thanks, @pankaj-ag Added it to the documentation.
