### ISSUE TITLE
Add phone number in search for adding people in collection

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2039]

**Comment by mohitsharma-22** [comment]
Request received from LAHI.
They want to add people to a collection and need to search contacts with phone number. 
The Name shown in the list is not the contact name saved, it is the what app names, which are not correct to identify the persons.
<img width="847" alt="Screenshot 2022-02-10 at 6 11 03 PM" src="https://user-images.githubusercontent.com/16541548/153411021-3f097da9-3db4-46d8-ba4b-3b8636b3eb56.png">

**Comment by dlobo** [comment]
How about they do the following:

* Search for phone number in main screen
* The right contact is shown
* Choose contact
* Click on left arrow, and choose add contact to collection

I think the current implementation is not very scalable for large number of contacts and we might not want to invest too much time in it

**Comment by dlobo** [comment]
marking this as won't fix for now
