### ISSUE TITLE
ContactOpts on Search Query not working

### ISSUE THREAD

**Issue by claalmve** [glific/glific#204]
**Describe the bug**
The `contactOpts` parameter for the `search` query doesn't seem to be working. When I try to limit the number of contacts retrieved, nothing happens.

**Comment by dlobo** [comment]
query search($term: String!, $contactOpts: Opts, $messageOpts: Opts) {
  search(term: $term, contactOpts: $contactOpts, messageOpts: $messageOpts) {
    contact {
      id
      name
      phone
    }
    messages {
      id
      body
    }
  }
}

{
  "term": "alfredo",
  "messageOpts": {
    "limit": 3
  },
  "contactOpts": {
    "limit": 1
  }
}

**Comment by pankaj-ag** [comment]
@claalmve this is fixed and merge. Have a look and let me know in case you see any other issue with that.
Thanks

**Comment by pankaj-ag** [comment]
@claalmve closing this one. Feel free to reopen in case you found any issues with this.
