### ISSUE TITLE
Glific messaging to handle errors from WABA 

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2046]
We are starting to hit limits with WABA and need to handle error messages and make appropriate changes. Listing the errors that we are aware of right now, so we can handle them individually. We'll treat this as a meta issue, and create issues for each error

*First phase fixes*
* [x] #2047 
* [x] #2049 
* [x]  "Unable To Send Message | Check your wallet balance" - 1003
* [x] ["Message sending failed as the user is inactive for session message and not opted in for template message" - 1006](https://github.com/glific/glific/pull/2064)
* [x] ["Invalid Media Url" - 1010](https://github.com/glific/glific/pull/2064)
* [x] "contact Gupshup Team" - 500

*Second phase fixes*

* [ ] "Number of parameters does not match the expected number of params: number of localizable_params (1) does not match the expected number of params (0)" - 2000
* [ ] "Message failed to send because the receiver is on a version of WhatsApp that does not support this message" - 1026

We can use this query to get the latest stats from DB on errors:

```
SELECT
	count(id) AS count,
	"errors"::json -> 'payload' -> 'payload' ->> 'reason' AS reason,
	"errors"::json -> 'payload' -> 'payload' ->> 'code' AS code
FROM
	"public"."messages"
WHERE
	errors != '{}'
GROUP BY
	reason,
	code
ORDER BY
	count DESC
```

**Comment by pankaj-ag** [comment]
I think we can skip this error, since it happend only with tap. 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/10670690/154477147-ab7af99b-851e-41f7-b860-3911ad45fe1d.png">

**Comment by pankaj-ag** [comment]
Contact Gupshup team, 

This is when the Gupshup was down and they made some changes in the API. 

After that, we have put a lot of checks and logs for these types of errors. 

The last entry was on 2021-06-14 12:54:42.947569 UTC, so skipping this error for now.

**Comment by pankaj-ag** [comment]
Putting this issue on hold for now.
