### ISSUE TITLE
Key word not responding the flow

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2056]

**Comment by mohitsharma-22** [comment]
COntact send keywords multiple times, but the flow didn't start.
Not able to replicate with other users.
<img width="658" alt="Screenshot 2022-02-16 at 12 13 53 PM" src="https://user-images.githubusercontent.com/16541548/154210912-d156365c-26f7-4ce4-bd9a-d63c5efe139d.png">

<img width="1298" alt="Screenshot 2022-02-16 at 12 13 22 PM" src="https://user-images.githubusercontent.com/16541548/154210923-0efe8b2d-0e6a-4443-ab1b-739b116b8876.png">

![screenshot_2022-02-16-11-29-21-60_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/16541548/154210954-25432ed3-398c-44ad-b22f-741d19791b76.png)

**Comment by pankaj-ag** [comment]
@mohitsharma-22 this user is in **Housing provider** flow, at wait for time node. 
Ignore keyword is also enabled to **Housing provider**  flow that's why it's not triggering the Hi keyword flow.

Please add this to your troubleshooting list of these types of issues.
