### ISSUE TITLE
Flows are not returning back to the parent flow after completion

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2061]
Issue happend on 16th Feb 2022
user - Mugdha Kalra, ID - https://ndrcsupport.tides.coloredcow.com/chat/82051
 Started the communication from **Help Center** flow
then move to **03-7-ND Parent workflow-SBIMF** flow, from it move to **Optin/Optout** flow, then move to **Optin** flow

On completion it should come back to the **03-7-ND Parent workflow-SBIMF** flow and send a message **Future readiness program**, but it didn't work. The communication was stopped at **Optin** flow.

<img width="985" alt="Screenshot 2022-02-16 at 7 23 32 PM" src="https://user-images.githubusercontent.com/16541548/154278960-2bfa4b75-fd78-48a1-a3d7-7bc87270ea4f.png"> 

<img width="546" alt="Screenshot 2022-02-16 at 7 24 09 PM" src="https://user-images.githubusercontent.com/16541548/154278926-c2a169a4-2001-4683-a468-dd22e0516f99.png">

<img width="665" alt="Screenshot 2022-02-16 at 7 24 02 PM" src="https://user-images.githubusercontent.com/16541548/154278943-344ce7f4-978e-46c9-ad9e-a7bf65ce90f6.png">

<img width="1123" alt="Screenshot 2022-02-16 at 7 23 56 PM" src="https://user-images.githubusercontent.com/16541548/154278951-605c974b-4dd3-4d63-980e-2fbe421f01a0.png">

<img width="760" alt="Screenshot 2022-02-16 at 7 23 47 PM" src="https://user-images.githubusercontent.com/16541548/154278958-169ea701-b41e-4bf7-a0ea-3259225bf23a.png">

**Comment by mohitsharma-22** [comment]
Issue happend on 16th Feb 2022
user - Mugdha Kalra, ID - https://ndrcsupport.tides.coloredcow.com/chat/82051
 Started the communication from **Help Center** flow
then move to **03-7-ND Parent workflow-SBIMF** flow, from it move to **Optin/Optout** flow, then move to **Optin** flow

On completion it should come back to the **03-7-ND Parent workflow-SBIMF** flow and send a message **Future readiness program**, but it didn't work. The communication was stopped at **Optin** flow.

<img width="985" alt="Screenshot 2022-02-16 at 7 23 32 PM" src="https://user-images.githubusercontent.com/16541548/154278960-2bfa4b75-fd78-48a1-a3d7-7bc87270ea4f.png"> 

<img width="546" alt="Screenshot 2022-02-16 at 7 24 09 PM" src="https://user-images.githubusercontent.com/16541548/154278926-c2a169a4-2001-4683-a468-dd22e0516f99.png">

<img width="665" alt="Screenshot 2022-02-16 at 7 24 02 PM" src="https://user-images.githubusercontent.com/16541548/154278943-344ce7f4-978e-46c9-ad9e-a7bf65ce90f6.png">

<img width="1123" alt="Screenshot 2022-02-16 at 7 23 56 PM" src="https://user-images.githubusercontent.com/16541548/154278951-605c974b-4dd3-4d63-980e-2fbe421f01a0.png">

<img width="760" alt="Screenshot 2022-02-16 at 7 23 47 PM" src="https://user-images.githubusercontent.com/16541548/154278958-169ea701-b41e-4bf7-a0ea-3259225bf23a.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 can you update the status here.

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you update the status here so that Mohit can add this to the trouble shoot list.

**Comment by AkhileshNegi** [comment]
Sure @pankaj-ag  I'll update the flow first and then test it. Once things are working, I'll pass it on

**Comment by AkhileshNegi** [comment]
Updated flow and interactive message to use 👍 and 👎 instead of using `flow keywords` so it does not trigger some other flow when button is clicked
@mohitsharma-22 You can test from your end now and then share your observations here

**Comment by AkhileshNegi** [comment]
Closing this as confirmed by [user](https://discord.com/channels/717975833226248303/780402199679336469/943790797680156673)
