### ISSUE TITLE
Does re-uploading the onboarded contact  update the existing status

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2066]
Need to check the bulk contact onboarding feature for the use case mentioned below

_When a user sends STOP, the user will get opt out, we want to make sure that we are blocked from being able to message that user again, even if we upload that user's contact the next time we are planning to send a message. In other words, the act of uploading a contact should not change that contact's status from stopped to unstopped._

**Comment by pankaj-ag** [comment]
@wevekamola  How they are uploading the contacts?
We can put a check for opt-out contacts, but that is not there in the code.

**Comment by AkhileshNegi** [comment]
@wevekamola 
When contact is first uploaded
```
{
  bsp_status: :hsm,
  id: 17,
  inserted_at: ~U[2022-02-21 11:59:29.241980Z],
  language_id: 1,
  last_communication_at: ~U[2022-02-21 11:59:29Z],
  name: "John Doe",
  optin_message_id: nil,
  optin_method: "Import",
  optin_status: true,
  optin_time: ~U[2021-03-09 12:34:25Z],
  optout_method: nil,
  optout_time: nil,
  organization_id: 1,
  phone: "919997407468",
  status: :valid,
  updated_at: ~U[2022-02-21 11:59:29.245971Z],
}
```

When contact is opted out

```
%{
  bsp_status: :none,
  id: 17,
  inserted_at: ~U[2022-02-21 11:59:29.241980Z],
  language_id: 1,
  last_communication_at: ~U[2022-02-21 11:59:29Z],
  name: "John Doe",
  optin_message_id: nil,
  optin_method: nil,
  optin_status: false,
  optin_time: nil,
  optout_method: "Glific Flows",
  optout_time: ~U[2022-02-21 12:04:02Z],
  organization_id: 1,
  phone: "919997407468",
  status: :invalid,
  updated_at: ~U[2022-02-21 12:04:02.108238Z],
}
```

When contact is opted in again via upload

```
%{
  bsp_status: :hsm,
  id: 17,
  inserted_at: ~U[2022-02-21 11:59:29.241980Z],
  language_id: 1,
  last_communication_at: ~U[2022-02-21 11:59:29Z],
  name: "John Doe",
  optin_message_id: nil,
  optin_method: "Import",
  optin_status: true,
  optin_time: ~U[2021-03-09 12:34:25Z],
  optout_method: "Glific Flows",
  optout_time: ~U[2022-02-21 12:04:02Z],
  organization_id: 1,
  phone: "919997407468",
  status: :invalid,
  updated_at: ~U[2022-02-21 12:04:36.922973Z],
}
```

The same contact is updated but the status remains invalid and it has both entered for opted-in and opted-out which should be corrected

**Comment by pankaj-ag** [comment]
@dlobo I think we should always skip the re-optin if contact has opted out. This will remove the issue to spam the user by mistake if they already opted out. 

let me know your thoughts.

**Comment by pankaj-ag** [comment]
@wevekamola I have fixed this. 
Now if you re-upload the contact when he is opted out, the status won't change.
