### ISSUE TITLE
Message sent twice from the flow

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2067]

**Comment by mohitsharma-22** [comment]
Mukkamar reported the message was sent twice and wants to know the reason of it.
I checked the message comes just after webhook, which can be a reason and help to debug.
FLow name - **Physical Flow 7**
Date and time - **18 the Feb 2022 - at 15 :54**

Contact name - **Tanu**.

<img width="1001" alt="Screenshot 2022-02-21 at 5 05 50 PM" src="https://user-images.githubusercontent.com/16541548/154948193-033e695f-3d33-4488-8069-284daaec2643.png">

<img width="1323" alt="Screenshot 2022-02-21 at 5 06 24 PM" src="https://user-images.githubusercontent.com/16541548/154948171-c3460b40-fcfe-40c5-956a-1f0a186faece.png">

**Comment by AkhileshNegi** [comment]
Adding more details for better searching
**Contact Phone:** 918291098045
**Contact ID:** 129364

**Comment by AkhileshNegi** [comment]
Highly likely that the webhook called returned response twices as there are two entries in webhook log table for URL used in the flow with success status for same flow
**URL:** `https://cohesive-idiom-312313.uc.r.appspot.com/v1/api/webhook`
**Flow:** `Physical Flow 7`
**Timing:** 
First: `2022-02-18 10:20:34`
Second: `2022-02-18 10:24:49`
**Request JSON:**
```
{"contact": "918291098045", "item_code": "P7_TECHNIQUE", "event_name": "add-points", "school_code": "CS08", "organization_id": 18}
```
**Response JSON:**

```
{"msg": "success"}
```

**Comment by dlobo** [comment]
seems like no progress or work needed. closing
