### ISSUE TITLE
Clean the organisation onboarding flow.  

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2071]
- Currently, when we fill out the form following things happen
- 1. We validate all the values and create an organization.
- 2. We create a contact. 
- 3. We put the BSP credentials
- 4. Mark organization inactive. 

We can not make it fully automatic since we have to verify the domains from Go daddy. (We should check if can create that programmatically too.)

Apart from that, Now we need to write a function in the onboard/queries function and run the following functions from that. 

- [x] 1. Add simulators 
- [x] 2. Add default collections 
- [x] 3. Add default flows
- [x] 4. Optin and Oputout flows
- [x] 5. sync_hsm_templates
- [x] 6. submit otp template
- [x] 7. Add saas admin

All the above functions are defined in the seed_migration file so we just need to call them from a single place. 

Later we can add the partner APIs and set the callback URL etc and can reduce more manual steps.

**Comment by pankaj-ag** [comment]
@abhi1203 we need to update the onboarding form with all the contents we need. 
Like create a SAAS admin

**Comment by abhi1203** [comment]
@pankaj-ag  Added this: 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/16714604/183024885-697c96d2-7d3e-4fc7-8aa5-e53d4f7e8e9e.png">

Let me know if we need to add anything else.
design file: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/jgkQgko
