### ISSUE TITLE
Search not returning desired results

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2073]

**Comment by mohitsharma-22** [comment]
Issue reported by Nayi Disha. 
The search is not having desired results.

Saved Search Name :- **Queries:Counsellor**

Contact missing in the search:- **Reameena**

Tested on **23rd Feb 2020 at 12 O Clock**

<img width="901" alt="Screenshot 2022-02-23 at 11 52 03 AM" src="https://user-images.githubusercontent.com/16541548/155274926-9ebd2033-234a-47de-b09e-b6c18c685eb6.png">

<img width="872" alt="Screenshot 2022-02-23 at 11 51 36 AM" src="https://user-images.githubusercontent.com/16541548/155274934-6d41e146-fc01-4618-8b3f-1c4c0783d9e2.png">

<img width="501" alt="Screenshot 2022-02-23 at 11 52 22 AM" src="https://user-images.githubusercontent.com/16541548/155274910-6be87626-2c5e-4b30-a22c-6c48382cc114.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 I can see the contact in the results. 
Saved search 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/10670690/155294819-6c613d0c-5df1-4edc-82b5-4f6d6e007f95.png">

**Comment by AkhileshNegi** [comment]
@pankaj-ag I checked this able to replicate in local. Sharing steps here for ease of replicating the issue
1. total contacts in `Contacts` table should be more than 25(e.g. 35)
2. label some messages of Contacts (e.g. `counsellor_queries`)
3. When querying the labeled messages in DB. It is returning 10 results

<img width="927" alt="image" src="https://user-images.githubusercontent.com/40158831/155298893-4177e230-412b-46a7-af84-7e7e5661dee3.png">
Query: 

```
SELECT DISTINCT(contact_id) from messages WHERE  flow_label like '%counsellor_queries%'
```
4. Create saved search with message label
<img width="529" alt="image" src="https://user-images.githubusercontent.com/40158831/155299113-3022a905-3185-40e3-93e5-9637dbb603b2.png">
5. Use saved Search
6. The total contacts count do not match
<img width="346" alt="image" src="https://user-images.githubusercontent.com/40158831/155299205-c991e33b-9222-4462-a2db-8940ad1ec092.png">

**Comment by pankaj-ag** [comment]
Ohh got it. 

So we need to check with the @glific/glific-frontend-team how they are showing the search multi results. 

Since we are already sharing those messages in the labels section.
