### ISSUE TITLE
Remove optin keyword discrepancy 

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2075]
Currently, if somebody opts out we start the optin flow whenever the user sends a message to glific. 
We determine the OPTIN flow from optin keyword only.
Sometimes it creates confusion [mentioned in this issue. ](https://github.com/glific/glific/issues/2070)

Proposed solution: 

Since optin flow is very important for all organizations we can define a new selection dropdown in the organization settings. (It's the same as the new contact flow funcationality).

**Comment by dlobo** [comment]
@mdshamoon can you please add stuff similar to the new contact workflow for optin workflow

**Comment by mdshamoon** [comment]
@dlobo we please add the optinFlowId attribute in the updateOrganization API. I am able to fetch it using the organization API but not update it.

**Comment by dlobo** [comment]
will be patching it in a few minutes. doing final checks and merging. can u check and resolve

**Comment by mdshamoon** [comment]
Looks good @dlobo. Closing
