### ISSUE TITLE
Incorrect timestamp format in sample import csv

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2079]
**Describe the bug**
The contact onboarding sample sheet has the optin timestamp incorrect.

**To Reproduce**
1. Go to Contact Management
2. Click on Upload contacts
3. Download the sample sheet
4. The timestamp mentioned is 3/9/2021_12:34:25

**Expected behavior**
The expected timestamp format is 2021-03-09_12:34:25 

**Screenshots**
<img width="613" alt="Screenshot 2022-02-23 at 5 50 40 PM" src="https://user-images.githubusercontent.com/29367838/155319089-2fdeb973-75be-41db-be0b-53114e935b25.png">

**Comment by AkhileshNegi** [comment]
@wevekamola  This is fixed now, You can check from your end as well
