### ISSUE TITLE
Flow is getting stuck for some Emojis   

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2092]
**Org:** Bandhu
**Flow:** existing2

Emojis which are not being read correctly: 📖 and 📱

<img width="808" alt="Screenshot 2022-03-01 at 9 21 03 AM" src="https://user-images.githubusercontent.com/29367838/156101475-573fe7db-3a8d-4128-811b-99e1f73d4a6b.png">

<img width="575" alt="Screenshot 2022-03-01 at 9 23 35 AM" src="https://user-images.githubusercontent.com/29367838/156101713-9cb41577-eaa8-4275-9b5f-c288f6c2fc09.png">

Other Emojis are working fine on the same flow

**Comment by mohitsharma-22** [comment]
Adding details of error received today while testing.

<img width="862" alt="Screenshot 2022-03-02 at 12 35 02 PM" src="https://user-images.githubusercontent.com/16541548/156312104-bb799116-de19-4839-b588-c7dc924375f7.png">

**Comment by mdshamoon** [comment]
@wevekamola issue was not with the emoji but with the interactive message in the next node. The interactive message was deleted by someone and the flow was not able to move forward.
@mohitsharma-22 please add this in the debugging checklist to check of the interactive messages is present or not. We are adding support to know if the interactive message is present in the flow or not but it will take some time.

@mohitsharma-22 for the character policy violation we can add frontend validation. Let me create an issue for this

**Comment by wevekamola** [comment]
@mdshamoon The emoji issue has been resolved. I have tested it and Jocab also verified it. So the emoji issue is fixed now. Thanks

**Comment by wevekamola** [comment]
@mohitsharma-22 @mdshamoon For the WhatsApp character policy violation issue, Jacob has removed the emojis from the title and added them to the description, which has resolved the issue.

Also as the warning or error was not getting shown in the flow preview simulator or while creating the interactive list, figuring it out was difficult.  @mdshamoon has created a task for this https://github.com/glific/glific-frontend/issues/1947 , so will track the progress there.

Will be closing this one.
