### ISSUE TITLE
Flow stuck for a single user

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2096]
Contact is opted in .
Flows are active and working for another users.

![Sruty](https://user-images.githubusercontent.com/16541548/156165842-9dfe6fe0-e667-487d-9f72-56f63c30afe4.jpeg)

<img width="1025" alt="Screenshot 2022-03-01 at 4 34 36 PM" src="https://user-images.githubusercontent.com/16541548/156165880-115624c0-7cf0-4255-a3af-1c8f2318a279.png">

**Comment by pankaj-ag** [comment]
We are waiting on GP to come back and give an update.
