### ISSUE TITLE
Impersonate the contact in Glific

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2103]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is tough to get the details from the contact to see how the messages are delivered to the contact's whatsAPP.

**Describe the solution you'd like**
Today's standup team decided to simulate the contact with the support account number and use it to investigate the issue.

The contact's phone number is Impersonate with the support phone number. And when the support phone sends the message to the bot and receives the messages as the contact on his/her phone.

**Comment by wevekamola** [comment]
@mohitsharma-22 This issue has already been created here #2097. Maybe you can add your comments on the previous issue and delete this one.

**Comment by mohitsharma-22** [comment]
ok @wevekamola closing this one.
