### ISSUE TITLE
Incorrect value saved in BQ

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2108]
Video Volunteer reported an issue for wrong data saved in the BQ.
When the user selects “Madhya Pradesh”, at the backend the response gets stored as “Uttar” which is the keyword when the user selects “Uttar Pradesh”.

![unknown](https://user-images.githubusercontent.com/16541548/156506463-34cbc63e-3d9d-4884-91ff-ab61541dc7bb.png)

![unknown2](https://user-images.githubusercontent.com/16541548/156506450-0038ee18-62ae-421b-a6c4-0fc2e5bf34a8.png)

![unknown1](https://user-images.githubusercontent.com/16541548/156506457-cca765c7-77b7-4f39-9f72-ba8d6351a39f.png)

![unknown3](https://user-images.githubusercontent.com/16541548/156506442-ba22c53a-fdfd-4470-b49e-8202e214c273.png)

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 is this fixed?

**Comment by mohitsharma-22** [comment]
Yes, @AkhileshNegi Thanks for checking on this.
Closing this one now.
Below comment from discord.
vivekamola — Yesterday at 13:04
Hey @grahesh I looked into it and in the backend as well it was saving "Uttar" for "Madhya Pradesh". The issue was with the flow configuration, by using has any of the phrase and both the input has Pradesh as common that's why it was picking Uttar first. I have updated the wait for response with this configuration and verify the updates. Please have a look and let me know
