### ISSUE TITLE
Offset and limit in Session Template listing query

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#211]
**Is your feature request related to a problem? Please describe.**
Like tags, we need paginated data for session templates. Right now, all the templates are returned by the API at once.

**Describe the solution you'd like**
Have an offset and limit input in the `sessionTemplates` query, similar to tags.

**Comment by pankaj-ag** [comment]
@rathorevaibhav this is fixed. have a look and close the issue

**Comment by pankaj-ag** [comment]
@rathorevaibhav this is fixed. Feel free to reopen in case you found any issue with this.
