### ISSUE TITLE
Flow got killed for a contact

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2111]
TAP Reported an issue the flow got killed for contact for not responding.
Contact Name - kumarchetnya548
When it happened  - 4th March 2022 - 10:36 AM
FLow - TLMP_Activity5

As user selected the button Start Activity.
The below message should go next as per the flow.
Super! Here is an easy Activity for you 😎

✔️1) See full activity video 👀 
✔️2) Send your work to me 📝

<img width="569" alt="Screenshot_2022-03-04_at_8 35 33_PM" src="https://user-images.githubusercontent.com/16541548/156882435-1883d3f5-ecd4-421b-9fab-4a7aefded6ad.png">

<img width="998" alt="Screenshot_2022-03-04_at_8 31 28_PM" src="https://user-images.githubusercontent.com/16541548/156882439-e93dc067-fd54-4116-8a0a-ea8468edfdb8.png">

<img width="746" alt="Screenshot 2022-03-05 at 5 41 53 PM" src="https://user-images.githubusercontent.com/16541548/156882444-dc8d078a-4b32-42ad-9668-0a53290869b8.png">

**Comment by pankaj-ag** [comment]
Another incident in the same platform on 10th March.
https://tap.tides.coloredcow.com/contact-profile/132489

**Comment by dlobo** [comment]
could not replicate
