### ISSUE TITLE
Collection chat screen doesn't show sent HSM template 

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2121]
**NGO:** Antarang

**Issue:** They send an HSM message to a collection. On the collection chat screen, it's showing no message sent but when we are checking on the chat screen of students present in that collection it shows the message has been sent. Ideally, it should show the HSM message on the collection chat also.

**Collection Name:** Class 10

**HSM Template name:** career yatra

**Sharing issue images below**

HSM message on the student chat screen
<img width="700" alt="Screenshot 2022-03-15 at 4 06 09 PM" src="https://user-images.githubusercontent.com/29367838/158377745-47df7199-5b8d-4d96-b442-91e5c1cf387d.png">

Collection chat screen shows no message
<img width="700" alt="Screenshot 2022-03-15 at 4 05 33 PM" src="https://user-images.githubusercontent.com/29367838/158377689-02630d0d-71b9-4233-9dc2-2bb7c5bdb75f.png">
 
The issue occurs in 15 March 2022 around 1:09 PM

**Comment by pankaj-ag** [comment]
@wevekamola I did some research and found that this message is triggered by an individual user. 

For now, we are not showing the user name in case it's triggered by the user. I will fix that/
