### ISSUE TITLE
Contact getting messages more than one when broadcasting from a collection

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2147]
Date 26 March 2022
https://reapbenefit.tides.coloredcow.com/chat/8692

Question - Is the person can be added more than once in a collection? which can be a reason for this.

**Comment by dlobo** [comment]
no, person cannot be added more than once to a collection, its a database constraint

**Comment by mohitsharma-22** [comment]
@dlobo Contact ID is showing the same. Let me know if I am missing anything

<img width="1011" alt="Screenshot 2022-04-01 at 2 00 06 PM" src="https://user-images.githubusercontent.com/16541548/161226687-a189a2a7-b666-40ca-ba93-e9bf679aa3d5.png">
.

**Comment by pankaj-ag** [comment]
@mohitsharma-22 not able to replicate. Please Re-Open this issue if you see this error again.
