### ISSUE TITLE
Contact are not getting messages and are stuck

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2148]
Date when happened = 26th March 2022
It is not for everyone. Selected users are getting stuck. Not able to replciate
Total contacts were 32 and only 10-12 got stuck at this place and did not get the messages

Example - 
https://reapbenefit.tides.coloredcow.com/contact-profile/148734
https://reapbenefit.tides.coloredcow.com/chat/148745

**Comment by pankaj-ag** [comment]
@mohitsharma-22 
This looks like the first node issue. Sometimes it gets a different node as a first node if it's two closes. I would suggest not to have any node in parallel to the first node. 

For now you can send a message to those users manually or as a background flow and when they will reply it will resume the street audit flow.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/10670690/160607143-1b2a5bfc-c3d7-40a1-b3fb-3b3a14d14513.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 please keep us updated with the testing here.

**Comment by dlobo** [comment]
I dont believe its first node issue assuming flow is same as whats shown above. its higher than the rest

**Comment by pankaj-ag** [comment]
@dlobo we checked few contacts they were added to the street audit collection. 
and when I checked the flow context they were waiting on the wait for response node. 

The only thing was they did not get the first message. 

I will look into this more closely.

**Comment by mohitsharma-22** [comment]
@pankaj-ag Thanks for checking back on this one.

I tested today. I received the message on my whats App, but I am not able to see that on the chat screen. I refreshed the screen multiple time, but was unable to see the message.

<img width="974" alt="Screenshot 2022-04-01 at 2 35 35 PM" src="https://user-images.githubusercontent.com/16541548/161234420-8b39bc31-0f35-4f0f-8958-1e4af08a275b.png">


<img width="990" alt="Screenshot 2022-04-01 at 2 35 27 PM" src="https://user-images.githubusercontent.com/16541548/161234488-85360043-dcc0-4f70-82b1-a2026ea161cf.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 I can see that message. It might be the socket issue that Shamoon is taking care of.
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/10670690/161473061-1aa562ad-cd84-4076-8ff4-58809f3e6699.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 closing this issue now. Please let me know if this happens again.
