### ISSUE TITLE
Flow is getting terminated in between for all the users

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2154]
FLow Name - LOKAL_NITI_Flow

Flow gets stopped after **Do you think public transportation is the most efficient way for you to commute?** message.
There is an interactive message after that, but it is not getting sent to the flow.
In contact history, it says the flow is terminated.

<img width="800" alt="Screenshot 2022-03-29 at 1 26 41 PM" src="https://user-images.githubusercontent.com/16541548/160562317-9d8af88f-0bbc-45fd-ba92-9fb9f96efdf8.png">

<img width="990" alt="Screenshot 2022-03-29 at 1 26 28 PM" src="https://user-images.githubusercontent.com/16541548/160562332-08454e16-2986-45e8-a14e-662a68f986b6.png">

**Comment by gauthamraje** [comment]
Following..

**Comment by pankaj-ag** [comment]
@gauthamraje this is because of the infinite loop. 
Looks like we are not handling that properly and we need to think how we can do that.

**Comment by gauthamraje** [comment]
@pankaj-ag what do you mean by infinite loop? @mohitsharma-22 told this is due to same outbound message being shared more than 3 times.

**Comment by dlobo** [comment]
have a first cut at a good fix for this issue :) We used to rely only on message body which is WRONG (I'm to blame for this). Now we are relying on the node uuid, which is. more accurate, so u can have the same interactive message being used (;like yes/no for all your questions) and we do the right thing
