### ISSUE TITLE
Flow messages are not seen on users WhatApp

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2155]
Issue date - 29 March 2022
Users who are having an issue 
1. Aman - 8630036345
2. Harish - 8800128259

The user has sent a keyword from the phone. But no response is coming back from BOT.

Users are active. It is not working for most of the users. But it is working for me and Prerak from the Dhwani team.

<img width="1342" alt="Screenshot 2022-03-29 at 4 22 03 PM" src="https://user-images.githubusercontent.com/16541548/160595968-6e236ab1-f601-44a9-8d3d-0e1857681158.png">

<img width="1326" alt="Screenshot 2022-03-29 at 4 21 55 PM" src="https://user-images.githubusercontent.com/16541548/160595990-7eddf026-4ac5-43de-a2dd-8682e6c11fe6.png">

![MicrosoftTeams-image_5](https://user-images.githubusercontent.com/16541548/160596035-9e72841d-9ef4-47b1-a2e5-e4e41b761001.png)

![MicrosoftTeams-image_6](https://user-images.githubusercontent.com/16541548/160596039-5f041baa-bf2b-43b3-922c-1b714e0925f1.png)

**Comment by AkhileshNegi** [comment]
The contacts were not opted-in and in Gupshup Enterprise, we cannot send even a session message if the contact is not opted in
