### ISSUE TITLE
Flow stuck after the a interactive message. in the flow

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2156]
Flow is not moving forward after this message.

<img width="892" alt="Screenshot 2022-03-29 at 4 29 42 PM" src="https://user-images.githubusercontent.com/16541548/160597661-3a5fde72-c048-4941-a6c4-ccdb9f447c71.png">

<img width="912" alt="Screenshot 2022-03-29 at 4 27 47 PM" src="https://user-images.githubusercontent.com/16541548/160597672-84e66f99-4048-482c-893e-b4e57ef2b506.png">

**Comment by AkhileshNegi** [comment]
For now keep the title check on for Gupshup Enterprise as it does not support sending interactive button without title
<img width="553" alt="image" src="https://user-images.githubusercontent.com/40158831/160601937-313fd804-c7ed-4e6d-8026-b296996df7ef.png">
