### ISSUE TITLE
Kannada characters are treated as emojis and throwing error in interactive message

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2159]
Checked no emojis in the interactive message. But it is throwing error "Emojis not allowed".

<img width="999" alt="Screenshot 2022-03-30 at 10 04 03 AM" src="https://user-images.githubusercontent.com/16541548/160752215-63dd1d4c-0231-4174-be8e-96b0e0c55fc3.png">

<img width="1344" alt="Screenshot 2022-03-30 at 10 04 24 AM" src="https://user-images.githubusercontent.com/16541548/160752246-ae8eb33d-463c-4f6e-9b00-7913b9c664f6.png">

**Comment by pankaj-ag** [comment]
This is fixed. Closing now.
