### ISSUE TITLE
Enhance search feature by adding filters for Optin contacts, people in a certain flow, file selection (image/video/pdf)

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#2175]
While filtering contacts, whether in a collection or searching, NGOs need more search filters:

1. Check contact status - optin, in session, opted-out
2. Check which flow they are in - This could be a dropdown with search selection of flows.
3. Check if the chat includes a link, image, video, audio, etc... - Will be helpful for cases where such media is required as response

**Comment by pankaj-ag** [comment]
@abhi1203 this makes sense to me. 
I did not get the third pointer though, do you mean to search for the contacts if they received the media in a flow or in their complete chat history?

**Comment by pankaj-ag** [comment]
One more thing.
We have no way to search a contact by their registered name and it is really difficult to identify someone from their Whatsapp username
