### ISSUE TITLE
Investigate why stripe generated wrong invoices.  

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2187]
- There was some discrepancy in Indus action and Headstream invoice.

**Comment by mohitsharma-22** [comment]
Headstream invoice which has incorrectly applied balance.
<img width="1228" alt="Screenshot 2022-04-04 at 11 37 27 AM" src="https://user-images.githubusercontent.com/16541548/161483559-e1d017a7-7941-4055-96eb-424de4d391da.png">

Indus action invoices - had incorrect invoices.
<img width="1205" alt="Screenshot 2022-04-04 at 11 42 44 AM" src="https://user-images.githubusercontent.com/16541548/161483988-8419b9c4-cc3c-4cb1-ba4e-cbd5be46a26f.png">

**Comment by mdshamoon** [comment]
The issue with Headstream invoice is resolved now. There was some applied balance left for the customer that was added in the invoice.

**Comment by AkhileshNegi** [comment]
@mdshamoon should we close this then?

**Comment by mdshamoon** [comment]
@AkhileshNegi for indus action the credit balance was applied multiple times. We still need to check that.

**Comment by pankaj-ag** [comment]
@AkhileshNegi @mdshamoon can we close this issue since you have answers of all the questions.
