### ISSUE TITLE
Trigger sending message multiple times

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2197]
**Describe the bug**
As shown in the screenshot same message was sent multiple times to contacts on `2022-03-28` from the triggered flow.

**Screenshots**
<img width="887" alt="image" src="https://user-images.githubusercontent.com/40158831/162373846-35dc4ea4-36b7-41ed-b190-89053f710ed2.png">

**Details**
Organization name:  NayiDisha
Flow name: Z_Made By Glific team. (Please don't delete)
Date issue was faced: 2022-03-28
Contact name who faced an issue: `Manoranjani Bannu` from collection `FRP Test Series`

**Comment by AkhileshNegi** [comment]
**Sample Contact ids:** 148392, 140747
**Organization name:** NayiDisha
**Message ids:** 

6446620, 6446614, and 6446591 for contact id `148392`
6446444, 6446422 for contact id `140747`

**Date:** 2022-03-28 
**Trigger name:** Z_Made By Glific team. (Please don't delete)_16/02/2022_11:00AM
**Collection name:** FRP Test Series
**Logs:**

executing trigger: Z_Made By Glific team Logs

Mon Mar 28 2022 11:42:57 web.1 | 06:12:57.795 user_id=103 org_id=22 [info] executing trigger: Z_Made By Glific team. (Please don't delete)_16/2/2022_11:00AM for org_id: 22 [metadata](https://logflare.app/sources/10694/search?querystring=%22executing+trigger%3A+Z_Made+By+Glific+team%22+t%3A2022-03-%7B28..29%7DT00%3A00%3A00+c%3Acount%28%2A%29+c%3Agroup_by%28t%3A%3Ahour%29&tailing%3F=false#)


updating trigger: Z_Made By Glific team Logs

Mon Mar 28 2022 11:42:57 web.1 | 06:12:57.795 user_id=103 org_id=22 [info] updating next trigger time for trigger: Z_Made By Glific team. (Please don't delete)_16/2/2022_11:00AM of org_id: 22 with time 2022-03-29 05:30:58Z [metadata](https://logflare.app/sources/10694/search?querystring=%22updating+next+trigger+time+for+trigger%3A+Z%22+t%3A2022-03-%7B28..29%7DT00%3A00%3A00+c%3Acount%28%2A%29+c%3Agroup_by%28t%3A%3Ahour%29&tailing%3F=false#)

Starting Flow Logs

Mon Mar 28 2022 11:42:58 web.1 | 06:12:58.017 user_id=103 org_id=22 [info] Starting flow: Z_Made By Glific team. (Please don't delete) for trigger: Z_Made By Glific team. (Please don't delete)_16/2/2022_11:00AM of org_id: 22 with time 2022-03-29 05:30:58Z [metadata](https://logflare.app/sources/10694/search?querystring=%22Starting+flow%3A+Z%22+t%3A2022-03-%7B28..29%7DT00%3A00%3A00+c%3Acount%28%2A%29+c%3Agroup_by%28t%3A%3Ahour%29&tailing%3F=false#)

**Comment by pankaj-ag** [comment]
We will take a look and when we start working on the #2240
