### ISSUE TITLE
BroadcastStats api giving errors

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2203]
**Describe the bug**
BroadcastStats api giving errors 

**To Reproduce**
1. Trigger BroadcastStats APi for any flowBroadcast
2. It shows an error in the backend console

**Expected behavior**
It should give the correct result for stats

**Screenshots**
<img width="474" alt="image" src="https://user-images.githubusercontent.com/32592458/163133638-2539c645-6770-487b-9293-4299603397fb.png">

**Comment by pankaj-ag** [comment]
Closing this one, we can track all the queries in https://github.com/glific/glific/issues/2208
