### ISSUE TITLE
Nudge - Enterprise portal - Contact not getting HSM delivered even the contact is opted-in

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2209]
<img width="1220" alt="Screenshot 2022-04-18 at 4 20 31 PM" src="https://user-images.githubusercontent.com/16541548/163798488-f4c96c3a-4d9e-4170-9584-b945a67a9d51.png">

<img width="1566" alt="Screenshot 2022-04-18 at 4 20 18 PM" src="https://user-images.githubusercontent.com/16541548/163798533-48f4742b-ab26-4b38-bb96-1fb12fe3f325.png">

**Comment by AkhileshNegi** [comment]
I looked into the issue and for the same contact, messages were sent till the 12th and the issue started when sending messages from 14th onwards.
For other contacts sending template messages is working fine.
So based on the error, the contact opted out between 12th April and 14th April. I have sent mail to the Gupshup team to check when and how the contact opted out.

**Comment by pankaj-ag** [comment]
Closing this one due to inactivity. We did not face this issue again so it's possible that contact get's opeted out.
