### ISSUE TITLE
Nudge - Enterprise portal - Images are not getting delivered to WA in interactive message

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2210]
Checked the flow is published.
The interactive message is having attachment. But the attached is not delivered to whatsApp.

<img width="625" alt="Screenshot 2022-04-18 at 4 28 24 PM" src="https://user-images.githubusercontent.com/16541548/163799204-1526f634-1b8b-42b2-8157-c8689c4b62af.png">

<img width="1236" alt="Screenshot 2022-04-18 at 4 28 05 PM" src="https://user-images.githubusercontent.com/16541548/163799236-c4c6a8d0-9e14-4b7b-85d5-125f096f64d7.png">

<img width="986" alt="Screenshot 2022-04-18 at 4 30 03 PM" src="https://user-images.githubusercontent.com/16541548/163799296-6df75f61-eaca-40fc-abc4-57229ff7e220.png">

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 We have not added support for Media support in interactive message for Gupshup Enterprise yet

**Comment by AkhileshNegi** [comment]
Will add support to it once we get confirmation from Dhwani Team
