### ISSUE TITLE
Send contact history table to bigquery

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2215]
As the history table is getting bigger we should move that to bigquery and archive the data from glific database.

**Comment by siddhant3030** [comment]
@pankaj-ag can you tell me what fields do you need from contact and organization table?

**Comment by pankaj-ag** [comment]
The complete contact history table.

**Comment by pankaj-ag** [comment]
Also, add the  contact phone as one more column.

**Comment by pankaj-ag** [comment]
This is complete.
