### ISSUE TITLE
Message not delivered to Glific chat, but delivered to WhatsApp

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2218]
The message was not received on the Glific Chat screen. But received on WhatsApp.
Need to know the reason for this.
Ask Reapbenefit to publish the flow. After published it worked. But not sure, if that was the reason of the failure.
Contact who has an issue. - https://reapbenefit.tides.coloredcow.com/chat/151854

1. Start a flow Covid_and_waste_management
2. Select Yes.
3. Next message is not shown in Glific Screen.

<img width="1018" alt="Screenshot 2022-04-21 at 1 02 53 PM" src="https://user-images.githubusercontent.com/16541548/164402982-064a5592-f311-4d43-9fa0-af767f9a8f8f.png">

<img width="1293" alt="Screenshot 2022-04-21 at 1 02 25 PM" src="https://user-images.githubusercontent.com/16541548/164403007-135af64a-a70a-483f-ada8-a56156294826.png">

**Comment by pankaj-ag** [comment]
It looks like a message number issue. I am still investigating why those numbers are duplicate.

**Comment by pankaj-ag** [comment]
Mohit I can see that messages are there now.
