### ISSUE TITLE
Let's make contact history a bit cleaner

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2227]
**Is your feature request related to a problem? Please describe.**
Contact history with the statement `All contact flows are ended` doesn't make much sense to the user.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/32592458/165646821-ed5efdcc-cb9e-4360-99ff-3611f1258366.png">

**Describe the solution you'd like**
Reframe the sentence to something simple for user to understand and check and if it's coming for the right actions and should not come multiple times since as a user this is very confusing.

**Comment by mdshamoon** [comment]
If the previous flows are getting killed by starting a new flow then the sentence could be: `All the previous active flows have been ended`

If the all the flows are ended for the contact then the sentence could be: `All active flows are completed`

**Comment by 0x0elliot** [comment]
hey, i would like to pick this issue up. i am a new contributor to glific and using elixir itself and any nudging in the right direction would help :)
