### ISSUE TITLE
Can we get reason for failures in broadcast stats api

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2229]
**Is your feature request related to a problem? Please describe.**
As a user knowing the reasons for failure is pretty important as I can take my decisions based on what the errors are
<img width="399" alt="image" src="https://user-images.githubusercontent.com/32592458/165683350-1318259e-ea34-4169-8d44-ebc01fe33160.png">

**Describe the solution you'd like**
Add the error reasons so that the user will get an understanding of why their messages are not getting reached

**Comment by pankaj-ag** [comment]
@mdshamoon can we add these tasks in a parent issue and when we will start working we can create one, Currently, it looks cluttered. 
https://github.com/glific/glific/issues/2208

**Comment by mdshamoon** [comment]
@pankaj-ag I have added all the details in a common issue https://github.com/glific/glific/issues/2246. Let me know if this works
