### ISSUE TITLE
Implement Access Control using Roles for different entities

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2234]
[Detailed document on this feature]( https://docs.google.com/document/d/1ULJhDPfC2bztpDdjBulutMpb-1X2txtBT2lEmKyqAcw/edit#heading=h.ceopwlrwnf8h)

We need to permission various objects in the Glific DB to a set of dynamic roles, to do this we need to

1. [x] Extend the roles tables from a static list of Staff, Manager, Admin, Super-Admin to a dynamic list. We'll retain the current set of roles as reserved roles
2. [x] A user can have one or more roles assigned to it. The default is Staff
3. An entity being permissioned has one or more roles that can access the object. The default is Staff
4. The following entities will have permissions attached to them

* [ ] Flows
* [ ] Collections
* [ ] Triggers
* [ ] HSM Templates
* [ ] Interactive Messages
* [ ] Saved Searches

5. The scheme we use should be flexible, so we can attach permissioning to other entities easily
6. This should not affect our current simple permissioning scheme, since this is what most NGOs will use

**Comment by pankaj-ag** [comment]
@dlobo this looks good to me.

**Comment by mdshamoon** [comment]
@dlobo looks good to me as well.

**Comment by pankaj-ag** [comment]
Closing this one as the first cut of this functionality is out. We will create new issues with requirements.
