### ISSUE TITLE
Dashboard - Report template a to extract survey results in a more intuitive way

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific#2242]
For instance, consider a survey on plastic waste with  2 questions 
1 Do you segregate plastic ?
2 How frequently it is collected ?

Today what we can readily provide is in Table B of the following sheet 
https://docs.google.com/spreadsheets/d/12Vm1AjQB_ir05KgQ2227uelH_gWedP8i7kwNfM-47uo/edit#gid=820650189

However what will be useful is in table C of the same sheet. 

Basically A slightly more involved  query that takes an additional jump from the wiat for response node back up to the send message node can get us there.

**Comment by pankaj-ag** [comment]
We will target this in #4343
