### ISSUE TITLE
Civis Dashboard 

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific#2243]
Can the incomplete / expired flows report show Node as not just the hexadecimal code. But also show the result variable in brackets against it. e.g. Nf2e(Approve_Law) Where "Approve_Law" is the result variable in which that response would be stored.

Link to dashboard.
https://datastudio.google.com/reporting/78e84bae-5a9a-4b1f-af8a-a67df0c78273/page/p_28n32s43tc?pli=1

**Comment by mdshamoon** [comment]
@Ranjana-G added this in Civis as well as template report. Thanks for the suggestion
