### ISSUE TITLE
Getting error while importing contacts

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2251]
![Image](https://user-images.githubusercontent.com/16541548/169068293-7b004607-d0c2-47fa-8602-23a9defca7db.png)

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 This issue seems when the list of contacts is significantly large. I think we need to restructure code to create a queue to upload contacts in a set of 100 contacts perhaps.

**Comment by AkhileshNegi** [comment]
This is fixed and deployed
