### ISSUE TITLE
Create an API to indicate all messages from a contact are read

### ISSUE THREAD

**Issue by dlobo** [glific/glific#226]
**Is your feature request related to a problem? Please describe.**
We tag all incoming messages to a Contact as Unread by default. This is expected behavior. Thus a contact could have multiple Unread messages.

In this case Unread means unread by the NGO

**Describe the solution you'd like**
The frontend shows all conversations per contact. Thus when we visit a contact screen, all messages for that contact should be un-tagged as Read (since it has been read by someone at the NGO)

And the last incoming message should be tagged as "Not replied"

Also, when we send a message to a contact, we should ensure that all previous "Not replied" tags are removed from those messages

**Comment by pankaj-ag** [comment]
@kurund I am closing this one as complete. 
Feel free to reopen in case you found any issue with this feature.

**Comment by pankaj-ag** [comment]
```graphql
mutation markContactMessagesAsRead($contactId : Gid!) {
  markContactMessagesAsRead(contactId: $contactId)
}

{
  "contactId": "26"
}
```

> The above query returns effected messages ids:

```json
{
  "data": {
    "markContactMessagesAsRead": [
      "2", "10"
    ]
  }
}
```
