### ISSUE TITLE
The cards showing up on Org settings page should be data driven 

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific#2265]
Only features that the are enabled for a tenant should appear on their configuration page. For instance DG should see exotel card since it is enabled for them. However VOPA should not.

**Comment by Ranjana-G** [comment]
Implementation - This can be done if information on features enabled is available in a database and provided to the front end via API so that the settings page is populated only with necessary cards.

**Comment by pankaj-ag** [comment]
@Ranjana-G the Exotel card is available for everyone and any organization can use it. 

The only thing is that it's a limited use case you can only take OPT_INs via IVR and trigger a flow. 

Currently, DG and RB are using this. 

But I agree it will be good for the future to make that card list configurable as per the organization.
