### ISSUE TITLE
Handle Success as text in wait for response rather than killing a flow

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2270]
**Describe the bug**
If we send Success  as text in a wait for response node it kills the flow

**To Reproduce**
1. Create a new flow as shown in screenshot
2. Send success in input
3. It does not move forward

**Expected behavior**
It should move forward

**Screenshots**
<img width="1194" alt="Screenshot 2022-06-01 at 4 43 25 PM" src="https://user-images.githubusercontent.com/32592458/171393322-e4d0edd1-78ed-43f3-aa28-02df19c123c4.png">

**Comment by pankaj-ag** [comment]
This happens twice with AW (for 2% of the contacts in 5 months) but we are not able to replicate it properly. 

Let's keep this issue open for some more time and see if it happens for other org as well.

**Comment by pankaj-ag** [comment]
@mdshamoon keep an eye and update this issue if this happens again.

**Comment by pankaj-ag** [comment]
Adding some thoughts to fix this.  Append "Glific" as a convention to all the reserved messages. 
1. "GLIFIC_NO_RESPONSE", "GLIFIC_EXIT_LOOP", "GLIFIC_SUCCESS", "GLIFIC_FAILURE"

And while checking in the category we can convert that again to 
["No Response", "Exit Loop", "Success", "Failure"]
