### ISSUE TITLE
LIVE location is not treated as invalid response for location input

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2302]
LIVE location doesn't work when sent from WhatsApp to Glific.
In case the location is asked from the contact in wait for response and the contact sends LIVE location in place of current location, then it should be treated as an invalid response.

Currently, nothing happens if Live location is sent and contacts are confused if the flow is stuck.

https://cc.tides.coloredcow.com/flow/configure/e9af36e4-0f96-45bf-9c8e-c29da5ae7880

![Image](https://user-images.githubusercontent.com/16541548/174241904-214b7c4f-a651-4d46-b397-4907c73a381e.png)

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you put the status here? I mean whatever we found in our research.

**Comment by pankaj-ag** [comment]
We need to either ignore that or process through the system. Flow should not get killed because of this.

**Comment by AkhileshNegi** [comment]
@pankaj-ag I reached out to Gupshup and they shared that live location is not supported on WhatsApp Business API.
Here's screenshot of our conversation
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/40158831/186329039-08e8e61f-35d6-4db8-bcf4-b336e994091c.png">

**Comment by AkhileshNegi** [comment]
Also flow is not killed on sharing live location and behaves as if no message is exchanged

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/40158831/186334053-ba35c5e8-e852-4a49-ad4c-a9388ed0f9ad.png">

Here first **live location** is shared and then **current location**

<img width="982" alt="image" src="https://user-images.githubusercontent.com/40158831/186334308-cc8f1e7c-c26e-433d-b964-1b6174da5620.png">

**Comment by AkhileshNegi** [comment]
Here first **live location** is shared and then **current location**
<img width="978" alt="image" src="https://user-images.githubusercontent.com/40158831/186335258-3f4ecebc-5da7-42fc-882f-8eb1b93185b5.png">

**Comment by AkhileshNegi** [comment]
Here first **live location** is shared and then **current location**
<img width="978" alt="Screenshot 2022-08-24 at 10 52 45 AM" src="https://user-images.githubusercontent.com/40158831/186335707-f4fe41c5-aaf5-4582-9160-1bed95f8cd10.png">
