### ISSUE TITLE
Video attachments is throwing error while sending as an attachment.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2307]
The below file is throwing an error as an attachment and Dost team is unable to send it to WhatsApp from Glific
https://storage.googleapis.com/cc-tides/Flow3-Block4.mp4

https://cc.tides.coloredcow.com/flow/configure/be42f5a6-7214-4bac-871b-9cd481c5c90a

![Image](https://user-images.githubusercontent.com/16541548/175511311-36f51457-03b0-4d50-a57b-f71931fa38ea.png)

**Comment by pankaj-ag** [comment]
@mohitsharma-22 can you please share an update here?

I think we checked and the video was not valid but I want to confirm with you first.

**Comment by mohitsharma-22** [comment]
Yes @pankaj-ag The video was missing header information.

@mdshamoon Please confirm if we can close this task. Or do you want to keep it open for adding some validation for this?

**Comment by pankaj-ag** [comment]
Closing this one for now. Please reopen in case you found any updates on this.
