### ISSUE TITLE
Folder structure for Flows, Interactive Messages and HSM

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2333]
### Description
Despite having keywords, and naming conventions it becomes difficult to search flows when the number of flows are significant. Similar challenges arise for Interactive Messages and HSM.
Currently collections can only be done manually or via the flow. If we were able to create a collection based on a contact field or combination of contact fields. For example, when I create a collection it asks me to list down the AND and OR conditions basis which the collection will be created. 

Both these would make things definitely easier on the creator side of things. Looking forward to hearing your thoughts as well as how other NGO's are possibly addressing these needs in their chatbots

### Goals
Creating some mechanism to ease searching in various section of Glific like
1. Folder structure for each of these sections. 
2. All child flows belonging to a parent flow could be put in folder
3. All HSM related to one topic could be put
4. All Interactive messages used in the flow could be put
5. [Issue](https://github.com/glific/glific-frontend/issues/2382): Currently it is also challenging to identify inactive flows.

### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Easy

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by AkhileshNegi** [comment]
We had a discussion on the same and we can get started with the [flow list page](https://cc.tides.coloredcow.com/flow)
We can add support to label the flows and then extend the search functionality to search flow names (already exist), shortcodes (already exist), and labels
Additionally, we can also add a dropdown to select all the flow labels shown in the image below. This will allow selecting one or multiple flow labels.
<img width="258" alt="image" src="https://user-images.githubusercontent.com/40158831/232384091-a37e2f4c-e6e1-4299-ab4f-a70af36f33f0.png">
Also we need to have a separate toggle for active and inactive flows similar to what we have for [notification screen](https://cc.tides.coloredcow.com/notifications)
<img width="840" alt="image" src="https://user-images.githubusercontent.com/40158831/232384504-53fda1fb-33af-449a-b4f0-b2914948a0d1.png">

**Comment by KDwevedi** [comment]
comment

**Comment by AkhileshNegi** [comment]
This is completed, we have added support for tags in Flows, templates and interactive templates screen
