### ISSUE TITLE
Restrict user to delete the organization number from contact profile

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2334]
## Task

Restrict user to delete the organization number from contact profile screen. 
The API used is deleteContact.

## Details
Happened with one of our clients recently where they deleted the main organization contact and Glific stopped functioning.

**Comment by AkhileshNegi** [comment]
@mdshamoon can you share the error message that should be prompted when trying to delete organization contact

**Comment by mdshamoon** [comment]
@AkhileshNegi the error message could be: 

"An error occured while deleting the contact. The contact is associated with WhatsApp Business API to send messages and cannot be removed".

**Comment by abhi1203** [comment]
`Sorry, this is your chatbot number and hence cannot be deleted` 

what about this simple short message? is it missing something?

**Comment by AkhileshNegi** [comment]
Look Great! Thanks @abhi1203

**Comment by pankaj-ag** [comment]
Closing this as complete.
