### ISSUE TITLE
Dockerizing glific - frontend and backend

### ISSUE THREAD

**Issue by 0x0elliot** [glific/glific#2348]
**Is your feature request related to a problem? Please describe.**
It would be simpler to help containerize all the services that run on the backend and frontend, then link them together using a nice docker-compose.yml file so that the required architecture could be easily understood by new contributors trying to contribute. It would make the project more contributor friendly.

**Describe the solution you'd like**
Dockerising the Postgres, main elixir backend, and any other services which are possible to fit in here.

I also noticed mentions of Oban Pro. I hope not purchasing the library keys doesn't make the development process tougher.

**Comment by David-Lazaro-Fernandez** [comment]
Hey there, I'm interested in this issue but I have some questions 🙌 

1. Do we need to Dockerize any possible service?
2. Would it be good if we create 2 Dockerfiles for each part of the project?
    - `front_end.dockerfile`
    - `back_end-dockerfile` 
    
 Tysm! 💌

**Comment by pankaj-ag** [comment]
@David-Lazaro-Fernandez I think starting with two different docker files makes sense.

**Comment by dlobo** [comment]
@David-Lazaro-Fernandez if you jump on our discord channel (link on the README.md file of glific, we can help you out as needed

**Comment by siddhant3030** [comment]
@David-Lazaro-Fernandez Hey. Just wanted to know if you're still working on this issue.

**Comment by mrbrianevans** [comment]
I'm happy to work on this issue if its not being done by anyone else

**Comment by siddhant3030** [comment]
@mrbrianevans Since it's still not being done yet. Please go ahead and implement it. Let me know if you need any help.

**Comment by mrbrianevans** [comment]
Okay will do. I hope I don't need Oban Pro to get it working in docker.
