### ISSUE TITLE
Add conversation info to the messages table (this is part of the gupshup payload that we should see)

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2349]
We received the conversation details also with the message payload. We need to start capturing that.

**Comment by AkhileshNegi** [comment]
@pankaj-ag can you share artifacts regarding same in the issue. What are conversation details we receive in payload and is there a document for same?

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you check gupshup docs for that.

**Comment by pankaj-ag** [comment]
https://support.gupshup.io/hc/en-us/articles/4414108160409-The-inbound-payload-change-for-conversation-based-pricing
