### ISSUE TITLE
Organization query is unauthorized for staff users

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2361]
**Task**

We are using organization query for getting the bsp provider in the frontend. For a staff member this query is unathorized. Can we authorize it for the staff member as well since we need that data for staff member.

<img width="924" alt="Screenshot 2022-08-05 at 11 09 04 AM" src="https://user-images.githubusercontent.com/32592458/183009822-89b12745-46d5-4c9f-80ea-65dcc96d672c.png">

**Comment by pankaj-ag** [comment]
@mdshamoon this is complete and merged. We will deploy it today.
