### ISSUE TITLE
Flow Revision Error: Unable to open flow

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2370]
**Describe the bug**
There seemed to be some issue when a flow revision was saved resulting in the Flow screen going blank without any nodes.

**Screenshots of the Flow screen**

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/40158831/183587592-0b667d38-6881-440d-b996-5c3f1320a28b.png">

**Frontend observation**

<img width="842" alt="image" src="https://user-images.githubusercontent.com/40158831/183589171-e2f0bece-eb9e-4a82-b68e-3d759f169081.png">

**Details**

**Organization name:** Danavidya
**Flow name:** danaVidya (id: 4442)
**Date issue was faced:** 9th August, 4:46 AM
**Error Json:** [GCS URL](https://storage.googleapis.com/cc-tides/DVerror.json)

**Comment by AkhileshNegi** [comment]
Same issue
**Organization name:** Bhumi
**Flow name:** Nakshatra 2022 (id: 4726)
**Date issue was faced:** 31st August, 11:00 AM
**Error Json:** [GCS URL](https://storage.googleapis.com/cc-tides/corrupted_flow_bhummi.json)

**Comment by AkhileshNegi** [comment]
@mdshamoon  assigning this issue to you so you can check by setting up flow editor that in which node the flow is corrupted

**Comment by mdshamoon** [comment]
I checked for Danavidya and issue was in the node: `Enter a flow`.

The `Enter a flow` node has an exit destination for an `Interactive message node`, but the interactive message node was not present in the flow.

The Bhumi flow shared here seems to work fine. Let me check other revisions of the same flow
