### ISSUE TITLE
Bigquery throws error not enough permissions even if the role is set to owner

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2379]
## Bug

Bigquery throws error not enough permissions even if the service account role is set to owner
This recently happened with Bhumi and Danavidya.

**Comment by vannavp** [comment]
Hello team,

Any update on this?

**Comment by vannavp** [comment]
@mdshamoon  please update?

**Comment by pankaj-ag** [comment]
@mdshamoon can you verify and if that is fixed please close the issue.
