### ISSUE TITLE
Add a default role for NGO admin and ngo person who left in the seeders

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2380]
## Task

Add a default role for NGO Admin and NGO person who left in the seeders.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/32592458/184826224-3986f5a0-7933-460b-9ffb-602dbf815e36.png">

**Comment by pankaj-ag** [comment]
We will check this when we have time. @mdshamoon is this creating any problem ?

**Comment by mdshamoon** [comment]
@pankaj-ag cypress test cases are failing because of this. If possible can we pick it up this week.
