### ISSUE TITLE
Add seed data for info notification

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2397]
## Task

Based on the discussion in this [issue](https://github.com/glific/glific-frontend/issues/2119) we are proposing a new category in notifications called as Information that will provide info on various event updates in Glific like when a template is approved or rejected.

We already have some seed data for the other two categories in notification namely: Warning and Critical so it is easier to see and check that data while testing locally but for information category no default data is present.

Can we add some seed data for the information notification so we can test it easily in the development and cypress test cases.

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/32592458/186391814-cfccac15-070e-4807-80ae-1e22a62f9073.png">

**Comment by pankaj-ag** [comment]
@mdshamoon this is fixed and we will deploy it today.
