### ISSUE TITLE
HSM template gets rejected. Not sure the reason of it.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2412]
HSM is getting rejected and getting invalid format error. Not able to figure out what error is the reason for the invalid format.
https://ndrcsupport.tides.coloredcow.com/template/7149/edit 
https://ndrcsupport.tides.coloredcow.com/template/7149/edit

HSM content
Dear Parent or Caregiver {{1}},

We're happy to announce the upcoming in-person parent training program in Telugu from 26th to 28th August from 3 pm to 5 pm at Oyster Clinic, Begumpet, Telengana.

We are going to talk about Autism spectrum as a condition and how you can parent your child beyond the label.

This program is open to all parents of newly diagnosed children (2-5 years) with Autism.

For Registration Type ndevent.
Register Now. 

Team Nayi Disha

**For DG**

In the case of the DG, we are submitting the media templates from the Glific. Got this error, even though we are attaching the media. The same template we approved from the Gupshup dashboard and it got approved.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/30264862/185878742-a76cc1dc-03e3-4d97-8983-197388ed83db.png">

**Comment by pankaj-ag** [comment]
@mohitsharma-22 this is fixed. Please check this and let me know. I have submitted the same template and it was working fine.

**Comment by mohitsharma-22** [comment]
@pankaj-ag Thanks for informing me. I have submitted the template for a test. I will update once we will get it approved. https://cc.tides.coloredcow.com/template/8404/edit

**Comment by mohitsharma-22** [comment]
@mdshamoon Template name is = **test_image**

**Comment by pankaj-ag** [comment]
@mohitsharma-22 can you test this feature and let us know if we can close this ?

**Comment by mohitsharma-22** [comment]
@pankaj-ag You can close this one. The issue is resolved.
