### ISSUE TITLE
We don't see an image preview when template is created and synced from gupshup

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2421]
When we create an image template on gupshup and sync it in Glific it doesnt show the image preview that we have added while applying the template. 

After looking into the issue I found that we don't get that data from the template list API
<img width="471" alt="image" src="https://user-images.githubusercontent.com/32592458/188392243-282fb870-b002-43e9-b5a6-cfa15d471566.png">

**Action to be taken:**

Check with gupshup if we can get the image data as well.

**Comment by pankaj-ag** [comment]
@mdshamoon any update on this one? If not can you follow up ?

**Comment by mdshamoon** [comment]
@pankaj-ag This is the last thing I heard from Gupshup team on this. Let me followup 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/32592458/191904546-8b874ffd-281c-4776-a9f8-5760f944fc82.png">
