### ISSUE TITLE
Missing Link: A flow gets stuck in a specific key word "Cyber Safety"

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2429]
**Describe the bug**
A flow gets stuck in a specific keyword "cyber Safety"

**To Reproduce**
1. Go to flow https://missing.tides.coloredcow.com/flow/configure/1b8a6863-b5cb-4cb5-864d-dd83dd071ed8
2. Click on Preview and test
3.  Once the interactive message comes, select the "Cyber Safety" option. 

If I change the word to "Cyber Safety 2" the flow works as expected.

**With Keyword**
<img width="1202" alt="Screenshot 2022-09-08 at 1 36 47 PM" src="https://user-images.githubusercontent.com/29367838/189110812-a289cf9a-dd9b-4e7b-a6af-c2fd224e0da6.png">

**With other Keyword**
<img width="1210" alt="Screenshot 2022-09-08 at 1 37 27 PM" src="https://user-images.githubusercontent.com/29367838/189110718-2d0a9e06-818b-4fcb-8988-d087c84ddf67.png">

**Comment by pankaj-ag** [comment]
@wevekamola this is fixed.
