### ISSUE TITLE
Add profiles to collections

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2460]
We need to figure out a way to add contact profiles to a collection. 

**Use case:** 
Let's say the user has two profiles. And both the profiles set different activity types as their preferences. So now one contact will be in two different groups (like dance and Art) with different profiles. 
And when we send the message to the collection it will go based on that selected collection profile. 

Things we are still not clear about yet:

We can not have two flow contexts for one contact. So if there is a trigger that runs different flows for different collections (which is a very common thing) then only the latest flow will sustain and all the previous flows will be killed automatically.

**Comment by mdshamoon** [comment]
@pankaj-ag Seems like a complicated thing for this use case. 

I was thinking more in terms of going towards creating dynamic collections based on contact fields/profile fields. This can solve a lot of use cases apart from these.

If I want to group people based on certain fields I can choose the contact field value and create a collection and then start a flow or send messages based on that. (not sure how complicated this would be as we need to extract data from json)

**Comment by mdshamoon** [comment]
The complexity I can think would be in these cases
1. Handling collections differently: Contact level vs profile level
2. Sending message/start a flow for a contact level collection or profile level (for cases where there is a mix of both)
3. If I send message/start flow for a profile level collection. Should we switch profiles if the user is currently on a different profile.

**Comment by pankaj-ag** [comment]
@mdshamoon the main case is how we can start a flow for two different collections with different profiles. The latest trigger will kill the previous flow.

**Comment by pankaj-ag** [comment]
Grouping people in a collection via fields can be happen via another flow also.
