### ISSUE TITLE
Add all fun_with_flag toggles like role management, flowuuid display, contact profile in seeders by default

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2495]
## Issue

Whenever I want to test some feature that is toggled by fun_with_flags library, I always search or ask for the flag_name to be toggled.
It can be accessed from [here](http://api.cc.tides.coloredcow.com/feature-flags/flags)
Lets add all the toggles by default in the seeder so that there is no need to search it again and again while development and testing
<img width="893" alt="image" src="https://user-images.githubusercontent.com/32592458/193641912-5c056c5a-9080-44ee-9a5f-ba201a328cf6.png">

**Comment by mdshamoon** [comment]
This is needed for the local development work to be faster. Reopening

**Comment by dlobo** [comment]
can you elaborate?

You know that fun with flags also has an admin dashboard that we can use quite easily

**Comment by mdshamoon** [comment]
Thanks @dlobo. I checked the UI but it also shows me these three entries only. Let me know if I 
<img width="1415" alt="Screenshot 2023-04-04 at 12 53 02 PM" src="https://user-images.githubusercontent.com/32592458/229718292-eb89fedb-3fd1-4858-9400-ceb26fc50407.png">

Can we add all of the flags by default and have them set the value as false.

1. roles_and_permissions
2. flow_uuid_display
3. enable_profile

If any apart from this.

This is needed for development and enabling these for testing in cypress for these features.
