### ISSUE TITLE
Add a variable support @ calendar in floweditor

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2537]
## Task

Add a variable support @date in floweditor that will be evaluated to the current date in the format:  **MM/DD/YYYY**
It should show up in autocomplete when we type @ anywhere in the floweditor 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/32592458/196340161-722b7d21-6ec2-4af8-9d30-47df51cfa4b1.png">

**Comment by pankaj-ag** [comment]
@mdshamoon I think we can have something like. 

@date.current_date
@date.yesterday
@date.tomorrow
@date.day
@date.month
@date.year

And some wildcard conventions like. 

@date.past_NUMBER_UNIT like @date.past_2_days, @date.past_2_hours and things like that.
