### ISSUE TITLE
Issue with collection search

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2547]
I can see a user is in a particular collection.
<img width="1319" alt="Screenshot 2022-10-25 at 12 19 27 PM" src="https://user-images.githubusercontent.com/29367838/197702932-3532a931-dc81-44ca-bed0-d07d38a00b7e.png">

**I can also see that the user in that collection**

But when I search the number it shows no user found.
<img width="1437" alt="Screenshot 2022-10-25 at 12 20 07 PM" src="https://user-images.githubusercontent.com/29367838/197702956-f7afa572-800e-48b7-b6b4-1f5e295b114d.png">

Ideally, it should show the user after putting the number in the search.

**Comment by pankaj-ag** [comment]
This is fixed in https://github.com/glific/glific-frontend/issues/2376. 

We were not searching the contacts based on phone.
