### ISSUE TITLE
Consider adding display_name for the contact

### ISSUE THREAD

**Issue by kurund** [glific/glific#255]
**Is your feature request related to a problem? Please describe.**
* Currently we show name or phone number if the name is missing in the frontend.

**Describe the solution you'd like**
* Maybe introduce a display name option, which could be configurable in the future.
* We can display something like "Jane Doe (919999999999)" or  "Jane Doe - 919999999999"  or " 919999999999: Jane Doe" etc.

**Comment by dlobo** [comment]
We get the name from whatsapp, when Whatsapp sends a message. So whenever the user changes their name, it gets changed also.

I'd vote to not keep this configurable at this time
