### ISSUE TITLE
Automate invoices sent to NGOs from Stripe

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2555]
**Is your feature request related to a problem? Please describe.**
As the number of NGOs is increasing and most NGOs want to go for manual invoices, because of TDS deduction and non- Creditcard availability

**Describe the solution you'd like**
There is a fixed amount of invoices Monthly/Quarterly. Needs help to send the invoice automatically via email from Stripe.

**Comment by AkhileshNegi** [comment]
This is completed
