### ISSUE TITLE
Credit Card addition is giving error

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2556]
Issue reported by Nyaaya.
Getting error while adding credit card in Glific.
Please fix

![Image](https://user-images.githubusercontent.com/16541548/199012795-337a8b78-bca3-44b0-a598-1f29fc7aa8dd.png)

**Comment by pankaj-ag** [comment]
@mdshamoon if you understand this can you fix on the backend? Otherwise I have to read the API and make the changes.

**Comment by AkhileshNegi** [comment]
This is fixed [here](https://github.com/glific/glific/pull/2572)
