### ISSUE TITLE
DG JH Reporting Tasks

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2579]
- [x] Remove these testing numbers from all the reports.
         918979120220, 
         918809989954, 
         919411144006, 
         918979278734

- [x] Need to update the **Feedback check** and **Crop Closing check** in **Flows** report tab
        Now instead of 3 bar graphs for each crop, we need only one bar graph and fetch the details of these contact fields.
        1. Bot_overall_closing
        2. Bot_overall_feedback

- [x] Need to add crop distribution graph with filters

- [x] Graph for showing the user distribution of reasons for saying NO to the adoption (Wheat, Rice and Mustard)

**Comment by wevekamola** [comment]
- [ ] Remove these testing numbers from all the reports.
         918979120220, 
         918809989954, 
         919411144006, 
         918979278734

- [ ] Need to update the **Feedback check** and **Crop Closing check** in **Flows** report tab
        Now instead of 3 bar graphs for each crop, we need only one bar graph and fetch the details of these contact fields.
        1. Bot_overall_closing
        2. Bot_overall_feedback

- [ ] Need to add crop distribution graph with filters

**Comment by AkhileshNegi** [comment]
@wevekamola This is completed. Can you check and close same?

**Comment by wevekamola** [comment]
@AkhileshNegi seems good to me. I will keep observing the data, and if find any issues will re-open the task.

Thanks for the support.

**Comment by wevekamola** [comment]
- [ ] The adoption response is not showing any result for Potato and Mustard.

<img width="453" alt="Screenshot 2022-12-19 at 9 07 49 AM" src="https://user-images.githubusercontent.com/29367838/208343004-55147ae5-cfed-4ecb-bda2-8b1f6ac2564c.png">


<img width="405" alt="Screenshot 2022-12-19 at 9 07 40 AM" src="https://user-images.githubusercontent.com/29367838/208343031-aa286efd-58da-44ca-b823-455ba5ea5fc2.png">


- [ ] Can we show crop age as well in these 3 datasets
<img width="414" alt="Screenshot 2022-12-19 at 9 10 55 AM" src="https://user-images.githubusercontent.com/29367838/208343129-277e5158-29e5-4462-b57d-bc48ecaee2c4.png">
