### ISSUE TITLE
Integrate A/B testing support for Glific

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2587]
1. Introduce a new node type in FlowEditor called Split Randomly
2. By default, split randomly does a 1:1 split into 2 options 'A' and 'B'
3. If we can allow the option of allowing the user the specify the number of groups to use (2 or more), that would be good. This can be in phase 2
4. Based on number of 'options' the result is 'A', 'B', 'C' etc ...

Things to consider (for phase 2, maybe?)

1. How will this effect reporting, can we add reporting support
2. Can we use labels to indicate 'success' or 'failure' for each branch. This will allow the NGO to decide which option was the 'winner'
3. We need to track which contacts went down which 'branch'

Some relevant links from our discord thread
1. https://help.textit.com/en/article/ab-testing-your-flows-1eyi254/
2. https://blog.textit.in/how-to-a-slash-b-test-your-flows
3. For more advanced usage, we can get some ideas from here: https://smsbump.com/knowledge-base/view/how-to-run-an-ab-test-in-smsbump

**Comment by roboton** [comment]
i'd suggest the following components:

1. flow that checks both for user inputs and user state to drive flows (finite state machine)
2. a place to create, retrieve, and update user state
3. an experiment platform to create experiments and assign users to certain states randomly (or with some other strategy)
4. a metrics/kpi definition platform that allows defining and collecting metrics across users/sessions over time

**Comment by roboton** [comment]
cc'ing @Tech and Data ***@***.***> for tracking and to include anyone
else's thoughts

**Comment by pankaj-ag** [comment]
@dlobo can you elaborate on point 3 a bit more? I think we can divide the samples into 10 different buckets. Let me know if I am missing something. 

<img width="699" alt="image" src="https://user-images.githubusercontent.com/10670690/204277458-59f7263e-892a-4184-a38d-14f91cb38e81.png">


<img width="828" alt="image" src="https://user-images.githubusercontent.com/10670690/204277520-c32e91d7-a827-442a-a6fd-5da22f2e1fdc.png">

**Comment by mdshamoon** [comment]
This is completed.
