### ISSUE TITLE
 DG Telangana Report tasks

### ISSUE THREAD

**Issue by wevekamola** [glific/glific#2592]
Report link https://datastudio.google.com/u/0/reporting/7058136f-5a31-41c0-a4f7-a295888cccd6/page/p_jkywa2ijuc
Account- https://digitalgreen.tides.coloredcow.com/

- [x] A tile showing the valid number we got from the IVR from this collection **Telangana Farmers via Exotel**
        <img width="600" alt="Screenshot 2022-11-29 at 4 30 22 PM" src="https://user-images.githubusercontent.com/29367838/204512348-689a8d72-49d5-4ea9-a3e4-73e1c4172c92.png">

- [x] Need to show a detailed report under user distribution based on this **Telangana Farmers via Exotel** collection but only for the farmers having valid contacts/optin. We can show **Name**, **Phone**, **Gender**, **Mandal**, **Age**, **Onboarded on**

- [x] Please add a filter all over the report for only valid optin contacts, currently the non-optin users are also getting added to the reports.

- [x] Right now we get details of non-optin users in total contacts if we can separate them in a separate report that will solve the overall issue.

<img width="1020" alt="Screenshot 2022-11-29 at 4 36 14 PM" src="https://user-images.githubusercontent.com/29367838/204513404-5aee04c8-733b-4fbb-9c67-a7eb08521a4a.png">

**Comment by pankaj-ag** [comment]
@AkhileshNegi @wevekamola can we close this ?
