### ISSUE TITLE
Feedback on Glific Bot

### ISSUE THREAD

**Issue by nairabhishek73** [glific/glific#2601]
1) Do we have to say welcome to tides? Can be confusing for someone who’s only heard glific.
“Hey there 👋, 
Welcome to Tides, a SaaS offering of a Two Way Communication platform for NGOs called Glific. Here's an introductory video of the Glific platform: https://www.youtube.com/watch?v=r6pI3YnINws&t=2s”

2)  After ‘5’ - let us know how we can help you, there should be an acknowledgement email that could say “Thank you for describing your requirement, our team will get in touch with you via email/phonecall in 3-5 business days”

3) Revise/update ‘key features’ images.
 3a)Second image says ‘Advanced seaches’
3b)I think we should remove what’s in the crosses.
3c)Also IVR is supported now right

4)After 2- there is a type of opt in where you describe your use case. What is the purpose of this message? Should it be mandatory?

5) Order of 1 to 5 could be changed so that the option to get started with Glific comes up after they see the features, use cases, etc.

6)“Would you like to use WhatsApp for your programs?
If yes, please describe your use case in 2-3 lines.
If not, please type NA or skip.”
- Can be improved-  type ‘NA’ or type ‘Skip’

7) After 1= get started with Glific, and selecting continue, no response.

**Comment by nairabhishek73** [comment]
@abhi1203

**Comment by wevekamola** [comment]
**Overall Feedback**
	Seems a bit less interactive, we should have emojis and videos instead of images. I have used a FB meta bit, I  think we can use the same approach

![IMG_0811](https://user-images.githubusercontent.com/29367838/209496953-193ae50c-33e6-4aa5-b647-e4635d7b068b.PNG)

![1](https://user-images.githubusercontent.com/29367838/209496863-55a168ca-980f-4907-b0b9-f2156f267c45.PNG)
![IMG_0809](https://user-images.githubusercontent.com/29367838/209496907-077dccec-8476-4939-b474-1a06708578a8.PNG)

![IMG_0810](https://user-images.githubusercontent.com/29367838/209496936-c470c0c6-18b7-4a50-8822-3855899418bc.PNG)

**Flow feedback.**


	**1. Get Started:** 
		a) The current inforamtion is suffient. But instead of a document if I can show the user the whole process through a quick video that will help them to think and plan accordingly.
		b) In Get Help, can we show the number to show it will initiate a call? Right, it's a bit unclear.
		c) Let's add Go Back also, in case they want to get more information. Right now If I don't want to use my mobile to get started there is a dead end to go back.

	**2. See chatbot use cases**
	  a) Image works, but we can modify it a bit, the content looks small and the other image looks big, I had to zoom in to read it properly.
	  b) Not sure if we have some videos of the use cases, that we can use here.

**Comment by mdshamoon** [comment]
@nairabhishek73 is this completed?

**Comment by nairabhishek73** [comment]
Yes you can mark as completed
