### ISSUE TITLE
You cannot send the message to the contact

### ISSUE THREAD

**Issue by kurund** [glific/glific#264]
**Describe the bug**
* We receive the below error from the backend. However, the message is stored in the DB

**To Reproduce**
1. Go to chat and send message to any of the seed contact whom message was not sent initially

**Expected behavior**
* Message should not be stored in the DB
* Error should be returned as a part of response.

**Screenshot**
![Screenshot 2020-07-19 at 8 13 57 PM](https://user-images.githubusercontent.com/151481/87877604-e6d6cd80-c9fc-11ea-976d-f6d2ffedb38a.jpg)

**Comment by dlobo** [comment]
We should ensure that the contact is valid before creating a message and getting ready to send it. If contact is invalid and/or message is incomplete, we should return an error from the API
