### ISSUE TITLE
Make some contact variables editable from glific interface

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#2641]
**Is your feature request related to a problem? Please describe.**
Sometimes when a user has entered an incorrect information, NGOs would like to make the correct right there from the interface itself.

**Describe the solution you'd like**
From the contact profile section, the fields should be editable.

**Comment by pankaj-ag** [comment]
@mdshamoon let's think about this also.

**Comment by pankaj-ag** [comment]
@mdshamoon we can do that via excel sheet. 
https://glific.github.io/docs/docs/How%20do%20I.../Update%20collection%20with%20bulk%20contacts%20or%20contact%20fields/

<img width="827" alt="image" src="https://user-images.githubusercontent.com/10670690/229363166-76a5ce71-2b61-4c97-9356-d33652c5e4b9.png">
