### ISSUE TITLE
Show the list of contact which are not added in the collection

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2666]
### Description 
When using the bulk feature to add contacts in collections, sometimes some contacts fail to add to the collection.

### Goals
Get the list of contacts' names, phone in xls. so that one can verify which all contacts are not added to the collections

### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Easy

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by dlobo** [comment]
I'm fixing the code to ensure we include all errors (previously we were not). will be displayed on screen for now. not great, but livable for now, since this is not a commonly used path

**Comment by dlobo** [comment]
@mohitsharma-22 @pankaj-ag can u'll give me a few examples of csv files (small) that will throw errors please

**Comment by mohitsharma-22** [comment]
@dlobo This is the file I used last which throw error. I am not sure, which all records have errror.

[career_buddy_import_LAHI_24Mar23.csv](https://github.com/glific/glific/files/11257903/career_buddy_import_LAHI_24Mar23.csv)

**Comment by KDwevedi** [comment]
comment
