### ISSUE TITLE
Customize to add the emails and balance dollars in Gupshup wallet

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2669]
The request is to customized the emails for the alerts sent to NGOs for low Gupshup wallet balance
Also, customized the low balance amount  to 10, 20 or 30 $
Request came from Reap Benefit.

**Comment by dlobo** [comment]
Did not make it configurable. We cannot afford to overload the interface with too many config variables. 

But increased the amounts and sending warning at $10 every 2 days, and below $3 every day
