### ISSUE TITLE
Add more default flows for new organizations and local development

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2676]
**Is your feature request related to a problem? Please describe.**
We already have some default flows for the features that we have in Glific. We should include the below areas as well so that it helps for new organizations and a developer to easily look through them instead of creating one from scratch:

- Contact profiles
- A/B testing

**Comment by AkhileshNegi** [comment]
@mdshamoon can you add links to flows that you'll need

**Comment by mdshamoon** [comment]
@AkhileshNegi I have asked KP and @nairabhishek73 to create and share the links for this since they can have better insights on what a new NGO user may need for the default flows for these features. They will share it next week and I will update it here.

**Comment by mdshamoon** [comment]
Flow json for multiple profile: 
[Multiple profiles.json.zip](https://github.com/glific/glific/files/10859587/Multiple.profiles.json.zip)
