### ISSUE TITLE
Not receiving any tags with a new message in subscription

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#268]
**Describe the bug**
Tags is always an empty array with the `receivedMessage` subscription.

**To Reproduce**
1. Run the `receivedMessage` subscription in Graphiql explorer. use the API request listed below.
2. Send a new message from WhatsApp
3. Analyze the API response

**API request**
```graphql
subscription {
  receivedMessage {
    id
    body
    tags {
      id
      label
    }
  }
}
```

**Expected behavior**
The tags should be an array of the tags assigned to the new message. It should have unread tag at least.

**Screenshots**
![image](https://user-images.githubusercontent.com/12053186/87953064-333b0f80-cac8-11ea-9a41-de8e83807338.png)

**Comment by dlobo** [comment]
Ok, I think we'll tag the message as un-read and not-responded the minute it arrives, before we send the subscription.

the other tags will come a few time units later as we send them thru the automation engine

**Comment by pankaj-ag** [comment]
@rathorevaibhav this is fixed. 
Have a look and let me know if anything else is required. 
![image](https://user-images.githubusercontent.com/10670690/88504064-213dfd00-cff1-11ea-9e81-65f1531682cc.png)

**Comment by pankaj-ag** [comment]
@rathorevaibhav closing this issue. Feel free to open a new one in case you see an issue with this.
