### ISSUE TITLE
User has two contact fields with the same name

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2725]
**Describe the bug**
User has two contact fields with the same name **num**

**To Reproduce**
1. Go to https://antarang.tides.coloredcow.com/contact-profile/454043
2. See the contact fields
3. It has duplicate field Num

**Expected behavior**
We should not allow duplicate contact fields

**Screenshots**
<img width="390" alt="image" src="https://user-images.githubusercontent.com/32592458/228761692-ad2823fd-580a-412f-a6d7-61d4abd691f5.png">

**Comment by pankaj-ag** [comment]
Looks like one name has some leading spaces. Adding a fix for now.
