### ISSUE TITLE
Bigquery: Multiple entries for the same contact in the contact table

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2726]
## Task

Contact has multiple entries  in bigquery(Antarang) 
One entry is about a year old and one is from yesterday.
Phone number of contact: 918275828541

There should only be a single entry for a contact. Might want to check why we are having multiple rows with 1 year old data

**Comment by pankaj-ag** [comment]
@mdshamoon I don't have the access to bigquery can you drop a screenshot of those two duplicate entries here? A few months ago we made some enhancements to the BQ delete query and I want to confirm that if that is the reason for this issue.

**Comment by mdshamoon** [comment]
@pankaj-ag added the entries here https://docs.google.com/spreadsheets/d/1uc-nXMe8YIKKNhqxihKfS7PhDiNpXaL3c_IPNWNcdGs/edit#gid=473201090

**Comment by pankaj-ag** [comment]
Okay, I checked no bg_inserted_at and bg_uuid's why the delete query is not working. 
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/10670690/229410941-e4fbc0c7-63e4-4881-a5fc-c79fe66c525c.png">

I think for now we can do two things here. 

1. Select all the rows where the bg_uuid column is null and set a UUID and bg_inserted_at (1 year ago) in them. It will get deleted when our delete query will run. 
2. Check all the entries having duplicate entries and null bg_uuid columns and delete them manually. 


@mdshamoon can you take care of it ?

**Comment by mdshamoon** [comment]
Sure @pankaj-ag thanks. Closing the issue.
