### ISSUE TITLE
Share the possible reason for error also, while throwing error in Organization registration form

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#2748]
**Describe the bug**
It's not a bug exactly. While filling the organization registration form (https://cc.tides.coloredcow.com/organization-registration), if the app name or gupshup API keys added do not match to the one added on gupshup, we get an error saying "Contact technical support team". https://media.discordapp.net/attachments/1090958141014945924/1090958141153353798/Screenshot_2023-03-30_164217.png?width=455&height=661

**To Reproduce**
Add a different App name (different than what is given in the Gupshup account), we will get the same error. 

**Expected behavior**
Can we add a message like "Please recheck if you added the right app name/ API keys" so that one will be to cross-check before contacting us

**Comment by AkhileshNegi** [comment]
We are getting appropriate  error when adding the wrong API keys or Appname
<img width="985" alt="image" src="https://user-images.githubusercontent.com/40158831/230288261-d0765dd8-1ba2-49ae-bd49-c8ec5c86daad.png">
