### ISSUE TITLE
Getting multiple organizations on the staging server

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2754]
Getting multiple organizations on the staging server, so we can give each NGO their own working instance for free (all they need is a paid gupshup account) - [Sneha Trivedi](mailto:sneha.trivedi@glific.org) will require your input and supreme approval on this (we could potentially also just connect our own fake gupshup apps there to make it even easier)

**Comment by AkhileshNegi** [comment]
We have setup account and created [documentation](https://docs.google.com/document/d/1FJ8BEsroDjTrDRpBanc4DfAKe8Gtli0B8XXeuufE7gI/edit?usp=sharing) to access and test the account
