### ISSUE TITLE
Feature: Track feature usage across Glific at an org level and platform level

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2769]
We want to track what features are used (and not used) across Glific, both globally and specifically. This will help us optimize the UI and also let us know what to obsolete and/or put more resources into.

At a broad level we will cover the following:

- [x] Logins
- [x] Individual chat screen
- [x] Contact/Message search (Basic)
- [x] Advanced search
- [x] Flow Builder
- [x] Notifications
- [x] Templates
- [x] Interactive Messages
- [x] Triggers
- [x] Speed Sends
- [x] Flows started
- [x] Manage Collection
- [x] Tracking some specific nodes
    - [x] Webhook calls
    - [x] Split randomly (A/B testing)
    - [x] Google sheet read
    - [x] Google sheet write

- [x] #2770
- [x] #2771
- [x] #2772
- [x] #2773
- [ ] #2774

**Comment by mdshamoon** [comment]
Added following trackers in the frontend. 

| Event | Event string sent |
|--------|--------|
| Open advanced search dialog | Advanced search |
| Click on a contact to view | View contact |
| Search a contact or message | Chat search |
| Visiting a list | Visit {list name} For eg Visited flows |
| Open a flow | Flow opened | 

Let's have a quick call and decide on a standard for adding tracks

**Comment by nairabhishek73** [comment]
If I have understood this correctly then the 'event' is the activity and the 'event string sent' is the label for the data point. 
Change Event- A/B node to A/B nodes used. 
Change event string- A/B node to A/B tests.

**Comment by nairabhishek73** [comment]
Also going forward it would be good to be able to filter feature use by active flows. This will reflect current use.

**Comment by AkhileshNegi** [comment]
So far we have added support to store metrics across platform in the database. Next visualization is left which is tracked in this [issue](https://github.com/glific/glific/issues/2774)
