### ISSUE TITLE
Tracker: Visualize the daily and monthly reports

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2774]
### Description
We are saving platform metrics in the database in the `trackers` table.
Let's build visualization into the system. Both at an organizational level and at the platform level.
We should use LiveView here :)

### Goals

Let's use Liveview for this

### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Medium

### Tech Skills Needed:
Elixir, Liveview

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by KDwevedi** [comment]
comment

**Comment by AkhileshNegi** [comment]
These are the metrices we are collecting right now across platform

1. Visit HSM Template
2. Login
3. Advanced search
4. Visit user
5. Visit organization
6. Visit contactField
7. Visit collection
8. Visit interactive
9. Visit Search
10. Visit trigger
11. Visit consultingHour
12. Sheets Read
13. Random Splits
14. Visit notification
15. Visit role
16. Webhook
17. Chat search
18. Visit flow
19. Visit Sheet
20. Flow opened
21. Flows Started
22. Visit ticket
23. Visit speed send
24. Visit Settings
25. View contact
26. Sheets Write
27. Visit webhookLog
28. Visit contact

**Comment by aravind-glific** [comment]
@AkhileshNegi If these metric needs to be part of internal dashboard for orgs, none of these metric is relevant. 
If this needs to be part our internal tracker, then we can have a discussion around it.
