### ISSUE TITLE
Creation of generic function for calling template via expression

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#2783]
**Is your feature request related to a problem? Please describe.**
For calling template messages from google sheets, we would need a generic function. Currently we have one for Arogya world, but in that case it is being called from client file. We would need this for other consulting projects like PAF & DG

**Describe the solution you'd like**
Creation of generic function for sending template via expression rather than having org specific file

**Describe alternatives you've considered**

**Additional context**

@mdshamoon

**Comment by dlobo** [comment]
@AkhileshNegi do u understand this issue?

**Comment by AkhileshNegi** [comment]
@dlobo yes
