### ISSUE TITLE
Integrate with a subscription based billing system

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2794]
### Description

Glific as a SaaS platform needs an integrated billing and resource usage system to manage its customer base. Our initial integration was with Stripe Subscriptions, but due to Indian Government regulations, the prevalence of e-payments, this is no longer functional. We'd like to take a new look at this and come up with a better integration service ideally with an Indian Payment Processor (RazorPay?)

### Goals

- API Wrapper for a selected payment provider
- Review and design of subscription architecture for Glific and other T4D products
- Integration with payment provider
- Docs for implementation
- APIs for subscription from Glific
### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Medium

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by adwait-godbole** [comment]
hi, @dlobo I am interested in contributing to this problem statement. Although I have no experience with Elixir I am willing to put it extra effort to learn it along the way.

**Comment by DishaJain17** [comment]
Hi  @dlobo ,My name is Disha Jain, and I'm excited to be a part of this project. I'm currently looking for open issues to contribute to, and I would greatly appreciate it if you could suggest some for me to work on.

I have a strong technical background, particularly in the MERN stack, Java, C++, Linux, Git, and I also have a solid understanding of basics of YAML, Docker, and Kubernetes. I'm eager to utilize my skills and knowledge to contribute meaningfully to this project.Also i have a knowledge of web scraping and payment integration .

Resume:https://drive.google.com/file/d/1-mPdea8ZHQv7B19y0v8CDHl3rEJsowie/view?usp=drivesdk

Intro:
https://drive.google.com/file/d/1-8wHZN-0Ew3aojcU3xJm9MNUoWWrAoAI/view?usp=drivesdk

Blogs:https://hashnode.com/@disha390

LinkedIn: https://www.linkedin.com/in/disha-jain-90a554229

Thank you in advance for your support and recommendations. I'm looking forward to hearing from you soon!

Best Regards
Disha Jain

**Comment by chandra-pro** [comment]
Hii @dlobo ,I am Chandramani Kumar and I am interested in contributing to this issue.As I have already implemented Razorpay in my Start up based Ecommerce app.So I have good knowledge and prior experience integerating it.

**Comment by chandra-pro** [comment]
@dlobo I want to know what are the resources in Glific over which subscription based billing system should be implemented?

**Comment by RishabK05** [comment]
@dlobo I have experience with razorpay integrations and i would like to contribute to this billing system

**Comment by chandra-pro** [comment]
Hello sir @mdshamoon @AkhileshNegi  
Can you please describe me the features to be implemented in "Integrate with a subscription based billing system"?

**Comment by KDwevedi** [comment]
comment

**Comment by AkhileshNegi** [comment]
We did initial research and came up with idea to integrate Chargebee to resolve this.
Based on our discussion with them we got to know at the backend they are also using Stripe or Razorpay
Stripe we are already using 
Razorpay is not taking any new customers
So basically we are back to square one
This is the requirement doc
https://docs.google.com/document/d/1AO8ikpzt8yDx7WvF8XI5lZm9oZNoskL6F3BVAvczXTs/edit
