### ISSUE TITLE
Blank text messages received on Glific by contacts

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2798]
**Describe the bug**
There are some messages in the database that have the message body as null and type as text. These are all received messages from the contacts. We need to check why these messages are coming up as null and even if they are we should not send null to the frontend and send a placeholder like `Message not available`

Some of the contact id's that I have found in Bhumi are:

- 470154
- 1185762
- 470154

To check for Bhumi organization in DB use this query

SELECT * FROM "public"."messages" WHERE ("organization_id" = 92) AND ("body" IS NULL) and ("type" = 'text')

**Comment by ishitakapoor26** [comment]
Could you please assign this issue to me? I am new to this organization and would like to contribute here under C4GT.

Thanks & Best,
Ishita Kapoor

**Comment by mdshamoon** [comment]
Sure @ishitakapoor26. Can you clone this repository on local and let me know once done.

**Comment by ishitakapoor26** [comment]
Sure, @mdshamoon, will let you know. For now, I am facing some issues with the project setup. Heading to the discord server to get it resolved.

**Comment by dlobo** [comment]
This is a complex issue @ishitakapoor26 , not a great first issue

**Comment by ishitakapoor26** [comment]
> This is a complex issue @ishitakapoor26 , not a great first issue
> 
> @mdshamoon can u reproduce by any chance? Are they using the API?

Thank you for letting me know. But still I will try to look into this issue as it would help me to get better understanding of the project. 
Meanwhile, I can look for some beginner friendly issues.

**Comment by dlobo** [comment]
I looked in the production DB, and saw there were only 11 messages (out of a few million)

did some digging and cleaned up the code. Also learned a bit more about ecto. PR coming soon
