### ISSUE TITLE
Sync tracker table to bigquery for visualizing the most used features in Glific

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2805]
**Is your feature request related to a problem? Please describe.**
We want to understand the usability of the platform and for that we have already added trackers to collect information for most features. Now we want to visualize and understand the most used features in Glific through a dashboard

**Describe the solution you'd like**
For this we will need to sync the tracker data to bigquery and then create a data studio report with the available data.
This will be exactly similar to the sync of stats_all table.

**Comment by KrishnaDwibhashi2** [comment]
V1 of Dashboard- 2 pages

Page 1-
1) 2 filters- Organization name, Date range
2) Bar graph- X-axis: Feature names, Y-axis: Count (I am assuming the count is the number of time a feature was used)
3) Same things in a tabular format- Rows- Org name, Column- Feature names, Cells- Count

Page 2-
1) 2 filters- Feature name, Date range
2) Bar graph- X-axis: Organization names, Y-axis: Count

@mohitgusain
