### ISSUE TITLE
Create a server to use Glific APIs in your preferred language

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2817]
### Description

To effectively utilize the [Glific APIs](https://api.glific.com/), it is necessary to follow a specific set of steps. However, for individuals new to the platform, it can be cumbersome to repeatedly write code for each step.

To simplify the process, we can create a straightforward server that adheres to the following sequence of actions. This server can serve as a reference for new users seeking to use the APIs

1. Begin by utilizing the login API to acquire the following information:
   - Access token
   - Renew token
   - Expiry time
  
2. Store the obtained data and enhance subsequent API calls by including the access token in the header.

3. Regularly check if the token has expired. If it has, utilize the renewal token to obtain a fresh access token through the designated [API](https://api.glific.com/#23b77640-b818-459b-88e0-3437665bf7ad).

By following this approach and creating a user-friendly server, new users can reference the implementation to efficiently utilize the Glific APIs without the need to rewrite code for each step.

### Goals

1. Basic Login by creating a token, storing it, and refreshing it when needed
   - [Login API which returns token and expiry time](https://api.glific.com/#4a9a72a5-01d3-4af4-a7e0-7b50a67c6dac)
   - [Refresh Token API doc](https://api.glific.com/#23b77640-b818-459b-88e0-3437665bf7ad)

2.  Send messages to contacts using send message API
   - [Messages API Doc](https://api.glific.com/#f53792cf-f45a-4fe3-9767-5315fc3a4b3e)
   - [Send Message to a contact API Doc](https://api.glific.com/#c09fbc20-193d-4c36-a927-e2c30c4cc14a)

3. This has to be a long-running server that does not terminate (unless killed). You might want to consider using ChatGPT to outline the solution of your project. 

4. Please document the project. Extra credit for adding unit tests. Use the features of the language to ensure high quality code with type hints etc

### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Medium

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by KDwevedi** [comment]
comment

**Comment by Abro0058T** [comment]
Hi , @AkhileshNegi  Can i work on this issue?

**Comment by SanjayRam07** [comment]
hello @geeky-abhishek , can I work on this issue?
Could you please assign and mentor me?

**Comment by AkhileshNegi** [comment]
Closing this for now as there is no consistent progress

**Comment by HimanshiEnigma** [comment]
Hello @AkhileshNegi i would like to work on this issue
