### ISSUE TITLE
Automated Language Translator

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#2818]
**Is your feature request related to a problem? Please describe.**
The feature is used to translate text in default language to a selected language automatically, without manually typing it out. The problem is huge manual overhead when there are lot of flows/ nodes and a lot of text needs to be translated. Many NGOs face delay in deployment because of this manual work. Sometimes the translations are missed and this causes problems in the user journey. 

**Describe the solution you'd like**
The text entered in every node in the default language must be auto-translated to a language chosen. The NGO could edit it, reducing a lot of manual repetitive work. Whenever you open up a flow in a language different from the default one, the text typed out in default language should be shown in the language chosen. There might be edits required, but the NGOs will have something to work on & needn't start from zero.

**Describe alternatives you've considered**
NGOs continue with the current method

**Additional context**
MicroSave has faced issues with translation. Received this requirement from Bala Vidya as well (new, considering using Glific).

**Comment by dlobo** [comment]
We should also check some of the new cool stuff that nyaruka has done with floweditor

https://floweditor.nyaruka.com (create a few nodes, and switch to Spanish) and click on translate

a good c4gt project to incorporate that aspect?

**Comment by mdshamoon** [comment]
Tracking in #https://github.com/glific/glific-frontend/issues/2456
