### ISSUE TITLE
Dockerize Glific frontend and backend

### ISSUE THREAD

**Issue by dlobo** [glific/glific#2820]
**Description**
Right now to see Glific in its full glory we need to setup Glific frontend and Glific Backend and there are some steps that are documented in the Readme that need to be followed to set up. However, completing those steps and get up and running instance takes time.

**Goals**
Create a docker file so it is easy to onboard and get new developers up and running with Glific

**Project:** Glific

**Organization Name:** Project Tech4Dev

**Domain:** Social Sector

**Complexity:** Medium

**Tech Skills Needed:** Elixir, Liveview

**Name of Mentors:** @AkhileshNegi @dlobo 

**Category:** Feature

**Product Set-Up:** https://github.com/glific/

**Acceptance Criteria:**
Single Docker file which can be used to set up both frontend and backend after updating .env file to get up and running Glific instance in local

**Comment by mihir1739** [comment]
I will like to work on this. Please assign this issue to me!

**Comment by KDwevedi** [comment]
comment
