### ISSUE TITLE
Templates: Filtering by category

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2824]
**Description**
Gupshup recently shared a new pricing model where the price to send template messages depends on the category of the template i.e. "UTILITY", "MARKETING", "Or AUTHENTICATION". Thus filtering the list template based on category can help NGOs to see templates across categories

**Goals**
The category is already present in the database we only need to filter based on the category in the list template API

**Project:** Glific

**Organization Name:** Project Tech4Dev

**Domain:** Social Sector

**Complexity:** Easy

**Tech Skills Needed:** Elixir

**Name of Mentors:** @AkhileshNegi 

**Category:** Feature

**Product Set-Up:** https://github.com/glific/

**Acceptance Criteria:** PR merged into the main branch

**Comment by KDwevedi** [comment]
comment
