### ISSUE TITLE
Templates: Editing approved templates

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2827]
### Description
With the latest changes to Gupshup API, an existing approved template can be edited, this will be helpful in case an approved template has a typo or need a few cosmetic changes
New API can be found [here](https://docs.gupshup.io/reference/edittemplate) and also in [Partner API](https://www.gupshup.io/docs/partner/)

### Goals
Add new API to edit approved

### Project Name:
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Easy

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by KDwevedi** [comment]
comment
