### ISSUE TITLE
Templates: Allow Category change

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2828]
### Description
While Applying for template, there is a new flag `allowTemplateCategoryChange` which when enabled Meta will automatically update the category of the template as per the template content. The default value is False. If the category gets updated, you can view the old category from the [Get Templates API](https:/[/www.gupshup.io/docs/partner/#collapse-TemplateApis-App_7CGetTemplates)

### Goals
Update API to keep this as true by default while applying template from Glific

### Project: 
Glific

### Organization Name: 
Project Tech4Dev

### Domain: 
Social Sector

### Complexity: 
Easy

### Tech Skills Needed:
Elixir

### Name of Mentors: 
@AkhileshNegi 

### Category: 
Feature

### Product Set-Up: 
https://github.com/glific/

### Acceptance Criteria: 
PR merged into the main branch

**Comment by KDwevedi** [comment]
comment
