### ISSUE TITLE
Check if the flow is already edited by someone in another tab and send an error

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2834]
## Task

We should follow rapidpro in doing the same. The code reference is added below.  https://github.com/nyaruka/rapidpro/blob/3ba4af9568aad630fd1f6d8ba7e665b0ad6bfebe/temba/flows/models.py#L813

The format of the error response will be

```
{
    "status": "failure",
    "description": "mdshamoon@glific.org is currently editing this Flow. Your changes will not be saved until you refresh your browser.",
    "detail": null
}

```

Will remove the takeover functionality then

**Comment by dlobo** [comment]
We will not implement this style of rapidpro. We dont think it is good UI/UX
