### ISSUE TITLE
Lack of API Documentation for Notification and Notification Count APIs

### ISSUE THREAD

**Issue by VishalZ123** [glific/glific#2839]
I would like to report an issue regarding the absence of API documentation for the notification and notification count endpoints on the [Glific APIs](https://api.glific.com/) platform. As a contributor to the Glific Mobile Application, I want to query these APIs for notifications, I was unable to find the necessary information to make use of these APIs effectively.

**Comment by AkhileshNegi** [comment]
Updated documentation [here](https://api.glific.com/#c67c8a5f-5507-4db8-a61f-59810294689b)
