### ISSUE TITLE
Include 'group' field in get all users query

### ISSUE THREAD

**Issue by cindyzhang12** [glific/glific#284]
**Is your feature request related to a problem? Please describe.**
For the Staff Management screen, there is currently no query that fetches username, phone number and user group together.

**Describe the solution you'd like**
Add a field in the get users query for the group they're in/

**Additional context**

![image](https://user-images.githubusercontent.com/61183011/88337120-286cbe80-cd04-11ea-9e10-cf25a7085543.png)

**Comment by anshulrnr** [comment]
Added groups field to the users query.

**Comment by pankaj-ag** [comment]
@cindyzhang12 please have a look at the docs for using the user API. 
https://github.com/glific/glific/blob/master/api.docs/includes/_users.md#get-all-users

Closing this one as complete. Feel Free to reopen in case you see any issue.
