### ISSUE TITLE
Provide NGOs with the option to delete contact fields along with associated data.

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2847]
Primary issue link: https://github.com/glific/glific-frontend/issues/2413
  
  **Tasks:**
    - Enhance the backend API to support field and data deletion.
    - Write a batch process using Elixir tasks to delete the field and its data from all contacts.
    - Optimize the batch process for efficiency and performance.

**Comment by aravind-glific** [comment]
@mdshamoon Can we also enable bulk deletion of contact variables in the listing page, option to multi-select 
![image](https://github.com/glific/glific/assets/132430123/5ca2c41a-1b92-4d68-a86f-728c58a99a60)
