### ISSUE TITLE
Multi-Select for Collections in Triggers

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#2868]
### Description
Currently, only one collection could be selected while configuring Triggers. If the flow to be scheduled/ triggered is for multiple collections, multiple triggers need to be created. 

### Goals
The dropdown currently used for choosing the Collection called 'Select Collection', make it possible for selecting multiple collections with minor tweaks on UI and no difference in the user experience aspect. Something like (Select Multiple Collections) in bracket to let the NGO know that multi-select is possible. 

![Screenshot 2023-07-05 at 1 58 27 PM](https://github.com/glific/glific/assets/132430123/0c26b4ac-cf60-4093-aef1-46a666127aca)

### Project Name
Glific

###  Organization Name
Project Tech4Dev

### Domain
Social Sector

### Complexity
Easy

### Tech Skills Needed
Elixir

### Name of Mentors
@AkhileshNegi 

### Category
Feature

### Product Set-Up
https://github.com/glific/

### Acceptance Criteria
PR merged into the main branch

**Comment by aravind-glific** [comment]
- The requirement is to schedule a particular flow to different groups/ collections together, the message delivery whether parallel or sequential wouldn't make a ton of difference
- Can't we do a check whether a user has been taken to the same flow using the same trigger within a given timeline to avoid this?
- Yes, creating multiple triggers could solve for this, but every NGO who raised this requirement are already doing this & that's probably why they saw the scope for improvement. 
- Also, in case we're implementing this, why don't we show a warning pop-up when someone chooses the second collection in trigger, saying something like 'Please make sure both the collections doesn't have duplicate contacts. The flow will be triggered twice for duplicate contacts' and hence transfer the obligation/ risk of mistake to their end. 
- More elegantly, we can try to give them a list of contacts/ number of contacts who are common across both collections and let them know something like 'The flow will be triggered twice for x contacts who are part of both collections selected'. In this way, they could either rework on their collections or avoid using multi-select
- If required, I can get feedback from all 3 NGOs who raised the request, communicate risks & understand their perspective better

**Comment by mahajantejas** [comment]
> ### Description
> Currently, only one collection could be selected while configuring Triggers. If the flow to be scheduled/ triggered is for multiple collections, multiple triggers need to be created.
> 
> ### Goals
> The dropdown currently used for choosing the Collection called 'Select Collection', make it possible for selecting multiple collections with minor tweaks on UI and no difference in the user experience aspect. Something like (Select Multiple Collections) in bracket to let the NGO know that multi-select is possible.
> 
> ![Screenshot 2023-07-05 at 1 58 27 PM](https://user-images.githubusercontent.com/132430123/251087294-0c26b4ac-cf60-4093-aef1-46a666127aca.png)
> 
> ### Project Name
> Glific
> 
> ### Organization Name
> Project Tech4Dev
> 
> ### Domain
> Social Sector
> 
> ### Complexity
> Easy
> 
> ### Tech Skills Needed
> Elixir
> 
> ### Name of Mentors
> @AkhileshNegi
> 
> ### Category
> Feature
> 
> ### Product Set-Up
> https://github.com/glific/
 
> ### Acceptance Criteria
> PR merged into the main branch

**Comment by mahajantejas** [comment]
Usecase for building this feature: Reap Benefit, which operates 3-4 of glific's chatbot -> DDCD, PMIDC, Jal Jeevan Mission, and Solve Ninja Mentor, they do broadcast of messages to multiple collections, sometimes ranging to 6-8 collections per message and this usually happens across the chatbos-> having this functionality would reduce their time effort. 

The responsibility to minimise duplicate contacts in the collections lies with the NGOs, which is a inherent risk they facing in the present way of doing things.

**Comment by aravind-glific** [comment]
Antarang use case : While scheduling reminder messages for different workshops planned for a month, triggers are used for sending reminders a day before. Multiple collections (based on different interests) needs to be send these reminders and hence enabling multi-select for collections in triggers would enable them to use one trigger for the whole month instead of having individual trigger for each workshop.

**Comment by dlobo** [comment]
Let's schedule and do this. should be quite easy from the backend since we just need to fill in the broadcast contacts table

**Comment by aravind-glific** [comment]
TAP use case : TAP used to handle 15 teacher collections for different cities and never used to have a superset collection of all teachers. Also, didn't had the capacity to query and merge all contacts into one collection. Having this feature would've saved some time from creating individual triggers for each. Later a large collection including all teachers were used, but maintaining that collection with updated contact information would be an additional task.

**Comment by AmishaBisht** [comment]
@mdshamoon please take a look in this issue and make changes to the frontend as follows:
Right now, only one group id is being sent from the frontend as string type. We need to change it so that multiple group IDs can be sent as a list of integer. Here is my PR you can see the code changes in there https://github.com/glific/glific/pull/3004

**Comment by mdshamoon** [comment]
@AmishaBisht  in the trigger get query also we need to update to groups. Right now its only getting a single groups. Can you please update that.

**Comment by rising0raj** [comment]
Hey @aravind-glific , I am more than eager to contribute and would ensure you that i will resolve the issue once the data is available on the website , can you assign it to me so I start working on the issue as soon as the data is uploaded on the website
