### ISSUE TITLE
GCS Worker: Files not getting synced

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2915]
**Describe the bug**
GCS files are taking significant time to get the upload to client's GCS account
This has been raised by LAHI(org: 14) and Udhyam(org: 95) so far

There has been some inconsistency as some of the new files are uploaded but some old files are not uploaded

**Expected behavior**
Files should be synced asynchronously, within a few mins

**Comment by dlobo** [comment]
I dont think our current architecture is very good for this. Works great at small to medium scale, not so good for large scale

Lets rethink. I think we need to do it in bulk from WhatsApp servers to GCS buckets

**Comment by AkhileshNegi** [comment]
Synced the files that were pending since January
