### ISSUE TITLE
Glific connector: Need schema in Organization Export Config API

### ISSUE THREAD

**Issue by Ishankoradia** [glific/glific#2922]
**Is your feature request related to a problem? Please describe.**
For the glific connector we are building, each stream (i.e. table) requires a schema to sync normalized data (flattened). This schema should have the information for each column along with its name and data type. 

**Describe the solution you'd like**
Currenly the export config api for an organization has the following structure 
```
{
    "data": {
          "organizationExportConfig": {
                   "tables": ["<table-name>", ...],
                   "languages": [],
                   "providers": [],
                   "config": []
          }
    }
}
```

Can we update the response to add `schema` for each table as follows
```
{
    "data": {
          "organizationExportConfig": {
                   "tables": [
                          {
                                "name": "<table-name-1>",
                                "schema": {
                                      "col-name-1": { "type": ["string", "null"] },
                                      "col-name-2": {"type", ["number"]},
                                }       
                          }
                   ],
                   "languages": [],
                   "providers": [],
                   "config": []
          }
    }
}
```
The schema convention that airbyte uses can be found [here](https://docs.airbyte.com/connector-development/schema-reference) . AirbyteRecords are required to conform to the Airbyte type system which can be found [here](https://docs.airbyte.com/understanding-airbyte/supported-data-types/ )

**Describe alternatives you've considered**
Another alternative is define the schemas manually i.e. hardcode them. Many of the source connectors like github connection have that. But then everytime we have a change in schema like an extra column or column name change or data type change, we will have to submit a PR to airbyte to update the schema. 

**Additional context**
Currently, the way we have handled normalization in surveyCTO connector is we do the api call to pull data twice. The first call is just to define and generate schema for each stream from the response data while the second one is to actually sync the data. This is not the most optimized approach since it requires unecessary api calls that degrade the performance. 

@AkhileshNegi @dlobo want to understand how much effort this would take ? If its a lot, we will go with the approach mentioned in `Additional Context`

**Comment by dlobo** [comment]
should not be too hard

@AkhileshNegi might be a good first project for @AmishaBisht . we can get this either from postgresql or from our internal types

**Comment by siddhant3030** [comment]
> should not be too hard
> 
> @AkhileshNegi might be a good first project for @AmishaBisht . we can get this either from postgresql or from our internal types
> 
> ```
> schema = 
> :fields
> |> Glific.Contacts.Contact.__schema__()
> |> Enum.map(fn(field) -> {field, Glific.Contacts.Contact.__schema__(:type, field)} end)
> ```

@dlobo this approach might not work. Can we pull out from the Postgres types and not the elixir types? There will be some schema miss matching in case we're using this.

**Comment by dlobo** [comment]
We'll use this approach and then modify the elixir schema returned to what u want in DDP. there is a one <-> one.mapping between echo schema  types and Postgres types

can u be more specific on wy it might not work
