### ISSUE TITLE
Introduce short name for the saved searches

### ISSUE THREAD

**Issue by kurund** [glific/glific#294]
**Is your feature request related to a problem? Please describe.**
* Currently we have a label field for Saved Searches which is used to describe saved search. It is might not be usable to display the same in the frontend.
For eg: Conversations where the contact has opted out

**Describe the solution you'd like**
* We should add new field "descriptions" for storing details on the saved search.
* We can use label for short name.
For eg:
label: Opted Out
description: Conversations where the contact has opted out

**Comment by dlobo** [comment]
Since we are using the convention of label/shortcode, how about we stick to the same here:

label == "Conversations where the contact has opted out"
shortcode == "Opted Out"

**Comment by kurund** [comment]
Perfect! that works.
