### ISSUE TITLE
Emails: Custom low balance mails

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2949]
**Is your feature request related to a problem? Please describe.**
Based on the scale NGOs is working with low balance can be subjective, right now we send email when the Gupshup balance is less than 10$ and when it has become zero.

**Describe the solution you'd like**
Add the ability to customize the low balance threshold for an organization so an organization gets an email when they hit this threshold

**Comment by AmishaBisht** [comment]
closed

**Comment by AmishaBisht** [comment]
Closes #2949
