### ISSUE TITLE
Blocking users feature

### ISSUE THREAD

**Issue by manishmanohar** [glific/glific#295]
**Is your feature request related to a problem? Please describe.**
We just figured out there is no feature of blocking users in business api. As we scale we feel that there would be clients who send us inappropriate messages. Since, all our conversations are escalated to a human it leaves a trauma to our agents who are attending users via chat. 

**Describe the solution you'd like**
Making a Block list of those users or auto tag blocked users.

**Describe alternatives you've considered**

**Additional context**

**Comment by dlobo** [comment]
Abhishek:

can you include this in feature list and schedule for 0.3

we'll need to block/unblock contacts, also have a list of contacts currently blocked and the messages they've sent.

we need to decide what to do with those messages: discard them on receipt, or store them, but not show them

**Comment by pankaj-ag** [comment]
Closing this one as done.
