### ISSUE TITLE
Internal Dashboard: Monthly Conversation

### ISSUE THREAD

**Issue by Chaitanya1512** [glific/glific#2958]
### Description
Improving Internal Dashboard by adding a few more metrics

### Goals
Update the current `Monthly Conversation` metric functionality to source data from `stats` table for better relevance.

### Project Name
Glific

###  Organization Name
Project Tech4Dev

### Domain
Social Sector

### Complexity
Easy

### Tech Skills Needed
Elixir, Liveview

### Mentor(s)
@AkhileshNegi 

### Category
Feature

### Product Set-Up
https://github.com/glific/

### Acceptance Criteria
PR merged into the main branch

**Comment by SoumyadipYT-OSS** [comment]
I am interested on this project as of having basic knowledge in Elixir programming language.

**Comment by Sayanjones** [comment]
@Chaitanya1512 I'm interested on this project. Can we discuss further?
