### ISSUE TITLE
Automated Flow Tester

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#2972]
**Is your feature request related to a problem? Please describe.**
The design & logical errors during flow creation is a major issue that happens across all NGOs. The ability to mitigate the errors or help them troubleshoot the issues at a Publishing level would be really helpful. Currently, we've a set of errors which are shown at the time of publishing. This feature is an enhancement to the existing functionality to alert the NGOs about more design flaws which is not handled currently.

**Describe the solution you'd like**

**Language Alert :** When the messages in different languages are not updated for all the nodes, throw an error/ warning and highlighting the nodes; whenever there is a change in content in the default language, a warning should be shown to make sure that relevant changes are made in the translated content in other nodes
Auto populate data from previous node in 'Wait for Response' node : ‘Wait for Response’ node doesn’t have any data auto populated when the node is created. Auto-populating data from a previous interactive message, list of options given would be helpful in speeding up flow creation process.
**Highlighting Error Node :** Highlight the node which is having an issue in the flow editor (like dangling node)
**Flag erroneous activity :** Discrepancies within a flow which is already published & triggered/ send to users should be flagged or notified. This is in context of TAP who realized there was an issue with the flow 3 days after the flow was triggered.
**HSM Template alert :** After ‘Wait for contact’ node, if the delay is more or equal to a day, then the subsequent message should be HSM → could be incorporated in triggers
Displaying variable name instead of value : For variables named incorrectly/ not fetching correct data instead showing the “@results.____” ,make sure a warning is displayed beforehand to avoid corrections at a later stage → use dropdown options

**Describe alternatives you've considered**
Missing Wait for Response node - Based on issue reported by QA - https://discord.com/channels/717975833226248303/1164029264115535943/1164029264115535943

**Additional context**

**Comment by aravind-glific** [comment]
@AkhileshNegi These are the relevant items we had discussed for automated flow tester from the city meetup inputs. Let me know if something needs to be added/ removed.

**Comment by AkhileshNegi** [comment]
A part of it is covered in this [issue](https://github.com/glific/glific/issues/3035)
