### ISSUE TITLE
Delete profile giving error

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2973]
**Describe the bug**
When we try to delete a profile from the contact profile section it gives an error.

**To Reproduce**
1. Create two profiles and go to the contact profile section
2. Click on remove button and press delete 
3. It shows an error after some time

**Expected behavior**
There should be no error

**Screenshots**
![image](https://github.com/glific/glific/assets/32592458/e346f064-a92e-4ce8-8645-63bdd08250e6)

**Comment by dlobo** [comment]
This should be fixed now. There was an index missing in contact_histories for profile_id which was causing thing to fail (timeout due to delete cascade)

@mdshamoon can u please check
