### ISSUE TITLE
New contact flow not working for the contacts

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#2977]
**Describe the bug**
New contact flow not working for the contacts

**To Reproduce**
1. Try to message on a bot with a new contact and have the new contact flow enables
2. The new contact flow is not invoking for the contacts

**Expected behavior**
It should invoke the new contact flow

**Comment by AkhileshNegi** [comment]
the issue is we recently deleted all the default tags for organizations and we are tagging a new contact message with one of the default tags and that tag is no longer in DB so it is giving error and newcontact flow is not starting.
We have removed that dependency now
