### ISSUE TITLE
View-only function for flows

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2981]
**Is your feature request related to a problem? Please describe.**
The request is raised by KEF. Below are the details of the request.
Hey, is it possible to add a view-only function for flows?
Asking this because, if a person is working on the flow and I need to view it, I'll need to either take over the flow or wait for the person to finish their edits on the flow.
 The view-only function would save a lot of time.

**Describe the solution you'd like**
Have an option to view only the flow to review it.

Creating a ticket for tracking and for discussion with the tech team if this is feasible to have such functionality.
https://discord.com/channels/717975833226248303/1136980851352158218/1136980851352158218

**Comment by AkhileshNegi** [comment]
Duplicate issue https://github.com/glific/glific/issues/3007
