### ISSUE TITLE
Real-time handling of errors

### ISSUE THREAD

**Issue by gaurya95** [glific/glific#2990]
**Is your feature request related to a problem? Please describe.**
Few days back there was a gupshup error. FB was running an experiment and a message wasn't sent. The issue came back from the customer to our OPs team to the tech team.

**Describe the solution you'd like**
I would like to have real-time handling of such errors. In flows, maybe a retry mechanism.

**Describe alternatives you've considered**
Talked to Glific team. They told me to raise this issue.

**Additional context**
NA

**Comment by mahajantejas** [comment]
how to handle failure cases? 
how to inform the NGO team of the failure cases
