### ISSUE TITLE
SaveSearch: Timing out

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2995]
**Describe the bug**
While using SaveSearch, the query is timing out and error is showing in the main screen

**To Reproduce**
1. Go to your Glific instance
2. Click on advanced search button on the search bar
3. Add date range starting start of this month and ending end of the month
4. Click Search
5. See error

**Expected behavior**
Conversation during the time duration should appear on the screen

**Screenshots**
<img width="580" alt="image" src="https://github.com/glific/glific/assets/40158831/552ba10d-b9ac-4559-aa9d-8631d40d785d">

**Comment by dlobo** [comment]
we should come back to this after message cleanup

I dont see how we can optimize the current queries :(

**Comment by AkhileshNegi** [comment]
Things look better now, ever since we cleaned up the DB. Closing this for now
