### ISSUE TITLE
Google Sheets: Update row functionality

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#2999]
Update a row with value in Write to Google Sheets : Currently, while using Write to Google Sheets, every new entry goes into the next new row which doesn't have any value in any of its cell. But sometimes, the user input might be invalid/ wrong and if there's a way to update any row, it would be a good enhancement to have. New row needs to be used only if the user is new, for an existing user, the row which already exists need to be updated. The logic for adding new entries to sheet must be updated to enable this.

Context : Raised as an enhancement by KEF, RB

**Comment by mdshamoon** [comment]
@aravind-glific google sheets doesn't provide any API for updating a row. Closing this since it is not possible as of now.
Adding the documentation link https://developers.google.com/sheets/api/guides/values
