### ISSUE TITLE
Ticketing System : Avoid exiting from existing flow while responding to Support Query

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3001]
When the user query is being answered by the staff member, the flow which the user is currently in gets terminated. Workaround to handle this scenario since ticketing system is used to handle queries & a response to query is an inherent part of the process

**Comment by KrishnaDwibhashi2** [comment]
Few organizations do have a help flow (with FAQ/ Changing language options etc) which the user can access by typing out help keyword. Even in this case, when the user is taken to a new flow, bringing them back to the origoinal flow at the exact same point makes the flow design complex. Can we have a work around for this?

**Comment by AmishaBisht** [comment]
Closing the issue for now, with the following reasons:

1. Not replicable(no clear steps to replicate the issue)
1. Vague information (the beneficiary did not provide clear information regarding this issue).
