### ISSUE TITLE
Ticketing System: Export support tickets from interface

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3002]
- Exporting support tickets directly from interface using a download icon in a downloadable format like .csv or .xls
- Requested by Nayi Disha

**Comment by KrishnaDwibhashi2** [comment]
In addition to status, name, date, Open by, the category should also be downloadable in the csv/xls

**Comment by aravind-glific** [comment]
<img width="696" alt="Screenshot 2023-12-14 at 8 20 36 AM" src="https://github.com/glific/glific/assets/132430123/763a899e-9278-43bd-929f-831c0a003302">

In the export of support ticket, the data for 'topic' and 'inserted_at' are inter-changed. [Refer the screenshot : Column C & D]. The inserted_at doesn't show the time stamp as well, just the date.
Reopening the issue.
