### ISSUE TITLE
Flow to have View & Edit mode for accommodating multiple people working on a single flow

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#3007]
**Is your feature request related to a problem? Please describe.**
As organizations are growing, multiple people work/ check a single Glific flow. Currently, when 2 people want to check a flow while one is working on it, the other person has to wait for taking over (even for viewing it). It also needs coordination between the people on whatsapp/discord requesting for takeover.

**Describe the solution you'd like**
Can we have view mode & edit mode for flows? When one person is working/editing it, other people can still view the flow & changes. Also, if we can have the option to "Request for take over" rather than directly taking over, it might make things easier.
In future, we can explore the option of multiple people editing the same flow. Right now, i don't see that it is required. View & edit mode should suffice.

**Describe alternatives you've considered**

**Additional context**
KEF, TAP has raised the issue. We have also observed it & felt the need while working internally/ with NGOs.

@mdshamoon @AkhileshNegi @aravind-glific

**Comment by AkhileshNegi** [comment]
Duplicate issue https://github.com/glific/glific/issues/2981
