### ISSUE TITLE
Improve message deletion code 

### ISSUE THREAD

**Issue by dlobo** [glific/glific#3013]
We need to delete messages aggressively. Our current method does not scale and does not reduce the messages significantly. Here's a proposed alternative:

* Create a new column in message_media table to mark media objects that are used by other tables, specifically session_templates for now. We need to ensure that these entries are not cleared. Ensure that this column has an index
* In the migration script, mark all the session media objects as such
* Add a new index to the inserted_at and organization_id column in messages tables
* Drop the FK constraint on messages table to messages_media (I did this manually on the production server)

The algorithm for deleting is as follows, which we'll do weekly:
* For a given date, go back in time for 2 months (we'll keep one month as buffer for now, make this a variable)
* For each organization do
  * Delete all message media objects that were inserted before the above date EXCEPT for session templates
  * Delete all messages that were inserted before the above date
  * For all contacts set the fist and last message number if one exists, else let them be null (and ensure we handle null case for search etc)

**Comment by dlobo** [comment]
The first part is done, the second part remains to be done and a good sprint project

**Comment by AkhileshNegi** [comment]
We have cleaned up messages, The Next steps to optimise this further are added [here](https://github.com/glific/glific/issues/3084)
