### ISSUE TITLE
Ticketing System : Functionality to share audio files back & forth

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3019]
Functionality for end users to share audio file queries would help them easily describe the issues. The responses too, when responded as audio note, would make the communication faster. Raised as a request by KEF. 

Having the ability to handle media files like images, video or audio notes would enhance the functionality of ticketing system & it could be used for handling scenarios other than support (sample use case : homework submissions)

**Comment by AmishaBisht** [comment]
closing for now only
