### ISSUE TITLE
Flows: Warning Categorizations

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3035]
**Is your feature request related to a problem? Please describe.**
While publishing the flows, if there are any errors we show them as warnings as mentioned in this [document](https://glific.github.io/docs/docs/Product%20Features/Flows/Others/Flows%20not%20working%20-%20Troubleshoot%20checklist/#4-errors-while-creating-flow)

Next, we want to categorize these errors in two parts i.e.
1. Warnings that can be ignored
2. Warnings that need attention and should be fixed as they might result in breaking flow

These warning will then be shown in two parts in the flow screen

**Comment by KrishnaDwibhashi2** [comment]
Warnings that need attention and should be fixed as they might result in breaking flow-
1) Could not find Sub Flow
2) The next message after a long wait for time should be an HSM template/. HSM template message alert
3) Could not find Group/collection
4) Could not find Contact(staff member)

Warnings that can be ignored
1) Your flow has dangling nodes
2) Language Alert

@aravind-glific Could you help in writing warning message to be shown & getting design for the same?

**Comment by aravind-glific** [comment]
@AkhileshNegi The designs are already ready, please find them on the link below :
https://www.figma.com/proto/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?page-id=2%3A2649&type=design&node-id=2119-2279&viewport=-12277%2C-39559%2C0.97&t=DL6S4OwXq9auSQmW-1&scaling=min-zoom

You can use the same messages that were previously used.

**Comment by AkhileshNegi** [comment]
We have added support from backend, created issue for frontend [here](https://github.com/glific/glific-frontend/issues/2625)
