### ISSUE TITLE
Linked Google Sheet records are getting updated from column Y

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#3046]
**Describe the bug**
The issue is reported by Reap Benefit for Jal Jeevan BOT.
The Writeable Google sheet was working fine but from 21 Aug, the new records are added from column y.
Whereas the node is correctly set for Column A to Z.

Flow Link - https://jjmassam.tides.coloredcow.com/flow/configure/f4194f7d-8353-4502-861e-7072289a0c30

**Expected behavior**
It should write the new records from column A.

**Screenshots**
<img width="636" alt="Screenshot_2023-08-22_at_3 09 36_PM" src="https://github.com/glific/glific/assets/16541548/8eb70805-d0c1-4a28-a495-35c13401b3ef">

**Comment by mdshamoon** [comment]
Issue cause is mentioned here:
https://discord.com/channels/717975833226248303/1143460193531875328/1144579237190316233

**Comment by mdshamoon** [comment]
Added resolution for the issue in this thread
https://discord.com/channels/717975833226248303/1143460193531875328

**Comment by mdshamoon** [comment]
@mahajantejas thanks for bringing this up. Haven't updated in the documentation. I will need support in getting this done. Was not sure the best way to explain this
