### ISSUE TITLE
Integration with Jugalbandi Voice

### ISSUE THREAD

**Issue by bandhu-tech** [glific/glific#3054]
**Is your feature request related to a problem? Please describe.**
We have already implemented a custom integration ("jugalbandi_json") by Glific which parses a user's query and format it into a JSON request to be passed to our database. However, this function is currently only working for a text query and jugalbandi's /query-with-langchain-gpt3-5-custom-prompt API. It does not work for jugalbandi's /query-using-voice-gpt4 API. 

**Describe the solution you'd like**
We need the same solution as we did for the text one, but compatible with this voice API.  

**Describe alternatives you've considered**
No alternatives to this. Without this voice API integration, our product rollout is incomplete. 

**Additional context**
Have been working on this in "html link test" flow. Voice flow parameters made in this custom solution should be as similar as possible to the text one, so that we can debug it easily.

**Comment by mahajantejas** [comment]
Tested with Jban on 31-aug-2023, 

Observation 

1. voice prompt along with a one shot prompt to return the answer in json is working as expected in juglandhi api envi
2. voice prompt along with one shot prompt is returning a free flowing answer in glific flow.

Take-away
1. Akshilesh looked into the code and inferred that debugging needs to happen as to why it is behaving differently.

**Comment by mahajantejas** [comment]
The flow they were using to test- https://bandhu.tides.coloredcow.com/flow/configure/110540be-f85d-4916-aac2-9919f99c9539 @AkhileshNegi

**Comment by AkhileshNegi** [comment]
```
Audio URL: https://storage.googleapis.com/cc-tides/WhatsApp%20Ptt%202023-09-28%20at%202.53.17%20PM.ogg
Prompt: Convert the user query to JSON template. Only respond with one JSON with latest information. If the user does not specify a type of housing, provider an answer in regular text not JSON, and you must only respond by asking the user to try again and specify if they want a housing type of Apartment/Flat, House, Basti, Worker Dorm, or Sleeping Space. You MUST supply a value for language code. If the input language is English, then the JSON value for language_code will be \"en\". If the input language is Hindi, then the JSON value for language_code will be \"hi\". If the user does specify any or partial text from these options, continue returning the JSON template. If any response is in a script other than English, you will translate the string to English and the JSON value must be created in English script. The key-value pairs for the JSON to be created are the following: {\n \"language_code\": \"<language name>\", \n  \"city_name\": \"<city>\", \n \"area_name\": \"<area name>\", \n  \"price_monthly_max\": \"<maximum rent>\",\n \"price_monthly_min\": \"<minimum rent>\", \"deposit\":\"<deposit>\", \n \"brokerage\":\"<brokerage>\", \n \"rooms\":\"<rooms>\", \n \"sleeping_spaces\": \"<sleeping spaces>\", \n \"max_guests\": \"<maximum number of guests>\", \n \"guest_type\": \"<type of guest>\", \n \"housing_type\": \"<type of housing>\", \n \"diet\":\"<diet preference>\", \n \"shift_in\": \"<move-in date>\", \n \"stay_until\": \"<move-out date>\", \n \"electricity\": \"<electricity>\", \n \"electricity_type\": \"<electricity payment>\", \n \"toilet\":\"<toilet type>\"\n \"toilet_type\":\"<toilet payment>\", \n \"kitchen\":\"<kitchen requirement\",\n \"bathroom\":\"<bathroom>\", \n \"part_of_house\":\"<part of house>\", \n \"latitude\":\"<latitude>\", \n \"longitude\":\"<longitude\"}
input_language: English
output_format: TEXT
```

**Comment by AkhileshNegi** [comment]
Closing this as we haven't heard back from them for some time. We'll check in-person
