### ISSUE TITLE
Add validation for Empty Expression added in send message

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#3056]
**Describe the bug**
Reported by Kshamtalaya.
They were not able to publish the flow. error was showing in the console.
On investigation, Shammon mentioned, that there is an empty expression added in the node.
The request is for add validation so that an empty expression cannot be added to the node

**Screenshots**

<img width="554" alt="Screenshot 2023-08-25 at 11 26 19 AM" src="https://github.com/glific/glific/assets/16541548/e21ffe32-6262-4c79-a15b-093c4405c149">

<img width="1050" alt="Screenshot 2023-08-25 at 12 35 22 PM" src="https://github.com/glific/glific/assets/16541548/4b22162d-8cfd-4a78-97b1-f9006cfb082c">

**Comment by mohitgusain** [comment]
@mdshamoon can you also make this mandatory in the frontend
