### ISSUE TITLE
Ticketing System : Assigning multiple people to one support ticket

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3070]
- Sometimes the support team handling tickets will be more than one, in those scenarios when there are multiple people involved in dealing with the same ticket/ when a person who is supposed to handle a ticket is unavailable, having the ability to assign it to multiple parties might something good to have
- Requested by TAP, Nayi Disha

**Comment by mohitgusain** [comment]
@aravind-glific we discussed this issue in our standup and is not making any sense for us. As for there, only one person should be assigned to any ticket. As you can see GitHub issues there is only one assignee in the issue. And if any person is going for leave or somewhere else. He/she can assign that ticket to some other person from the ticketing screen. Attached is a screenshot. Also if there is one more person assigned to any ticket there will be confusion about who is taking care of that issue.

<img width="700" alt="image" src="https://github.com/glific/glific/assets/30264862/845b9898-0a0d-4627-9155-3b83125071c9">

**Comment by AmishaBisht** [comment]
closing this for now, assigne can be changed by anybody , there is no restriction in that will reopen this when we'll get a solid usecase.
