### ISSUE TITLE
Audit item 16 (Not to disclose any internal/absolute path to the end user)

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3077]
The error message that we generate  the server discloses the unnecessary information like the source file path which needs to be removed from the errror.

<img width="697" alt="Screenshot 2023-09-08 at 9 42 01 AM" src="https://github.com/glific/glific/assets/90472056/bfc916c4-eeb5-4a64-8bf1-9b82d7237cd3">

**Comment by dlobo** [comment]
Steps to reproduce:

Create a file: /tmp/ctf with the following contents
```
{
  "operationName": "createTemplateFormMessage",
  "variables" : {
    "messageId": "1091'",
    "templateInput": {
       "label": "Hello",
       "shortcode": "Hello",
       "languageId": "2"
    }
  },
  "query":
     "mutation createTemplateFormMessage($messageId: ID!, $templateInput: MessageToTemplateInput!) {
        createTemplateFormMessage(messageId: $messageId, input: $templateInput) {
          sessionTemplate {
            id
            body
            label
          }
       }
    }"
}
```

Log on to glific and get the authentication token using developer tools. Then run the following command (assuming default install)

```
curl --location 'http://glific.test:4000/api' \
--header 'authorization: AUTH_TOKEN' \
--header 'Content-Type: application/json' \
--data @/tmp/ctf
```
