### ISSUE TITLE
Audit item 22 (Remove the file(s) if they are not required in the web-server)

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3082]
A possible backup file was found on web-server. These files are usually created by developers to backup their work. Remove the file(s) if they are not required.

Backup file is in this path `http://api.staging.tides.coloredcow.com/assets/app.css.gz`

<img width="1258" alt="Screenshot 2023-09-10 at 1 44 12 PM" src="https://github.com/glific/glific/assets/90472056/f638e2bf-34de-4fc3-899c-aadad4991b21">

**Comment by AkhileshNegi** [comment]
Phoenix applications often use a build tool like Webpack or Brunch to compile and bundle JavaScript and CSS files. The ".gz" extension indicates that these files are gzip-compressed versions of your assets, which can improve loading performance. We are using these to have custom color and styling for internal dashboard and these files don't have any sensitive/confidential information
