### ISSUE TITLE
Messages cleanup on a monthly basis 

### ISSUE THREAD

**Issue by dlobo** [glific/glific#3086]
Cleanup the messages table every month, retaining messages for the past 3 months only. Trigger from a cron job or shell script (can do it manually the first few months to get a sense of the errors etc). We should do it on the the first Saturday night of the month

Here are the steps we followed recently

* Delete all messages prior to the retention start date
  * DELETE FROM messages WHERE inserted_at < START_DATE_OF_THREE_MONTHS_AGO
* Delete all messages_media objects prior to the retention start date 
  * DELETE FROM messages_media WHERE inserted_at < START_DATE_OF_THREE_MONTHS_AGO AND is_template_media = false
*  Delete all messages_conversations entries except for the last few days. We are currently NOT using this table, so this will change once we start using the table
   * DELETE FROM messages_conversations WHERE inserted_at < START_DATE_OF_CURRENT_MONTH
* Update the first and last message numbers for all contacts. This is the only operation that we do on a per organization basis (for now). @AkhileshNegi We should script this and add it to the elixir code since it loops through all the organizations in the DB

**Comment by AkhileshNegi** [comment]
We have cleaned up the messages table with the steps mentioned.
Next, we need to add cron to automate these steps
We'll track it in this [issue](https://github.com/glific/glific/issues/3123)
