### ISSUE TITLE
Audit item 9 (Client side bypass / Improper server side validation)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3087]
## Task

Some of the fields are read only in the frontend but can be modified via the APIs. If the fields are read only from the frontend it should be read only from the API as well.

Below are the API that changes the fields which are read only:

**updateContact** - fields: phone, status, bspStatus
**updateTrigger** - fields: All fields except isActive

**Comment by dlobo** [comment]
I think we should introduce two new apis for this and call them

updateContactRestricted
updateTriggerRestricted

which circumvents the above problem, and we ensure that those api's cannot modify the read only fields
