### ISSUE TITLE
HSM templates are not getting imported in Enterprise account - Nudge

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#3094]
**Describe the bug**
Reported by Nudge. The templates are approved in Gusphup but not visible in Glific.
They want the templates to be moved to the PROD account also

Templates:
elexp_rnrpostdemo_tn
elexp_rnrpostdemo_ka

https://discord.com/channels/717975833226248303/1150760932973228164

**Comment by AkhileshNegi** [comment]
Issue note replicable and worked well from Mohit's account and other account. Was working well the next day. Hence, Closing this
