### ISSUE TITLE
Assign role to a new user created in Glific throws error

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#3098]
**Describe the bug**
Reported by KEF
A new user has created her account. When the admin tries to assign a role to the user. It throws error

**To Reproduce**
1. Create an account in Glific
2. Login to Glific with an admin account
3. Go to the Staff management screen
4. Search the user whose account was created in 1st step.
5. Assign any role and click on Save
6. See the error "Does not have access to the user"

**Screenshots**

![errorNewUser](https://github.com/glific/glific/assets/16541548/ddf4c4e2-6286-4815-a1f5-eece84b8ae72)

**Comment by mdshamoon** [comment]
Specifically this error happens when you try to assign a role from none to any other role.
