### ISSUE TITLE
Audit issues not applicable for us

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3104]
Audit item 4 (Unauthenticated APIs): These are gupshup API

Audit Item 6 (Insufficient Anti-Automation): We have rate limiting but we don't have Captcha

Audit item 8 (Cross Origin Resource Sharing (CORS) Misconfiguration): This is a business requirement

Audit item 10 (Improper Implementation of Session Timeout): This is a business requirement

Audit item 12 (Improper Input Validation). Need better security with Gupshup

Audit item 21 (Username and Password field with auto-complete): It is for ease of our users. We should not disable it

**Comment by AkhileshNegi** [comment]
[Audit item 11 (Database Schema Disclosure)](https://github.com/glific/glific/issues/3105)
[ Audit item 22 (Remove the file(s) if they are not required in the web-server)](https://github.com/glific/glific/issues/3082)
