### ISSUE TITLE
Audit item 11 (Database Schema Disclosure)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3105]
On submitting the introspection query in the application url , the application
discloses entire grpahql database schema in the response as shown in the screenshot.

![Image](https://github.com/glific/glific/assets/32592458/ba5ab1da-ab35-404a-bb88-1f87616053bb)

We should disable it for production. Should be allowed on test and local

**Comment by AkhileshNegi** [comment]
This is the GraphQL feature where the entire schema is available to check and we can cherry pick what we need by querying only those fields
