### ISSUE TITLE
Audit item 13 (Application Error Message)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3106]
**Audit Report**
The application is not configured to display any generic error message rather it displays
the application stack Trace details. Application error or warning messages may expose
sensitive information about an application's internal workings to an attacker

**Solution** 
The errors should not  show up the application stack trace and return a graceful error message

**Comment by AkhileshNegi** [comment]
Similar to [this](https://github.com/glific/glific/issues/3077)

**Comment by AkhileshNegi** [comment]
This is fixed as well in the same PR
