### ISSUE TITLE
Audit item 20 (Concurrent Logins Possible)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3110]
This is a choice for the platform.

In this case the recommendation from the audit team is to show the count of other active sessions for the same account once a user logs into the app

**Comment by mdshamoon** [comment]
In the frontend we will show the number of other active sessions along with the IP address from each session.

From the backend perspective we will need an API that gives us the details of the number of active sessions along with their IP addresses.

**Comment by dlobo** [comment]
I think we might want to protest this also. seems like this is a good feature, but not a web security issue

**Comment by dlobo** [comment]
I'll try and write this on the plane tomorrow, is quite easy I think (similar to delete_all_user_sessions)
