### ISSUE TITLE
Mail Dashboard V2

### ISSUE THREAD

**Issue by Darshan2003** [glific/glific#3112]
Currently, for sending graphs in the mail we are using SVG, but Gmail and some other clients don't support SVGs.
- Update the implementation to use PNG instead of SVG

**Comment by AkhileshNegi** [comment]
Based on the last changes the graphs are coming up now but without any labels and legends
<img width="669" alt="image" src="https://github.com/glific/glific/assets/40158831/3ddd0bd6-1d53-418e-ab9b-58352940c8ea">
