### ISSUE TITLE
Ticketing System : Unique User Record

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3126]
- Incoming support issues from the same user contact is treated individually in the current ticketing system
- Bundling all tickets created by a single user will be easier for handling tickets 
- It will help in better segregation and will also enable the NGO to prioritize individuals with high number of queries
- Requested by Nayi Disha

**Comment by AmishaBisht** [comment]
add a filter on the basis of name or phone number of the user who opened the ticket and also there should be a count of tickets raised by that user.

**Comment by mdshamoon** [comment]
@AmishaBisht I am not able to see the filter in the graphQL query for nameOrPhone. I think its not been added in the filter fields. 

When I added that in the backend and searched the query was failing. Can you please check that. 
We can also discuss this on Monday

**Comment by aravind-glific** [comment]
@AmishaBisht Isn't the count of tickets from a particular user not part of ticketing listing page?

**Comment by aravind-glific** [comment]
@AmishaBisht Missing functionality/ unexpected behaviour based on testing that needs to be handled:
1. Count of tickets created by one user is not displayed in Listing Page
2. Searching tickets by body is not working - It should be added along with contact number and name of user

**Comment by mdshamoon** [comment]
@aravind-glific the proposed solution: Showing the number of queries raised by the contact within the ticket row will only create confusion in my opinion. I am marking this up for discussion and we can take this up if we get a better idea to show this segregation.
