### ISSUE TITLE
Flow search is showing duplicate results

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#3132]
**Describe the bug**
Flow search is showing duplicate results

**To Reproduce**
1. Search name of any existing flow in search field in Flows tab

**Expected behavior**
Only 1 result should appear

**Screenshots**
![WhatsApp Image 2023-09-25 at 12 25 07 PM](https://github.com/glific/glific-frontend/assets/122982753/7deb521d-b99f-4d30-a1d3-801da922a436)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AkhileshNegi** [comment]
This was fixed earlier this week in this [issue](https://github.com/glific/glific/issues/3127)
Changes have been deployed as well. Reopen this if issue still persists
