### ISSUE TITLE
Keyword of new created flow are not working

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#3153]
**Describe the bug**
Reported by multiple NGOs, OBLF, ReapBenfit, and Udhayam.
They have created new flows and reported that the keywords of new flows are not working. Keywords are not starting the flow.
Test in CC account and able to replicate the issue. 
https://cc.tides.coloredcow.com/flow/configure/1c7afa3a-fef2-4c82-8228-7dc6e324ae01

**To Reproduce**
1. create a new flow and assign a keyword
2. publish it
3. Send a keyword from whats app to start the flow
4. The flow is not starting.

**Screenshots**

<img width="859" alt="Screenshot 2023-10-19 at 11 48 23 AM" src="https://github.com/glific/glific/assets/16541548/9f11c37a-3d12-40e0-a9ad-5cda23ffece6">
<img width="486" alt="Screenshot 2023-10-19 at 11 47 59 AM" src="https://github.com/glific/glific/assets/16541548/ff6427c2-55cc-45c4-bd8e-67fa7caa2e85">

**Comment by dlobo** [comment]
This was a bug created by a fix we tried to do to resolve the keyword issue, but set us back even more. we reverted that fix, since we know the cause of the issue
