### ISSUE TITLE
Message body and message media caption is different

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3164]
## Task

In case of a media message the frontend shows the caption attribute of the media message.

In case of some of the contacts for TAP the body of the message and the message media caption is different in DB. The body is the actual message sent whereas the message media caption is different which is shown in the UI. Something to do with the optimizations we did for message media

Examples case
Contact id: 1487679
Message id: 49303333

**Comment by AkhileshNegi** [comment]
We'll be using message body since we are using one message media for all messages which same message media
