### ISSUE TITLE
Flag erroneous activity : Automated Flow Tester

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3165]
**Is your feature request related to a problem? Please describe.**
Discrepancies within a flow which is already published & triggered/ send to users should be flagged or notified. 

- HSM template alert : After wait for contact node, if the delay is more or equal to 24hrs, then the subsequent message must be a HSM message. 
- HSM template alert for Triggers : While scheduling a trigger, the flow selected must ideally start with an HSM message, it could be notified to the user while creating a trigger message.

**Additional context**
This is in context of TAP who realized there was an issue with the flow design 3 days after the flow was triggered.

**Comment by AmishaBisht** [comment]
Duplicate issue. Requested feature already built and deployed.
