### ISSUE TITLE
Flow take over popup is shown multiple times even after taking over (and the previous person leaving the flow)

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#3168]
**Describe the bug**
Flow take over popup is shown multiple times even after taking over (and the previous person using the flow leaving the flow). I have got it atleast 5-6 times

**To Reproduce**
1. Try taking over the flow another person is using
2. The other person will be on platform, but not on the flow

**Expected behavior**
After taking over once, the pop-up shouldn't be sent/nudged multiple times

**Screenshots**
<img width="1434" alt="image" src="https://github.com/glific/glific-frontend/assets/122982753/d720dd9c-9104-4a04-be6f-0fd8172abd3f">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by radhikaT4D** [comment]
This seems like a bad experience. Should be prioritized.
