### ISSUE TITLE
Email:low_balance_alert_mail_frequency

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3179]
**Description**
We send alert emails to beneficiaries whenever their Gupshup balance is low. Currently, these emails are sent daily, which is causing disruption and may be overwhelming for the recipients. To address this issue, we want to change the frequency to once in a week.

**Expected behavior**
Beneficiaries should receive email once in a week only.

**Comment by mahajantejas** [comment]
Possible to explain 
- what is the threshold that triggers the low balance emails
- is it possible to add/ update email ids for each of the orgs to make sure right people get the alert? 

You can let me know, if it is possible to add this to the issue?
