### ISSUE TITLE
Error while deleting profile

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3193]
TAP has reported this concern that they are facing error while deleting the profile

**To Reproduce**
1. Go to Glific
2. Click on Chats
3. Search for Swarnadipta Saha
4. Go to View Contact Profile.
5.  Click on Remove - An error will pop up

If we try to delete this contact while login in to the TAP account  Swarnadipta Saha I am  unable to remove it and getting the below error as added in the below screenshot.
I have also tested it on CC the by the same steps facing the same error.
I have observed this is occuring for both multiple and single accounts.
**Screenshots**

https://github.com/glific/glific/assets/143380171/58500a9f-4693-4f32-ba4f-a322ee5b2d68
<img width="1462" alt="image" src="https://github.com/glific/glific/assets/143380171/fbba657b-5966-499c-91b1-ff75785d3e2c">
<img width="1445" alt="image" src="https://github.com/glific/glific/assets/143380171/908bbcff-0773-4174-9d14-4a697022a5b5">
<img width="1466" alt="image" src="https://github.com/glific/glific/assets/143380171/7b584d47-c903-462d-854f-d0e845781617">

**Comment by AmishaBisht** [comment]
This issue was occurring due to the query timeout, so cleaned the database now working fine, so closing the issue.
