### ISSUE TITLE
v0.2 feedback - The sorry message should appear first as per the flow but in the message it shows after

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#321]
The sorry message should appear first as per the flow but in the message it shows after
![image](https://user-images.githubusercontent.com/16714604/88674931-0611e100-d108-11ea-892f-d83ddb115017.png)
![IMG_4E7CFEBE1F23-1](https://user-images.githubusercontent.com/16714604/88674731-cba84400-d107-11ea-9bb5-fd56f0da39e2.jpeg)

**Comment by dlobo** [comment]
Duplicate #322
