### ISSUE TITLE
Enhancement: Manually adding contacts in bulk to new collections (Contact Management) 

### ISSUE THREAD

**Issue by mahajantejas** [glific/glific#3218]
**Problem Statement**
For addition of contacts in bulk to a collection: using the "Contact Management" and uploading a CSV to add the contacts to collection , the CSV contains three fields "Name", "phone no" and "collection" 
problem 1 - It is confusing which name to enter - preferred name or contact.name
problem 2-  whatever name is entered in this CSV and uploaded, the preferred name of the contact changes to become the name as per this sheet.

**To Reproduce**
1. Go to 'contact management'
2. Download the CSV template to upload contacts in a collection
3. it contains the following fields-> "name" , "phone no" and "collection"
4. Upload the csv to complete the addition of bulk contacts to the collection
5. Any name can be added in the names field while uploading the CSV, and the name of the contact changes in the Glific interface. 

Before updating the collection -> Name is "Tejas Mahajan" 
<img width="1046" alt="Screenshot 2023-11-22 at 1 36 56 PM" src="https://github.com/glific/glific/assets/141305477/de155f13-a550-4866-97b7-e99adddab076">

Name entered as "TJ" in the CSV 
<img width="421" alt="Screenshot 2023-11-22 at 1 37 38 PM" src="https://github.com/glific/glific/assets/141305477/34c30563-073f-4f48-8e87-47b6e1ccd347">

Post updating the collection 
<img width="1021" alt="Screenshot 2023-11-22 at 1 38 38 PM" src="https://github.com/glific/glific/assets/141305477/f2c1d4b4-8607-4315-90f5-d0d507900c1b">

<img width="382" alt="Screenshot 2023-11-22 at 1 42 05 PM" src="https://github.com/glific/glific/assets/141305477/8e9ff976-da73-4d85-96e6-ad854eadbfb5">

**Describe the solution you'd like**

Remove the "Name" field from the CSV, and just keep "phone no" and "collection" and if additional parameter is needed "whatsapp id" can be used.

**Comment by dlobo** [comment]
Why remove the name field? what happens if NGOs want to update the name?

I would recommend, we modify it to make:

1. The name column be optional
2. If name column present, and name value empty, dont update name

**Comment by mahajantejas** [comment]
this also works @dlobo

**Comment by mahajantejas** [comment]
@AmishaBisht @dlobo -> after the latest discussion 

1. This issue has been faced when the NGO wants to add contacts to collections, where "Name" field is creating confusion 
2. For adding contacts to a collection, phone no and collection is sufficient information 

To change name, or any other contact field, there already exists the feature to change it: https://glific.github.io/docs/docs/FAQ/Update%20collection%20with%20bulk%20contacts%20or%20contact%20fields/ - see this point 5 onwards. 

Therefore, recommendation is this 
- Remove the "name" field while adding to collection
- To modify "name" or any other contact field, there already exists a template in the documentation shared above, remove the

**Comment by AmishaBisht** [comment]
Duplicate issue
