### ISSUE TITLE
v0.2 feedback - The messages are appearing reversed

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#322]
The messages are appearing reversed
![image](https://user-images.githubusercontent.com/16714604/88668667-8cc2c000-d100-11ea-90e7-23c99844a5b4.png)

**Note from Frontend team**
This might be because the frontend is receiving the subscription updates simultaneously. So it could be possible for some cases & reasons, the frontend is receiving sent messages first and then the received message. I'll look to sort the messages by the timestamp on the frontend side. Even then, it may look weird if an incoming message suddenly shows up in between other messages.

**Comment by dlobo** [comment]
can you do a pull and a "mix setup" to reset things.

I've committed a fix for this
