### ISSUE TITLE
Automated Flow Tester : Flag erroneous activity + Notification

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3223]
- Flag erroneous activity : Discrepancies within a flow which is already published & triggered/ send to users should be flagged or notified
- This is in context of TAP who realized there was an issue with the flow 3 days after the flow was triggered/ program start

**Comment by AkhileshNegi** [comment]
Can you add the discord conversation? Also explain what were the discrepancies and if there wasn't a warning or notification already created

**Comment by aravind-glific** [comment]
- the flow simulator traverses through all the nodes and catches the logical flaws
