### ISSUE TITLE
Automated Flow Tester : Warning - 'Wait for response' node should be present after interactive message

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3227]
Flow not responding - [Quest Alliance](https://discord.com/channels/717975833226248303/1164029264115535943/1164029264115535943)

- The registration flow for QA was not working due to a missing ‘Wait for Response’.
- A logical flow check which identifies missing elements like Wait for Response whenever a user is expected to send a message. This is obvious for interactive messages
- For other messages, we can try to infer from the message (and language) if its a question that is expecting a response (maybe via LLM), this could be a future enhancement

**Comment by AkhileshNegi** [comment]
@aravind-glific can you share the logic how to identify in a flow that `wait-for-response` is missing and what are other logical flow chech that are needed

**Comment by aravind-glific** [comment]
@AkhileshNegi As per the discord conversation we've had, doing it for interactive messages should be a good starting point. Making sure that a 'Wait for response' node is present right after any interactive message. For normal send a message, this might not always be the case.
