### ISSUE TITLE
Automated Flow Tester : Warning - Only default flow updated, update other language flows as well

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3228]
Old version of flow getting triggered for few users - [Discord Support Ticket](https://discord.com/channels/717975833226248303/1163830712240185424/1163830712240185424)

- When an old flow is updated, the default flow as well as other language flows needs to be updated as well.
- Here, the flow malfunctioned because only the default language/ English language flow was updated, but the Hindi language flow was not.

**Comment by AkhileshNegi** [comment]
Can you test this and add steps to replicate the issue as well

**Comment by aravind-glific** [comment]
Closed since this issue is linked with [language alert issue](https://github.com/glific/glific/issues/3241)
