### ISSUE TITLE
v0.2 feedback - On sending optout I didn't receive any message on whatsapp. But on glific the flow continues

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#323]
On sending optout I didn't receive any message on whatapp. But on glific the flow continues
![IMG_823041C4EC58-1](https://user-images.githubusercontent.com/16714604/88675648-c3043d80-d108-11ea-80ae-60f389808cfa.jpeg)
![image](https://user-images.githubusercontent.com/16714604/88675542-a831c900-d108-11ea-8cbf-dada3360ed76.png)

**Comment by dlobo** [comment]
We fixed the "glific output" flow from the help menu

seems like either Gupshup (have sent mail to them) and/or WhatsApp are now intercepting the output keyword and stopping messages from being delivered. We do not get a notification from them on this event, but subsequent message sends are rejected, saying "user has not opted in"

**Comment by dlobo** [comment]
@pankaj-ag , not sure if we handle Gupshup error messages, but we should. You can see one example when you type optout in WhatsApp: {"reason":"User Not Opted In","status":"error"}

lets parse and intercept those error, hence assigning to you :)
