### ISSUE TITLE
Automated Flow Tester : Warning - Flow starts with Wait for Response

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3230]
Flow not getting triggered - [Reap Benefit](https://discord.com/channels/717975833226248303/1164914298561237034)
The flow was not getting triggered since : 
1. Flow started with wait for response instead of send message 
2. ~~The message at the beginning was not HSM template. Checks could be made at flow publish level to avoid these scenarios~~

Solution - To show warning at the time of Publishing whenever either of the 2 scenarios happen

**Comment by AkhileshNegi** [comment]
@aravind-glific both of these depends on how the flows are used and how they are linked with other flows. Like flow can start with session message if it is linked with some other flow or flow has a keyword that triggers it.
Can you do some more research on it

**Comment by aravind-glific** [comment]
@AkhileshNegi Yes, the usage of wait for response node in the beginning might depend on the flow design and modularity. So we could just make sure that flows used inside the Triggers start with an HSM template. But even for this, I think its better to ensure that the first 'send message' node is a template, rather than the first node itself. The first node could still be something else like a check whether the person is registered/ updating a counter or something. Even though in the Triggers I've created until now, this is not the case, I think there might be cases were the first node could be something other than 'Send a message' node.

**Comment by aravind-glific** [comment]
Split into 2 issues

**Comment by mdshamoon** [comment]
@AmishaBisht @aravind-glific got the data for the starting node in a flow for all published flows in production
   "execute_actions" => 5969,
   "not any type" => 7,
   "set_contact_profile" => 1,
   "split_by_contact_field" => 529,
   "split_by_expression" => 231,
   "split_by_groups" => 265,
   "split_by_intent" => 3,
   "split_by_random" => 13,
   "split_by_run_result" => 1,
   "split_by_subflow" => 147,
   "split_by_webhook" => 350,
   "wait_for_response" => 23,
   "wait_for_time" => 12
   
   Out of around 7000 flows there are only 23 that starts with wait for response. Can you make the call based on this if we should add this warning.

**Comment by aravind-glific** [comment]
@mdshamoon I think we can ignore this warning since 23 is not a statistically significant number considering the size of the larger set.

**Comment by AmishaBisht** [comment]
@mdshamoon @aravind-glific Closing this issue for now if any further cases come, then we can look into this issue.
