### ISSUE TITLE
Automated Flow Tester : Warning - Improper Counter Initialization

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3231]
Counter variable not initialized - [OBLF](https://discord.com/channels/717975833226248303/1167335600249110649/1167335600249110649)
The counter variable used for fetching values from a sheet was not initialized and hence the flow was getting stopped abruptly. A check could be built around it - checking whether counters used inside the flows are initialized properly.

**Comment by AkhileshNegi** [comment]
@aravind-glific can you share in a flow how a counter variable can be differentiated from a non-counter variable. Also if you can add some sample flow link or screenshot, that will be helpful to understand the issue better

**Comment by aravind-glific** [comment]
@AkhileshNegi To give you more context on this, this happened in one of OBLF's flows. The counter initialization was handled in the onboarding flow while the counter increments were happening inside a quiz flow. So the flow would break for anyone who came directly to the quiz flow instead of onboarding. Ideally, this shouldn't happen since anyone coming to the bot for the first time should be taken to the onboarding flow someway. 

There is no straightforward way to identify counter variables, but there are few partial workarounds possible :
1. Usage of the keyword counter in the contact variable name - Eventhough I don't personally name counter variables as counter, many people might be doing it. Kind of a straightforward way to identify
2. Any contact field which is undergoing an increment or decrement at any point inside a flow (using custom expression) could be treated as counter variable.

**Comment by AmishaBisht** [comment]
As discussed with the prod team, there is no way to differentiate between the counter variable and normal variable, so closing this.
