### ISSUE TITLE
Flows: GPT Node

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3244]
**Is your feature request related to a problem? Please describe.**
With the introduction of GPT, we can add a node called 'Fetch from GPT.' What this node essentially does is run a user-defined prompt and generate a response. This response can then be used down the flow

This feature can have different applications, such as:
1. Converting user-entered dates into the correct format.
2. Analyzing user responses and taking various actions using `has any of the words`, `has a number`, or other options from the same node

**Support Queries**
[Sakha Consulting Wings](https://discord.com/channels/717975833226248303/1168519231525105745)
[Udhyam](https://discord.com/channels/717975833226248303/1057182365417472000/1061963539025244251)

**Screenshot**
<img width="709" alt="image" src="https://github.com/glific/glific/assets/40158831/c37a28db-65c3-4163-bcd7-7ec1068d2024">

**Comment by mahajantejas** [comment]
@AkhileshNegi 
how will this work? 
the org will need to have a OpenAi APIs right?

**Comment by AkhileshNegi** [comment]
1. We can use same OpenAI keys they enter from setting
<img width="1159" alt="Screenshot 2023-12-05 at 10 51 17 AM" src="https://github.com/glific/glific/assets/40158831/cc1521a9-5982-415a-97ea-1676d168bf08">
2. We keep it simple for first cut and then if requested later on can add
