### ISSUE TITLE
Automated Flow Tester: Long Flows

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3258]
**Is your feature request related to a problem? Please describe.**
While publishing flow we also need to show a warning if the flow is too long. We also came across issue that the translation check fails when the flow is too long in that case we will skip the translation check and show translation check will not work

**Describe the solution you'd like**
Show warning that flow is too long

**Comment by KrishnaDwibhashi2** [comment]
Product team have discussed & decided that 20 (or maximum 25) Nodes would be an ideal number to have in a flow which will help in debugging/ better readability.

There are 2 ways when the error can be shown. Please let us know which one is possible-
1) When x+1 (x being the number we decide upon-20 or 25) node is being created itself (the arrow being pulled), the warning should be shown.
2) When the flow is published, the check will happen

We would prefer method 1 over method 2. But if method 1 is not possible, it would be method 2.
Warning to be shown- The recommended number of nodes for a flow is 25. Exceeding this limit may result in issues during debugging or flow editing. Please consider using the 'Enter another flow' (link documentation if possible) node to create modular flows.

Reconfirming- Right now, we will be showing warnings only- it won't  stop users from creating longer flows.

In future- we would also like to add this as a message in loading screen with others)

**Comment by AkhileshNegi** [comment]
We'll go with route 2 as we cannot restrict them from creating flow with more nodes, it may break existing flow or sometimes flow can have only few additional nodes and for that creating sub flow does not make sense

**Comment by KrishnaDwibhashi2** [comment]
In either of the cases, we are anyways not restricting the org from creating the flow further- we are just giving warning (I would call it a suggestion rather than warning). It will be more effective if they are told at that point itself (route 1) rather than route 2 as somebody who have created a long flow already and then publishing it will not revert back & make flows smaller.
