### ISSUE TITLE
Keyword not triggering flow

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3264]
Reap Benefit and Udhyam have reported the issue that flow is not getting trigger for some particular flow and they are not getting any response back from BOT
However, if we change the keyword and try to trigger the flow it's working fine.

Support Queries
https://discord.com/channels/717975833226248303/1186279380507443242
https://discord.com/channels/717975833226248303/1186307111739736094

**To Reproduce**
1. Go to flow https://reapbenefit.tides.coloredcow.com/flow/configure/80243b01-d3c8-4789-95d6-9af5355f4cda
https://udhyam.tides.coloredcow.com/flow/configure/4ebd693a-69c7-485a-838b-3b89aa031f6e)
2. Type the Keyword "aimentor" for the 1st Flow and helpsbic for the second flow and test this 
3. You will observer no response from the BOT
4. See error ( added screenshot. below )

**Screenshots**
<img width="988" alt="image" src="https://github.com/glific/glific/assets/143380171/f95d8e23-1781-4c0f-92ff-62808747704a">

**Additional context**
Just for FYI, now ORG have changes the keyword and the flow triggered and they got response from BOT.

**Comment by dlobo** [comment]
@SangeetaMishr has this been reported recently with any other NGO or flows?

**Comment by SangeetaMishr** [comment]
@dlobo no only Reap Benefit and Udhyam had raised previously.

**Comment by SangeetaMishr** [comment]
@dlobo @AmishaBisht The keyword issue has come up for an Org names : LAHI today.
Login URL : https://lahilms.glific.com/
Flow Name: Delhi_summer_int
Flow Link : https://lahilms.glific.com/flow/configure/4f6585f0-15a6-4a2e-ae46-94a7f160bae7
Keyword: summerinternship ( is not starting the flow)

Hence I changed the keyword to actions and the flow worked

Screenshots for reference:

**Comment by SangeetaMishr** [comment]
<img width="1080" alt="image" src="https://github.com/glific/glific/assets/143380171/a03a2103-9fca-4089-b73d-26f78e791daa">

**Comment by AmishaBisht** [comment]
Closing this since it has been pending for a long time and we are unable to replicate it

**Comment by SangeetaMishr** [comment]
@AmishaBisht This issue has again come up for the Org Name - Circles of safety 
Flow Name - Cos_GPTintegration_test1  https://cos.glific.com/flow/configure/f96eafce-a7b3-451a-9199-a32ed4634a94
Keyword not working - Askcos
Keyword changes to - Askquestion ( the flow worked)
<img width="854" alt="image" src="https://github.com/glific/glific/assets/143380171/69463162-fce6-4ddd-abb6-37bf886337a1">

**Comment by madclaws** [comment]
We have to inspect the keyword cache, if the keyword is in the cache. This can be inspected in `consumer_worker.ex`. This can be used next time the issue arises again.

**Comment by AmishaBisht** [comment]
If the keyword issue occurs again, we can check the keyword cache. In the case of template flows, the keywords weren't appearing inside the published keyword map, and after cleaning the cache, it worked. So, this might be the case here as well. We can check the keyword cache using the `Glific.Caches.fetch(organization_id, key, fallback_fn)` function. Closing the issue for now. We can reopen it if the issue occurs again.
