### ISSUE TITLE
Collection: Automatic contact addition

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3265]
**Is your feature request related to a problem? Please describe.**
Based on our discussion on competitive analysis, Wati has a feature called slicing as shown below
<img width="972" alt="image" src="https://github.com/glific/glific/assets/40158831/292abad9-2876-421a-a981-72635b75f4b9">
We can incorporate something in a similar line to create a collection where members are added automatically

**Describe the solution you'd like**
In the collection creation screen, add an option to automatically add contacts to this collection based on the contact field value
<img width="522" alt="image" src="https://github.com/glific/glific/assets/40158831/f167617e-ca47-4f42-8a03-25c6313692d5">

**Describe alternatives you've considered**
The alternative can be to create a new collection first and then start the flow for all contacts check this value and add contacts to the collection based on the value

**Comment by mahajantejas** [comment]
@AkhileshNegi  would it be possible to add multiple values with "And" / "or" logic in this way of creating new collections? 

ex - belongs to delhi and is male and speaks hindi - gets added to this collection.
