### ISSUE TITLE
API for creating/updating regx flow

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3297]
## Task

For this [issue](https://github.com/glific/glific-frontend/issues/2628) we need an API from the backend to create/update the regx flow

**Comment by DependerKumarSoni** [comment]
Hi @mdshamoon,
I came across your repository and am intrigued by the issue at hand. Given my past experience with regex and APIs, I believe I can contribute effectively to its resolution. Would you mind assigning this issue to me? Thanks!

**Comment by mdshamoon** [comment]
Hi @DependerKumarSoni do you want start with setting up the repository and then I will assign you the issue. Feel free to ask any questions on our [discord](https://discord.gg/Y6guKhf9qp) channel
