### ISSUE TITLE
Automated flow tester: Translation alert giving unnecessary warnings

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3314]
**Describe the bug**
While publishing the flow, translation warnings are appearing even when no nodes are translated. This issue specifically occurring  for Hindi language only , even when other default languages are present. Typically, this checks if any node is missing translation and if yes then it shows the translation warning. However, in the current scenario, the warning is being triggered even when there are no translations available.

<img width="1161" alt="Screenshot 2024-01-29 at 7 08 36 PM" src="https://github.com/glific/glific/assets/90472056/bfa76bd9-ffcf-45b6-a933-44d58790173d">

**steps to replicate**
1. login to cc tides
2. open this flow in flow editor [flow](https://cc.tides.coloredcow.com/flow/configure/397674b4-86a7-4b4e-87e9-7ec3b61e1de8) 
3. publish the flow

**Comment by AkhileshNegi** [comment]
@AmishaBisht Can you add clear steps from the start to replicate this error

**Comment by AmishaBisht** [comment]
sure
