### ISSUE TITLE
Feature: Whatsapp Groups

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3320]
**Is your feature request related to a problem? Please describe.**
As WABA doesn't provide the support for whatsapp groups to address that we have launched collections that works like a group in glific but it is requested from many ngo that they need whatsapp group support in glific so we are planning to Integrating the personal [whatsapp groups](https://docs.google.com/document/d/178rJWdOCnAueVqaIylVmCCQJ_F3Bjf7jWVjzrH8d1hA/edit) with glific, through this we'll keep record of the whatsap groups as well. Glific staff should be able to receive all the message and also able to manually send messages via interface.

**Describe the solution you'd like**

- [x] https://github.com/glific/glific/issues/3322
- [x] https://github.com/glific/glific/issues/3323
- [x] https://github.com/glific/glific/issues/3341
- [x] https://github.com/glific/glific/issues/3373
- [x] https://github.com/glific/glific/issues/3380
- [x] https://github.com/glific/glific/issues/3343
- [x] https://github.com/glific/glific/issues/3383
- [x] https://github.com/glific/glific/issues/3342
- [x] https://github.com/glific/glific/issues/3386
- [x] https://github.com/glific/glific/issues/3377
- [x] https://github.com/glific/glific/issues/3344
- [x] https://github.com/glific/glific/issues/3401
- [x] https://github.com/glific/glific/issues/3391
- [x] https://github.com/glific/glific/issues/3402
- [x] https://github.com/glific/glific/issues/3361
- [x] https://github.com/glific/glific/issues/3376
- [x] https://github.com/glific/glific/issues/3411
- [x] https://github.com/glific/glific/issues/3420
- [x] https://github.com/glific/glific/issues/3422
- [x] https://github.com/glific/glific/issues/3360
- [x] https://github.com/glific/glific/issues/3379
- [x] https://github.com/glific/glific/issues/3392
- [x] https://github.com/glific/glific-frontend/issues/2747
- [x] https://github.com/glific/glific/issues/3427
- [x] https://github.com/glific/glific/issues/3419
- [x] https://github.com/glific/glific/issues/3418
- [x] https://github.com/glific/glific/issues/3454
- [x] https://github.com/glific/glific/issues/3458
- [x] https://github.com/glific/glific/issues/3459
- [x] https://github.com/glific/glific/issues/3462
- [x] https://github.com/glific/glific/issues/3470

**Comment by AkhileshNegi** [comment]
Closing Master issue and tracking rest good to have here
https://github.com/glific/glific/issues/3494
