### ISSUE TITLE
Unable to check the chat history for a particular contact | Nayi Disha

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3329]
Nayi Disha Org has raised this that a particluar contact named - Sravani with contact details - +96896227169 chat is not visible on the chat window/ chat history. As per their records this person has contacted their BOT on Jan 27, 2024.

**To Reproduce**
1. Go to https://ndrcsupport.tides.coloredcow.com/chat/846886
2. Search for the contact name or number as shared above
3. See error ( No messages is present)

We can see the chat history for other contacts but not for this particular contact.

**Screenshots**
<img width="1128" alt="image" src="https://github.com/glific/glific/assets/143380171/8a565dae-5488-40fe-90ab-6d44600ea744">

Discord Query - https://discord.com/channels/717975833226248303/1202845031216586772/1202845031216586772

**Comment by AkhileshNegi** [comment]
Closing this as we have not heard from them for some time
