### ISSUE TITLE
Auto Translate: Success Metrics

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3339]
**Is your feature request related to a problem? Please describe.**
While Auto Translate is deployed in production and currently is in beta version, we should have few success metrics to measure hits/misses of feature

**Describe alternatives you've considered**
Add metric in [tracker](https://discord.com/channels/717975833226248303/1143964157071327272)

**Comment by mahajantejas** [comment]
Some throught: 

without spending any development effort: we can define the success metrics as follows 
1. Steady usage on the translate APIs (openAI as well as google translate) - this we can get from the openAI platform, i am not sure about the google translate api

With some development effort - if we track the following
1. Use of auto translate 
3. Export with translate
4. Export without translate
5. Import translations

To get a sense of what is working and which one are the users finding it more useful.

After one month of deployment, we will also reach out to the NGOs who are using it, with a simple survey 
1. Rating on usage (1-3) 
2. Rating on accuracy of translation (1-3) 
3. Any other feedback
