### ISSUE TITLE
Error while trying to set up the glific backend in Ubuntu

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#334]
I was trying to setup Glific on my local by following the instructions mentioned in the readme.
After running the command(`mix setup`), I have got the following errors in terminal:

**Error in terminal:**
1. could not compile dependency :earmark_parser, "mix compile" failed. You can recompile this dependency with "mix deps.compile earmark_parser", update it with "mix deps.update earmark_parser" or clean it with "mix deps.clean earmark_parser"
==> glific
** (Mix) Could not compile "src/link_text_parser.yrl" because the application "parsetools" could not be found. This may happen if your package manager broke Erlang into multiple packages and may be fixed by installing the missing "erlang-dev" and "erlang-parsetools" packages

2. [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.

**Solution:**
I used the following command to install it
1. apt-get install erlang
2. apt-get install inotify-tools

May be we can add this as part of installation instructions.

**Steps to reproduce the behavior:**
1. Go to glific folder
2. Run `mix setup`

**Screenshots for reference:**
![Screenshot from 2020-07-30 16-06-161](https://user-images.githubusercontent.com/26589967/88929986-7c454d80-d298-11ea-85c5-c5601d688547.png)

![Screenshot from 2020-07-30 16-16-29](https://user-images.githubusercontent.com/26589967/88929989-7d767a80-d298-11ea-910f-006df940e11d.png)

**Desktop:**
 - OS: Ubuntu 18.04.3 LTS

**Comment by dlobo** [comment]
is the error fixed after you installed inotify-tools?

Thanx for the report and bug fix. Once confirmed, I'll add to readme

**Comment by DigneshGujarathi** [comment]
> is the error fixed after you installed inotify-tools?
> 
Yes

**Comment by dlobo** [comment]
I updated the readme for the backend. thanx for the report
