### ISSUE TITLE
Auto Translate: Adding logs

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3340]
**Is your feature request related to a problem? Please describe.**
To have a better understanding of feature usage and the accuracy of translation, storing logs of translation in the table. The table should include things like `source text`, `source language`, `destination language`, `translated text` and `success or failed`
This way we can take export of same and do analytics manually

**Comment by mahajantejas** [comment]
Is it possible to also get logs of usage - 

1. Use of auto translate 
3. Export with translate
4. Export without translate
5. Import translations

To get a sense of what is working and which one are the users are using more?
