### ISSUE TITLE
Search query giving empty results for OBLF account

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3374]
**Is your feature request related to a problem? Please describe.**
Search query giving empty results for OBLF account. Organization id 109. This issue is happening intermittently and not replicable at all times

**Describe the solution you'd like**
It should get back with a list of contacts and messages

**Comment by AkhileshNegi** [comment]
Closing this as performance is bit better after cleaning up database. For long-term fix we are tracking [here](https://github.com/glific/glific/issues/3123)
