### ISSUE TITLE
Enable logs for GCS bucket by default for a new organization

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3394]
**Is your feature request related to a problem? Please describe.**
Want to identify download rate for a media sent on Whatsapp through the bot

**Describe the solution you'd like**
We can enable logs for a GCS bucket which gives us the usage details of that particular bucket https://cloud.google.com/storage/docs/access-logs#command-line

**Comment by mahajantejas** [comment]
I think this is good to have, we should enable for all orgs
