### ISSUE TITLE
A POP message in the login interface

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3395]
Right now lot of queries come up for how to login so the  first interaction with BOT and then creating account is missed by alot of new org.

Requesting if we can have a pop short message in the login page so that they can read and understand they have to 1st interact with the BOT before creating account.

<img width="564" alt="image" src="https://github.com/glific/glific-frontend/assets/143380171/ede239bf-3e79-4e82-a48e-48f9f5096214">

**Comment by AmishaBisht** [comment]
closing this issue since this is already implemented in Glific
