### ISSUE TITLE
Enhancement: Add profile indexes in bigquery

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3409]
**Is your feature request related to a problem? Please describe.**
In multi proflles feature:

When switching a profile we need to provide the index of that profile in the flow, which we usually get using list_profiles in the flow. This can be done easily if a person is switching profile through their whatsapp

Tap's usecase:

Update the contact profiles without the interference from the user, through google sheets and running a background flow.
They will need the profile index to switch the profiles and then update the contact field for that profile.

**Comment by mahajantejas** [comment]
right now we have update contact with csv, we should extend same to update profile with csv

**Comment by AkhileshNegi** [comment]
not a priority for now
