### ISSUE TITLE
WA Groups: We should hide DMs from groups list

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3418]
**Describe the bug**
If we send a DM to the number added in the Maytapi account it shows up in the group list. 

**To Reproduce**
1. Go to WhatsApp group chats
2. Send a DM to the maytapi number.
3. It shows up in the group list

**Expected behavior**
DM's should have a separate place in the UI and not to be merged with groups

**Screenshots**
![image](https://github.com/glific/glific/assets/32592458/3d22c2ec-2d73-473b-b956-69711f10275a)

**Comment by mahajantejas** [comment]
can you pause on this? it will be good to know what Avanti Fellows think of this? @mdshamoon and we can decide based on the feedback.

**Comment by AkhileshNegi** [comment]
@mahajantejas We'll add this in separate tab like Whatsapp Linked Number DMs, right now it is coming under Whatsapp Groups
