### ISSUE TITLE
Not able to send a message from simulator

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3426]
**Describe the bug**
Error while sending a message from Simulator

**To Reproduce**
1. Go to Chats
2. Open simulator and send a message
3. See error

**Expected behavior**
There should be no error

**Screenshots**
<img width="362" alt="image" src="https://github.com/glific/glific/assets/32592458/3b5269dd-4e6d-41c3-8690-fa2ebaed3433">

**Comment by AkhileshNegi** [comment]
issue was specific to single machine. Resolved for now
