### ISSUE TITLE
Introduce a conversation level flag that determines if message could be sent or not

### ISSUE THREAD

**Issue by kurund** [glific/glific#344]
**Is your feature request related to a problem? Please describe.**
* We need should alert the user that message cannot be sent in a nicer manner

**Describe the solution you'd like**
* It would great if we could have a flag at contact level that tells frontend if a message could be sent or not. 

**Describe alternatives you've considered**
* Doing this at the frontend might be trickly due to timezone issues etc.

**Comment by dlobo** [comment]
This is a bit hard since this changes every 24 hours, but we have to do it. I think for each set of contacts we send up, we also add a field for whether we can send a session message and/or an hsm message

**Comment by dlobo** [comment]
Duplicate #364 which is now moved into the contact object and sent as part of the conversation API
