### ISSUE TITLE
Collection to be updated in flow, when collection name is renamed

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#3440]
**Is your feature request related to a problem? Please describe.**
If collection name is renamed in the "Collections tab" and if it is not removed and re added in the flow, the flow doesn't work as desired. Recently, Nayi disha faced this issue in 2 of their flows

**Describe the solution you'd like**
Whenever collection name is updated in "Collections tab", the flow should be automatically synced with it (similar to interactive messages getting updated even when changes are made)

**Describe alternatives you've considered**
Shamoon suggested to remove the option of renaming in collections, which I do not think should be a solution, as organizations rename their collections when year changes, or batch changes. So that option of renaming should be there for sure.

**Comment by AmishaBisht** [comment]
<img width="781" alt="Screenshot 2024-04-16 at 8 20 27 PM" src="https://github.com/glific/glific/assets/90472056/55d81551-c688-4ab4-a5d0-5fdf8f3ca389">
@mdshamoon we are getting group_ids inside the argument in the flow revision

**Comment by mdshamoon** [comment]
> <img alt="Screenshot 2024-04-16 at 8 20 27 PM" width="781" src="https://private-user-images.githubusercontent.com/90472056/322891206-55d81551-c688-4ab4-a5d0-5fdf8f3ca389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzk1NTAsIm5iZiI6MTcxMzI3OTI1MCwicGF0aCI6Ii85MDQ3MjA1Ni8zMjI4OTEyMDYtNTVkODE1NTEtYzY4OC00YWI0LWE1ZDAtNWZkZjhmM2NhMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE0NTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYjFlYzAxZDhkZDgzMDcyYzdkMDI2ZDMyZjkxODVmNmEzNTQ5NDNjMjc3ZGY0NDc5ODliNzIyZmE4MjFhYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tj-qNl-ORQ6GYEKbEWtgS1dLqd8eoDX-iDSz-oVeBYw"> @mdshamoon we are getting group_ids inside the argument in the flow revision

We are getting the id's of the collection in the flow context but we are not using it while matching in split by collection. We should use id's to match the collection rather than the name because name can be changed.
