### ISSUE TITLE
Migrate bigquery data from old cc account number to new prod number

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#3463]
**Is your feature request related to a problem? Please describe.**

Our v5 dashboard and stats dashboard are connected to the old number's bigquery account and new changees are not getting reflected on the dashboard. We should migrate the data from the old number to the new number

**Comment by mahajantejas** [comment]
stats dashboard: https://lookerstudio.google.com/u/0/reporting/05bfe737-eabf-413b-95fb-181a08d75347/page/O1J5B
