### ISSUE TITLE
At counter themessage can be seen on Glific but doesn't reflect on WA

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3510]
OBLF has raised this issue that for a particular flow atcounter 1601, the message were seen on Glific but it was notreflecting on WhatsApp

**To Reproduce**
2. Click on Flow- Quiz Content Flow_UI
3. Scroll down to create  counter

**Expected behavior**
The content creator had exceeded 20 characters in two out of three options for the question at counter 1601 which is why the user wasn't getting the messages but the flow was running in the background. Editing the options to be 20 or under 20 characters and resynced the content sheet worked.

**Additional context**
Discord Link - https://discord.com/channels/717975833226248303/1229702377972563990

**Comment by mahajantejas** [comment]
linked to https://github.com/glific/glific/issues/3518
