### ISSUE TITLE
GCS: GCS url is missing for the inbound flow 

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3539]
**Describe the bug**

When we send any media in Glific(inboud messages), it gets synced to GCS. After the media syncs there, the **gcs_url** column is populated in the **message_media** table, where the GCS URLs of the media are stored. However, in some cases, the GCS URLs are  getting skipped during the sync, possibly due to timeouts or other reasons.
Here is the support ticket raised by the NGO: [Discord thread](https://discord.com/channels/717975833226248303/1234497345488556113/1234497345488556113)

**Expected behaviour**
When media is sent in Glific, it should be synced to GCS without any omissions.

**Comment by madclaws** [comment]
Args
```elixir
%{
  "media" => %{
    "contact_id" => 859295,
    "flow_id" => 0,
    "id" => 6735247,
    "organization_id" => 70,
    "type" => "video",
    "url" => "https://filemanager.gupshup.io/wa/ad93a470-3c97-4c7d-b9b9-3162ad9a8110/wa/media/08975e51-31e7-4fa0-8f5d-72f30adc7173?download=false"
  }
}
```

Error
```
** (Oban.PerformError) Glific.GCS.GcsWorker failed with {:discard, "GCSWORKER: GCS Upload failed for org_id: 70, media_id: 6735247, error: {:error, :closed}"}
```
@AmishaBisht The oban error we discussed in weekly monitoring report
