### ISSUE TITLE
Alerts for tier messaging limits

### ISSUE THREAD

**Issue by nairabhishek73** [glific/glific#3541]
**Is your feature request related to a problem? Please describe.**
If we mistakenly start a flow for >1000 contacts and the org is in tier 1(can send to 1k contacts only) then the flow starts and errors will pile up, leading to automatic suspension of the Glific account for a day. This can create trouble for the NGOs plans and program.

**Describe the solution you'd like**
Eliminate human error on Glific by building in an alert/block on Glific based on the tier the NGO is in. 
1) Alert if they hit the threshold of contacts reached in the tier.
2) Alert if they are starting a flow for more contacts than their tier allows. Similarly if a trigger is set for a collection that has more contacts than the tier allows.

**Describe alternatives you've considered**
The only other alternative I can think of is to ensure everyone is well informed before getting onto Glific, but there's not guarantee with this.

**Additional context**
This problem has happened with Armman's program where 4k contacts started a flow via trigger. Then the account got suspended. Now their message schedule is off and needs manual intervention. I believe it has happened twice before with 2 other orgs.

**Comment by KrishnaDwibhashi2** [comment]
@amisha-  We need it in 2 places- Trigger, Collections tab
It should calculate the messages scheduled/ sent to the total number of contacts in a particular day
Error message should be popped up when trigger is being set or start a flow is being clicked for collections.


**Error message when starting flow-** You are crossing your daily messaging limit of x contacts as per your tier category (tier-y). Hence, you won't be able to send this flow to the collection. You can read more about this here (hyperlinked- https://developers.facebook.com/docs/whatsapp/messaging-limits)
Please reach out to Glific team if you have further queries


**Error message when setting up trigger-** You are crossing your daily messaging limit of x contacts as per your tier category (tier-y). Hence, you won't be able to set up this trigger. You can read more about this here (hyperlinked- https://developers.facebook.com/docs/whatsapp/messaging-limits)
Please reach out to Glific team if you have further queries

**Comment by AmishaBisht** [comment]
Hey, @KrishnaDwibhashi2 , we can do this in steps. In the first step, we can only show on the trigger and collection level. For instance, while creating a trigger, we can check how many contacts are in the collections. Here, we won't count the previous contacts; we'll only count the contacts for that particular trigger at that time. The same goes for the collection. Otherwise, it'll be complicated. Not exactly complicated, but there could be a lot of edge cases, like if I schedule a trigger before a week or before a month. Plus, I think there are not a lot of use cases for this. Therefore, the warning on the trigger and collection level would be enough. Let me know what you think.

cc @dlobo @AkhileshNegi

**Comment by KrishnaDwibhashi2** [comment]
@AmishaBisht Per trigger/ Per collection alert would solve one part of the problem (if the collection/trigger itself is exceeding the limit), but not solve the entire (or the bigger) problem. 

I didn't understand your edge case. If I had set a trigger for today a month back, while you are checking the count (say while I am setting up one more trigger today), you will check overall how many contacts I intend to reach out (via triggers set for today) and accordingly throw alert right? Or am i missing something? We can discuss further if you want.

What would be effort difference for both the implementations (per trigger/ collection level alert vs overall)? Based on that we can take a call
