### ISSUE TITLE
Autotranslate: latest translations not getting added to a node if the content is already present

### ISSUE THREAD

**Issue by mahajantejas** [glific/glific#3557]
**Describe the bug**
For an already translated flow, performing automatic translations after the default flow is changed, does not change the translations in the language nodes. 

**To Reproduce**
1. Go to flow: https://prod.glific.com/flow/configure/b5fc3b07-26dd-4016-9333-7de91eb96f64
2. Click on 'more' -> translate -> automatic translation
3. after the translations happen, change the content in the default language flow
4. click on automatic translation again
5. Observe that the content in the other languge node does not change. 
6. Now clear one of the language nodes and publish the flow
7. Repeat the steps 4-5, only the cleared node is updated with the latest content in the default flow

**Expected behavior**
Whenever automatic translation or export with auto translate operation is being performed, (even if the content is present in the language nodes, the translations should be overwritten) 

**Additional context**
The translations were probably not being overwritten because when GPT models were used as a translation engine, it took multiple api calls to complete the translation, in which case, of the language node had content, that node was skipped. After changing over the translation engine to google translate, api time out is no longer an issue. So the functionality can be changed.

**Comment by mahajantejas** [comment]
After discussion it was decided that if the default language has content present, then do not overwrite the translations. So if that means that this issue will be closed, then go ahead and mark it closed.

**Comment by mahajantejas** [comment]
hi @madclaws, re-opening this ticket, after an internal discussion. 

This is the proposed solution: Provide a pop up on clicking auto-translate: 

"Please Note: Auto translate only adds translation in languages nodes which are empty.  To get the latest translations of updated content in your default language flow, please clear the nodes in the language nodes"

**Comment by madclaws** [comment]
@mahajantejas Closing this issue since have created an [issue](https://github.com/glific/glific-frontend/issues/2930) on frontend to fix this.
