### ISSUE TITLE
Invalid data causing functionClause error

### ISSUE THREAD

**Issue by madclaws** [glific/glific#3568]
**Describe the bug**
`Map.get/3` expects a map as the first argument, but here we are getting `String`, due to that FunctionClause error occurs.

**Reference**
https://appsignal.com/project-tech4dev/sites/5f480c425ac13f7330101f30/exceptions/incidents/2/samples/5f480c425ac13f7330101f30-712440005729124570617164437001

**Expected behavior**
Ideally we should validate that the data should be a map

**Comment by AkhileshNegi** [comment]
I checked logs but not enough information to investigate the issue or replicate it. There have been 14 instances of error in last 30 days so very low
