### ISSUE TITLE
Organization: Default organization flow

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3701]
**Describe the bug**
While setting up a new organization, by default in the organization flow screen the `new contact` flow is active without a flow being selected. This results in the `new contact` flow trying to get triggered and since no flow-id is there it results in nothing getting triggered and no response from the bot

**Expected behavior**
By default, the  `new contact` flow should be inactive

**Comment by Monalmos** [comment]
Project

**Comment by Monalmos** [comment]
C#

**Comment by AkhileshNegi** [comment]
I think this was the default flow which is active in fresh NGO setup


![Image](https://github.com/user-attachments/assets/44224d1f-78e0-4bb7-8f10-f482dc753466)
