### ISSUE TITLE
Flows: Omiting keywords for template flows

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3702]
**Is your feature request related to a problem? Please describe.**
Right now, we have set template flows for each organization, which blocks a few flow names and keywords
Since these flows are not accessible, NGOs can neither delete them nor edit them. So if a beneficiary uses one of these reserved keywords, it triggers the linked flow automatically.

Here's the list of flows
![template](https://github.com/user-attachments/assets/7a56944a-a656-46ee-9753-9a0fdbea0512)

The keyword is assigned to these flows so NGOs can test them in the simulator before creating flows from these template flows

**Describe the solution you'd like**
1. Find an alternative to start these template flows
2. Remove keywords

**Comment by madclaws** [comment]
We need to remove the template flow keywords from backend.
