### ISSUE TITLE
 A check validation for not allowing any markdown for row validation in Interactive Message

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3730]
**Describe the bug**

This issue was noticed for KEF when they raised on Ngo- support at specific interactive message node the flow was getting stuck.

**To Reproduce**

1. Go to Flow name and link - Help Flow 24-25 - https://kef.glific.com/flow/configure/dfdecac5-e726-4818-80a6-03032e5a8984
2. You will find the keyword `q` send it to the KEF BOT number 
3. The interactive message node 2bde  was getting stuck https://kef.glific.com/interactive-message/13744/edit
4. Added screenshots below where you can see the Error

Discord : https://discord.com/channels/717975833226248303/1272487852772687933

PS: this error has been rectified now as we shared this doc and the Org rechecked and modified the interactive message and saved https://www.markdownguide.org/basic-syntax/

**Expected behavior**
Can we have a validation or check which throws an error or red mark alert if their is any markdown is not added in the row description in Interactive Message

**Screenshots**
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/e6916c83-1704-4007-be6f-876343c9ece6">
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/64beb274-f62e-48ca-9c21-ae3581d4a0e0"/>

**Comment by AmishaBisht** [comment]
When we add Markdown characters like bold and italic, the interactive message is not being sent to WhatsApp
