### ISSUE TITLE
Automate to Enable the Message Events in Gupshup 

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3731]
**Is your feature request related to a problem? Please describe.**

Logged this ticket as per our discussion with Suraj from Gupshup and Akhilesh, on enabling the message events through the API.

Currently, we either ask organizations to handle it themselves or assist them during onboarding calls. Since this is a manual effort, there's a high risk of forgetting or missing steps.

**Describe the solution you'd like**

If we can achieve it through API and once the Glific Account is created as the callback URL is set if we can enable the message events as well

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/d5995695-77f2-4a22-ba2c-a283265dc185">

**Comment by madclaws** [comment]
@SangeetaMishr There's already a ticker for this [here](https://github.com/glific/glific/pull/3632) and its already done. Will be included in the next deployment (next week). FYI.

**Comment by AkhileshNegi** [comment]
Duplicate ticket
https://github.com/glific/glific/issues/3506
