### ISSUE TITLE
v5 Dashboard template: masking the phone numbers

### ISSUE THREAD

**Issue by gtmpt4d** [glific/glific#3732]
**Is your feature request related to a problem? Please describe.**
1. We have a demo v5 dashboard which is not pulling up data. This is affecting demos
2. It has a field in all tables called phone number which we'd like to remove

**Describe the solution you'd like**
1. reconnect it to the prod bot's big query table
2. replace the field phone number in all tables on all pages with wa_id

**Describe alternatives you've considered**
NA

**Additional context**
NA

@madclaws please treat as P0 request as suggested by @radhikaT4D . FYI @AkhileshNegi

**Comment by mahajantejas** [comment]
solution discussed: devs will mask the phone numbers in the V5 template dashboard, and provide the steps in the documentation on how to enable seeing the phone numbers.

**Comment by AmishaBisht** [comment]
Updated the Glific V5 dashboard with masked phone numbers.
