### ISSUE TITLE
Validation of createSavedSearch

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#383]
The createSavedSearch validation should be for shortcode, not a label. Now, if we save data with the same label, it gives an error of validation for a label that says "has already been taken".

**Steps to reproduce the behavior:**
createSavedSearch with the same label.

**Comment by pankaj-ag** [comment]
@DigneshGujarathi can you share a use case where we need to creat two saved search with same label.
Also, how will the user differentiate between two saved search from the drop down.

Let me know if I am missing something here.

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi can you share a use case where we need to create two saved search with same label.
> Also, how will the user differentiate between these two saved search from the drop down.
> 
> Let me know if I am missing something here.

@pankaj-ag A label is mapped against the description & description is a free form text field, so a user can add a description for creating a collection. As per discussion with @kurund we don't need it as a unique.

**Comment by pankaj-ag** [comment]
@DigneshGujarathi @kurund I have removed the constraint. Have a look now.
