### ISSUE TITLE
Flows:  Template flows are showing up in active flows

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3840]
**Describe the bug**
Some flows are appearing in both the active and template flows, but they should only appear in one of these. Because the template flows are showing up as active, users can delete template flows, which shouldn't be allowed.

Additionally, the filters are not working correctly. The search function returns different results when searching with capital letters compared to lowercase letters.

Steps to Reproduce:

1. Search for "Help workflow" in production; it appears in both active and template flows.
2. In the flows search, type "help." It returns 15 results, including the "Help workflow."
3. Now type "Help." It returns 14 results, excluding the "Help workflow."

<img width="1200" alt="Screenshot 2024-09-12 at 12 23 30 PM" src="https://github.com/user-attachments/assets/d06ef895-d6ab-48ca-9912-f73ac52abbee">
<img width="1179" alt="Screenshot 2024-09-12 at 12 24 46 PM" src="https://github.com/user-attachments/assets/a02cbb4f-3c17-4c04-ae77-1088aefacf21">

**Additional context**
is_template column is false for Help workflow in database
<img width="1299" alt="Screenshot 2024-09-12 at 12 29 41 PM" src="https://github.com/user-attachments/assets/7adc3a80-e1e5-4879-9465-16d1095da34b">

**Expected behaviour**
Template flows should appear only in the template section, and active flows should be in the active section; a flow cannot appear in both. Additionally, filters should work properly.

**Comment by KrishnaDwibhashi2** [comment]
@akanshaaa19 Adding to the above pointers,
- If the flow in Active gets deleted, Template flows also get deleted
-If a flow with same name exists in Active flows already, then the active flow is not seen on UI- Only template flows are seen.

**Comment by akanshaaa19** [comment]
On further investigating it was found that the filters in `flows` api are not working as expected if `name_or_keyword` filter is used

If we search for anything in inactive flows all flows (active and template) are returned:
![image](https://github.com/user-attachments/assets/6877ad65-057c-412b-8d16-6cb945908fbf)

payload:
![image](https://github.com/user-attachments/assets/969ba0c0-b5a9-40f4-a5ad-63e8a21d5513)

response:
here isActive: true flows are also returned which should not happen
![image](https://github.com/user-attachments/assets/4163b7da-1ae2-44cd-8e44-95cc9ad77466)
