### ISSUE TITLE
HSM Message | Error

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3876]
**Describe the bug**
Practez ( TAP) Mentorme had raised this query each time he creates temaplet message from existing template message the erro pops up `Couldn't submit for approval: Template Already exists with same namespace and elementName and languageCode`

**To Reproduce**
1. Go to https://practez.glific.com
2. Click on  template message 
3. Go to this template message https://practez.glific.com/template/441691/edit
4. Make a new template message for Hindi Language 
नमस्ते {{1}}!

हमारे पास एक महत्वपूर्ण {{2}} 
{{3}}
<img width="652" alt="image" src="https://github.com/user-attachments/assets/8bb18bc6-c742-4293-8700-83c84c77efc9">

When you add all these you will get the an error message while submitting.

**Expected behavior**
The template with the same message is in a rejected state, yet it still won’t allow me to create the same template message. I have also tried using a different title.

**Screenshots**
<img width="893" alt="image" src="https://github.com/user-attachments/assets/01e06278-ad66-4736-94a7-bf3afa9f718c">

https://practez.glific.com/template/444356/edit ( Rejected template message)

**Comment by AkhileshNegi** [comment]
That is the expected behaviour. If the template is in the rejected state, then from UI one can delete it and then it will delete from Gupshup also. One can only apply a template with the same name and language code thus even if it is rejected the same is still taken
