### ISSUE TITLE
Wa groups: Sync api is not working

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3882]
**Describe the bug**
When any changes are made in WhatsApp groups through the WhatsApp app, we need to reflect those changes in the Glific platform using the sync API. However, an org reported that the sync function is not working; when they click on "Sync," the changes are not reflected in Glific. We need to fix the sync API to resolve this issue.

Discord query: https://discord.com/channels/717975833226248303/1295997528856199168 

We do the same sync while adding credentials. But if the there are huge number of contacts to sync, the api gets timeout on FE. Maybe we should do the sync as a background job and show it in Notifications once its done?, @AkhileshNegi @AmishaBisht

**Comment by madclaws** [comment]
We do the same sync while adding credentials. But if the there are huge number of contacts to sync, the api gets timeout on FE. Maybe we should do the sync as a background job and show it in Notifications once its done?, @AkhileshNegi @AmishaBisht
