### ISSUE TITLE
GCS: Files are not getting synced with gcs

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific#3888]
**Describe the bug**
For LAHI, the files are syncing with GCS, but their GCS is active on Glific

**Comment by AkhileshNegi** [comment]
This is the status of organizations and unsynced files as of 5th Dec 9PM IST
<img width="819" alt="image" src="https://github.com/user-attachments/assets/6fbfdac3-94c3-46c3-9b4f-35a0f0a1649e">

**Comment by AmishaBisht** [comment]
For LAHI (Lighthouse), there is no synced file out of 427.

**Comment by AkhileshNegi** [comment]
This is the status of organizations and unsynced files as of 11th Dec 11:30AM IST

<img width="828" alt="image" src="https://github.com/user-attachments/assets/2d7cdeb7-a3ff-47b8-9366-decef4226eb0">


**By checking their credentials we are getting this error while saving same credentials**


<img width="1150" alt="image" src="https://github.com/user-attachments/assets/fecc2342-ad1d-4f55-b85e-5cc7ad2c0275">

**Comment by AkhileshNegi** [comment]
Closing this as credentials are invalid and support team will reach out to them
