### ISSUE TITLE
1024 character Limit exceed for Send Message node

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3925]
**Describe the bug**
Nayi Disha raised a query regarding a user who received a send message,node  but it encountered an error due to the 1024-character limit.

**To Reproduce**
1. Go to chats
2. Click on contact id - https://ndrcsupport.glific.com/chat/2254130
3. Scroll up to date 4th Nov 2024  and time 22:30 

Flow :https://ndrcsupport.glific.com/flow/configure/c40b0919-7afa-4995-b9d1-03f6e8f42802

**Screenshots**
<img width="770" alt="image" src="https://github.com/user-attachments/assets/8a78406f-18c4-46bb-9e49-bbf3d78fdd8f" />

We should display an error indicating that the 1024-character limit has been exceeded for the send message node.

PS : The issue is not replicable now, I exported the flow and imported it on Prod and tested for myself and it got sent to me without any error message https://prod.glific.com/flow/configure/c40b0919-7afa-4995-b9d1-03f6e8f42802

**Comment by SangeetaMishr** [comment]
@AmishaBisht  Do we have any error notified to NGOs on glific send message node to make them aware ? The error comes after sending message to the user.

**Comment by AmishaBisht** [comment]
Not reproducible
