### ISSUE TITLE
Improving the search functionality in Support Tickets to make it easier

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific#3931]
**Describe the bug**
Nayi Disha had raised this query that they are unable to find the names and ids of the support ticket raised on the search box

**To Reproduce**
1. Go to Support Tickets of Nayi Disha Account or Prod
2. Click on 'the `id  51699 Raj`, `id 51750 Saloni``id 51731 Satya Tiwari` in Nayi Disha Account, in prod search with name `sam`and id `234981` it isn't appearing
3. Scroll down to to the 5,6,7 page  you will find the tickets available (in Nayi Disha)
4.When you search at times it appears at times not

I searched all the names you shared – Raj didn’t appear for me, and for the other two contacts, Sumita showed up, but Satya Tiwari didn’t appear. However, if we search just for 'Satya', it comes up.
when I search for SaaS admin it appears correctly, but the IDs don’t show up in search results. Sometimes, the search doesn't work for certain names either.
This happends in Prod Account also

**Expected behavior**
Search functionality on tickets should be easy to find names or ticket ids.

**Screenshots**

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/1886bc01-d9e0-4eba-9649-2da24cf08da2" />
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/918eb0ec-69c0-422a-9ceb-af2cb0eb890f" />
<img width="909" alt="image" src="https://github.com/user-attachments/assets/4041658e-fc4f-4c4a-a923-689b895ccbd6" />
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/baa0d683-e7b9-430d-88d2-3a97401146cf" />
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/19164316-be40-4de0-9829-b758073bcad6" />
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/d5367f6c-c055-4ba4-9186-b26fba2b8f88" />

**Comment by madclaws** [comment]
@SangeetaMishr The search works by if the search term is in either name(of who opened) or phone (of who opened) or ticket body.

**Comment by SangeetaMishr** [comment]
@madclaws Can you elaborate on _either name(of who opened) or phone (of who opened) or ticket body._ 
I will share my understanding 
- either name(of who opened): the user who logged the ticket
-  phone (of who opened):the user who logged the ticket
- ticket body (message of the body)

**Comment by madclaws** [comment]
Yes, and the name mentioned above ex `Satya Tiwari` is name in contact field `name` not the original name in DB. That's why it was not coming in search, we don't do search inside contact fields.

@SangeetaMishr

**Comment by SangeetaMishr** [comment]
@madclaws Nayi Disha has request to add search criteria with the feilds name also 
As there all team members don't have access to view the mobile number. Hence it is taking time for them to gather the number, and do analysis and also as whatsapp name sometimes has special characters and not the actual name.
