### ISSUE TITLE
Response of updateSavedSearch

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#437]
**Describe the bug**
Can we get all the parameters in the updateSavedSearch response, just as we do have in createSavedSearch?

**updateSavedSearch response:**
`{
    "data": {
      "updateSavedSearch": {
        "__typename": "SavedSearchResult",
        "errors": null,
        "savedSearch": {
          "__typename": "SavedSearch",
          "id": "1",
          "label": "All conversations"
        }
      }
    }
  }`

**createSavedSearch response:**
`{
    "data": {
      "createSavedSearch": {
        "__typename": "SavedSearchResult",
        "errors": null,
        "savedSearch": {
          "__typename": "SavedSearch",
          "args": "{\"messageOpts\":{\"offset\":0,\"limit\":10},\"filter\":{\"term\":\"\",\"includeUsers\":[],\"includeTags\":[],\"includeGroups\":[]},\"contactOpts\":{\"offset\":0,\"limit\":20}}",
          "count": 5,
          "id": "10",
          "label": "vc",
          "shortcode": "qw"
        }
      }
    }
  }`

**Comment by pankaj-ag** [comment]
Closing this one as complte
