### ISSUE TITLE
Updates to the search API for rich media type message support

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#481]
**Is your feature request related to a problem? Please describe.**
Right now, in the search API, we are not getting media details for the message if the message is non-textual. 

**Describe the solution you'd like**
We need support to have media details like caption, thumbnailUrl, sourceUrl etc in regular API calls as well as subscriptions.
```graphql
query MyQuery {
  search(contactOpts: {limit: 10, offset: 0, order: ASC}, filter: {}, messageOpts: {limit: 10, offset: 0, order: ASC}) {
    messages {
      body
      id
      media {
        id
        caption
        sourceUrl
        url
        thumbnail
      }
    }
  }
}
```

**Comment by pankaj-ag** [comment]
Closing this one.
