### ISSUE TITLE
Enable all the languages in the selection dropdown on UAT

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#514]
**Describe the task**
The languages dropdown on uat in settings page, is not showing all the languages right now

**Expected behavior**
It should be consistent with the live system.

**References**
![image](https://user-images.githubusercontent.com/16714604/93991890-7789ab00-fdaa-11ea-9165-4e542f755a6f.png)

**Comment by pankaj-ag** [comment]
Closing this one as complete.
