### ISSUE TITLE
Send messages at once to all the group members

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#574]
**Is your feature request related to a problem? Please describe.**
We need to send the same message to all the group members.

**Describe the solution you'd like**
Need a query that can send a message to all the group members using the group ID.

**Describe alternatives you've considered**
Add a group filter in createAndSendMessageToContacts query.

**Comment by anshulrr** [comment]
@rathorevaibhav API structure as per requirements
- Input fields
  - message input
  - group id
- Response
  - list of contact ids to whom the message is sent

**Comment by rathorevaibhav** [comment]
@anshulrr this looks good. Just one question, after sending the messages to the contacts will it trigger the send message subscription or not? so that the frontend can update the conversations with the new message

**Comment by anshulrr** [comment]
Yes, same as create and send message API, this will trigger the send message subscription for messages to all the contacts.

**Comment by pankaj-ag** [comment]
Closing as compelte.
