### ISSUE TITLE
Start a draft flow in the middle of another flow

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#621]
**Is your feature request related to a problem? Please describe.**
We use draft:(automation keyword) to start a flow. But we cannot use this in the middle of ongoing automation. Due to this when we try to start new automation in the simulator, it does not initiate as it's already in the previous automation.

**Describe the solution you'd like**
A way to end the automation in between and start new automation when we use draft:(automation keyword).

**Comment by dlobo** [comment]
This depends if the current flow has ignore keywords set, which we respect. We could complete all flows when we detect a draft flow being started

**Comment by dlobo** [comment]
@rathorevaibhav can you check and close. this will be merged into master later today

**Comment by rathorevaibhav** [comment]
This looks good. Closing.
