### ISSUE TITLE
Default flows setup for any new ngo

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#674]
we don't need to show all the flows and have content such that they can easily overwrite it without confusion.
<img width="1210" alt="Screenshot 2020-11-19 at 9 24 15 AM" src="https://user-images.githubusercontent.com/16714604/99619459-822e8c80-2a49-11eb-9345-7b9700ac0f1f.png">
<img width="1440" alt="Screenshot 2020-11-19 at 9 24 32 AM" src="https://user-images.githubusercontent.com/16714604/99619467-85c21380-2a49-11eb-9a40-6817d940a66e.png">
<img width="1440" alt="Screenshot 2020-11-19 at 9 24 38 AM" src="https://user-images.githubusercontent.com/16714604/99619469-88bd0400-2a49-11eb-8ce1-870ed690ce63.png">

<img width="1207" alt="Screenshot 2020-11-19 at 9 23 56 AM" src="https://user-images.githubusercontent.com/16714604/99619453-7e026f00-2a49-11eb-86ae-ef48cbde5db7.png">

**Comment by abhi1203** [comment]
We also need to remove Optout, Out of office and Survey flows.

**Comment by anshulrr** [comment]
Completed and tested
