### ISSUE TITLE
Updates to group & search query

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#677]
**Is your feature request related to a problem? Please describe.**
There are few things needed to build optimized workflows for the user permission features and get filtered data from backend.

**Describe the solution you'd like**
With regards to user permissions workflows, there are a few things needed on the API front:
- There should be some data field in the mutation to capture `Can chat with group contacts` only when the user role is staff in the staff management edit screen
- If `Can chat with group contacts only` is unselected then the user should be shown all contacts otherwise only the group contacts in the search query
- Same for the group query
![image](https://user-images.githubusercontent.com/12053186/99692719-9d80b280-2ab0-11eb-949e-576e9f6e2511.png)

**Comment by anshulrr** [comment]
The feature works fine with a single role mapped to the user.

**Comment by pankaj-ag** [comment]
@rathorevaibhav is there anything left on this or we can close this issue ?

**Comment by rathorevaibhav** [comment]
Yes, this is complete. Closing.
