### ISSUE TITLE
Translation enhancement

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#722]
As per the design, we need a following
- [ ] We need support for multiple attachments
- [ ] Need support for a category field

Reference -
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/n75V4p

**Comment by dlobo** [comment]
WhatsApp supports only one attachment per message, so we should follow the same, and not have multiple attachments. Issue seems quite old, so closing
