### ISSUE TITLE
Add new contact field dynamically

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#757]
We need to check if the current functionality is working fine.  There are some inconsistencies.

![image](https://user-images.githubusercontent.com/10670690/102040233-34136b80-3df2-11eb-9a06-4dd17e1361dc.png)

**Comment by pankaj-ag** [comment]
The new contact fields are not saved in the results. 
You can test this on production.

**Comment by AkhileshNegi** [comment]
Hi @pankaj-ag  this is tested and resolved can you review same
PR: https://github.com/glific/glific/pull/823
