### ISSUE TITLE
Advanced searching by Staff isn't showing results

### ISSUE THREAD

**Issue by abhi1203** [glific/glific#772]
**Describe the bug**

**To Reproduce**
1. Enter a staff name when advance searching
2. Click search
3. See error that there's no conversations

**Expected behavior**
All the contacts assigned to that staff member should show up

**Screenshots**
Searched by Saurabh
![image](https://user-images.githubusercontent.com/16714604/102209247-80e06a80-3ef6-11eb-9c36-dddb03140f7d.png)
No results.
![image](https://user-images.githubusercontent.com/16714604/102209271-88a00f00-3ef6-11eb-8feb-f329c6ebcfda.png)

**Comment by pankaj-ag** [comment]
@abhi1203 the stuff filter gives you all the messages sent by the staff member and there Are no messages for Sourabh. 

For other things, you can use a groups filter.

**Comment by abhi1203** [comment]
Yea. there was a difference in the features understanding. thanks
