### ISSUE TITLE
Failed to retrieve flow, {:flow_keyword, "newcontact", "published"}, expected at least one result but got none in query:

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#813]
** (ArgumentError) Failed to retrieve flow, {:flow_keyword, "newcontact", "published"}, expected at least one result but got none in query:

from f0 in Glific.Flows.Flow,
 join: r1 in assoc(f0, :revisions),
  where: f0.organization_id == ^12,
  where: r1.flow_id == f0.id,
     select: %Glific.Flows.Flow{id: f0.id, uuid: f0.uuid, keywords: f0.keywords, ignore_keywords: f0.ignore_keywords, organization_id: f0.organization_id, definition: r1.definition, version: r1.version}
    where: r1.status == ^"published",
    where: ^"newcontact" in f0.keywords,

   (glific 0.8.6) lib/glific/flows.ex:346: Glific.Flows.get_cached_flow/2
     (glific 0.8.6) lib/glific/processor/consumer_worker.ex:85: Glific.Processor.ConsumerWorker.handle_common/3
    (glific 0.8.6) lib/glific/processor/consumer_flow.ex:100: Glific.Processor.ConsumerFlow.check_flows/4
    (glific 0.8.6) lib/glific/processor/consumer_worker.ex:99: Glific.Processor.ConsumerWorker.process_message/2
   (glific 0.8.6) lib/glific/processor/consumer_worker.ex:72: Glific.Processor.ConsumerWorker.handle_cast/2
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
  (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
 07:53:32.864 request_id=c677860d1818878e5eae493e0400fdfa [info] POST /gupshup
 Last message: {:"$gen_cast", {%Glific.Messages.Message{user: #Ecto.Association.NotLoaded<association :user is not loaded>, flow_label: nil, is_hsm: false, type: :text, contact: #Ecto.Association.NotLoaded<association :contact is not loaded>, inserted_at: ~U[2020-12-28 07:53:32.502288Z], updated_at: ~U[2020-12-28 07:53:32.502288Z], user_id: nil, message_number: 0, organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, session_uuid: nil, bsp_status: :delivered, tags: #Ecto.Association.NotLoaded<association :tags is not loaded>, clean_body: "hello", sent_at: nil, send_at: nil, body: "Hello", status: :received, organization_id: 12, flow_object: #Ecto.Association.NotLoaded<association :flow_object is not loaded>, media: #Ecto.Association.NotLoaded<association :media is not loaded>, sender_id: 9176, media_id: nil, receiver: #Ecto.Association.NotLoaded<association :receiver is not loaded>, errors: %{}, flow_id: nil, id: 24703, __meta__: #Ecto.Schema.Metadata<:loaded, "messages">, flow: :inbound, receiver_id: 3505, bsp_message_id: "ABEGkYdnUUFzAhB-sfOz3yD7OHfWNfP2GeXK", contact_id: 9176, uuid: nil, sender: #Ecto.Association.NotLoaded<association :sender is not loaded>}, {12, %Glific.Users.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, contact: #Ecto.Association.NotLoaded<association :contact is not loaded>, contact_id: 3505, current_password: nil, groups: #Ecto.Association.NotLoaded<association :groups is not loaded>, id: 28, inserted_at: ~N[2020-12-01 15:56:25], is_restricted: false, name: "Glific Admin", organization: #Ecto.Association.NotLoaded<association :organization is not loaded>, organization_id: 12, password: nil, password_hash: "$pbkdf2-sha512$100000$oYEtSSTlL6JIIPFBI0cMnQ==$eu4lnkjGRoMEuXtex4Ea9NKrcnrSrt3oAlzGavV60ey/zo6guJtteoj8UZZZBeYqPMUiQRV95HMy9CV93lbqnw==", phone: "918454812392", roles: [:admin], updated_at: ~N[2020-12-01 15:56:25]}}, #PID<0.24823.13>}}
 07:53:32.874 request_id=c677860d1818878e5eae493e0400fdfa user_id=28 org_id=12 [info] Sent 200 in 10ms
 07:53:33.659 request_id=c4528c6ce51b500f80ef7ad273182d67 [info] POST /api
 07:53:33.668 request_id=c4528c6ce51b500f80ef7ad273182d67 user_id=28 org_id=12 [info] Searches.Search/2 with : args: %{contact_opts: %{limit: 50, offset: 0, order: :asc}, filter: %{id: 9176, organization_id: 12}, message_opts: %{limit: 50, offset: 0, order: :asc}, organization_id: 12, save_search: false}
 07:53:33.679 request_id=c4528c6ce51b500f80ef7ad273182d67 user_id=28 org_id=12 [info] Sent 200 in 20ms
 07:55:58.553 user_id=1 org_id=1 [info] Searches.Search/2 with : args: %{contact_opts: %{limit: 20, offset: 0}, filter: %{organization_id: 1, term: ""}, message_opts: %{limit: 10, offset: 0}}
 07:56:17.574 user_id=1 org_id=1 [info] Searches.Search/2 with : args: %{contact_opts: %{limit: 20, offset: 0}, filter: %{organization_id: 1, term: ""}, message_opts: %{limit: 10, offset: 0}}
 07:56:37.593 user_id=1 org_id=1 [info] Searches.Search/2 with : args: %{contact_opts: %{limit: 20, offset: 0}, filter: %{organization_id: 1, term: ""}, message_opts: %{limit: 10, offset: 0}}
 07:56:46.439 [info] Verifying tokens: user_id: '28'

**Comment by dlobo** [comment]
when would this happen? when someone executes a flow that has not been published?

**Comment by AkhileshNegi** [comment]
@dlobo Hi lobo, I looked into the issue and able to replicate same. The issue occurs when there is a flow with keyword as newcontact but there is no published flow.
