### ISSUE TITLE
Field labels are not getting saved in bigquery.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#815]
Field labels are not getting saved in Big query.
<img width="643" alt="Screenshot 2020-12-28 at 6 13 27 PM" src="https://user-images.githubusercontent.com/16541548/103215261-daa25500-4938-11eb-87ba-fe9ba8cf56ec.png">
<img width="399" alt="Screenshot 2020-12-28 at 6 15 33 PM" src="https://user-images.githubusercontent.com/16541548/103215268-dd9d4580-4938-11eb-9a70-d20793061954.png">

**Comment by pankaj-ag** [comment]
This has been fixed in the latest release. We will deploy that today and let you know.
