### ISSUE TITLE
Add description on the glific organization settings in the seeder.

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#816]
![image](https://user-images.githubusercontent.com/10670690/103216599-75506300-493c-11eb-8f38-b3ff7ccf4be2.png)

**Comment by AkhileshNegi** [comment]
@pankaj-ag all providers have description in seeder. We need to update the production database once
![image](https://user-images.githubusercontent.com/40158831/103347894-54178000-4abe-11eb-92dd-c10e898c8f3a.png)
