### ISSUE TITLE
Bigquery API to update a row returns an error as not supported for streaming buffer

### ISSUE THREAD

**Issue by anshulrr** [glific/glific#820]
Steps to reproduce:
1. We are updating the contact fields from flows.
2. Sometimes the API response to update the contact in Bigquery returns an error.
`UPDATE or DELETE statement over table *.contacts would affect rows in the streaming buffer, which is not supported`
3. After a few hours, it works fine.

We should make sure to log the Bigquery error response.

![image](https://user-images.githubusercontent.com/42372297/103230302-1cdc8e00-495b-11eb-8e14-910f387781f2.png)

**Comment by pankaj-ag** [comment]
After some research, we found that Google suggests updating the data in the interval of 90 min at least. Otherwise, they will throw this error.

**Comment by pankaj-ag** [comment]
After some research, we found that google recommends waiting 90 min for running the query.
