### ISSUE TITLE
Write document specs for private functions

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#831]
Currently, there are some areas where we don't have specs for private functions. 
We need to add that. 
I will check why dialyzer is not reporting them.

**Comment by pankaj-ag** [comment]
@AkhileshNegi is it done or there are more files?

**Comment by dlobo** [comment]
In general we should write specs, docs and tests for all functions, public or private

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you list down all the files which needed the cleanups?

**Comment by AkhileshNegi** [comment]
@pankaj-ag These are the files I have tracked so far that will be needing cleanup:

- lib\glific\release.ex
- lib\glific\csv\file.ex
- lib\glific\csv\flow.ex
- lib\glific\flags\ecto.ex
- lib\glific\flows\case.ex
- lib\glific\flows\localization.ex
- lib\glific\jobs\bigquery\bigquery_worker.ex
- lib\glific\jobs\gcs\gcs_worker.ex
- lib\glific\processor\consumer_worker.ex
- lib\glific\providers\gupshup\message.ex
- lib\glific\providers\gupshup\worker.ex
- lib\glific\seeds\seeds_dev.ex
- lib\glific\seeds\seeds_scale.ex
- lib\glific_web\endpoint.ex
- lib\glific\tags\tag.ex
- lib\glific\users\user.ex
- lib\glific_web\controllers\api\v1\registration_controller.ex
- lib\glific_web\live\page_live.ex
- lib\glific_web\misc\http_signature.ex
- lib\glific_web\plugs\api_auth_plug.ex
- lib\glific_web\schema\generic_types.ex

**Comment by dlobo** [comment]
Closing this since we should constantly review and improve code base as we are looking at various issues, trapping errors etc. Lets keep rewriting
