### ISSUE TITLE
How to Collating/Upload existing data on Glific

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#841]
Pankaj, Assigning it to you for review from a Product functionality perspective.

How to Collating/Upload existing data on Glific?
https://glific.slab.com/posts/how-to-collating-upload-existing-data-on-glific-5n2rzdv6

**Comment by pankaj-ag** [comment]
Mohit I did not understand this. 
I think this is generic for all the cloud drives. 

We need to change it and show how users can capture the data(Media file ) from Glific and store them on GCS.

**Comment by pankaj-ag** [comment]
Sorry Mohit, My bad. 

I got it now. 

Closing the issue.
