### ISSUE TITLE
User documentation for has location and has media

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#843]
We added two new categories in the flow editor.
1. Has location 
2. Has Media 

We need to add two articles on the slab for our users.

**Comment by pankaj-ag** [comment]
@mohitsharma-22 over to you now.

**Comment by mohitsharma-22** [comment]
Thanks @pankaj-ag Please review the documents for "Has location" and "Has Media" and let me know if you have any suggestions.

1.  Has Media - https://glific.slab.com/posts/how-to-the-has-media-category-in-flow-editor-s9ax87aw
2. Has Location - https://glific.slab.com/posts/how-to-use-the-has-location-category-in-flow-editor-cyucru6n

**Comment by pankaj-ag** [comment]
Thanks. closing this one now.
