### ISSUE TITLE
Improve error handling code for Gupshup worker ...

### ISSUE THREAD

**Issue by dlobo** [glific/glific#874]
1. If there is an API key failure or any other gupshup failure), we should log it and return success to Oban since the job succeeded but there was an error in the information passed (which is not going to change)
2.  We should check the other error codes and decide if we want Oban to retry the job
3. For things like API key failure, would be good to alert the frontend

am taking an initial stab at this in the branch: bug/staging-gupshup

**Comment by AkhileshNegi** [comment]
PR: https://github.com/glific/glific/pull/878

**Comment by pankaj-ag** [comment]
This is fixed. Closing this now.
