### ISSUE TITLE
Adding multi-simulator support

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#876]
**Is your feature request related to a problem? Please describe.**
Multiple users can not use the simulator simultaneously and can see the flow messages trigger by other users.

**Describe the solution you'd like**
Multiple users can use simulator simultaneously without being interrupted by flows triggers or messages sent by other users to simulator

**Comment by pankaj-ag** [comment]
This has been merged into master. 

@AkhileshNegi can you do some testing and adding the graphql test and documentation?

**Comment by pankaj-ag** [comment]
This is complete. We will track other things in the frontend.
