### ISSUE TITLE
Onboarding Documentations

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#880]
@pankaj-ag @abhi1203 Assigning it to you to review the document for Onboarding. 

**Glific Pilot NGO Onboarding Toolkit**
https://glific.slab.com/posts/glific-pilot-ngo-onboarding-toolkit-xikv1fz3

**Setup the organization on Gupshup and go Live**
https://glific.slab.com/posts/setup-the-organization-on-gupshup-and-go-live-qwbjphx0

**Facebook verification process for WA business API**
https://glific.slab.com/posts/facebook-verification-process-for-wa-business-api-065jvy5a

**Comment by pankaj-ag** [comment]
Mohit this looks good to me and it also verified by some NGOs. 
Thanks for moving this on the slab.
Closing this one now.

**Comment by pankaj-ag** [comment]
@mohitsharma-22 can you tell us the status. I think there is some offline discussion here.

**Comment by abhi1203** [comment]
Seems like this is complete. we can close
