### ISSUE TITLE
Adding busy and free state for simulator

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#889]
**Describe the task**

The simulator should have either of the two states: free or busy.

Based on the above two states can we have these graphql calls:
-  Query getSimulator which returns the simulator number if the simulator is in free state else it should return null.  Running the query should change the simulator state to busy if its in free state.

- Mutation closeSimulator where we pass the simulator number as a parameter and it changes the simulator status to free.

Additionally, If there are no messages exchanged in 5 minutes after opening the simulator, than change the simulator status to free.
Frontend will close the simulator after 5 minutes of the last send message between the user and simulator.

**Comment by pankaj-ag** [comment]
We are tracking this one in #876. 

Closing this one. Please put your further questions on that issue.
