### ISSUE TITLE
HSM templates not updating when last updated_at is at a later time than when the template was approved

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#901]
**Describe the bug**
 Currently we are updating HSM based on updated_at time. As updated_at gets modified when is_active changes therefore there was a case where templates were not being updated when the status changes from PENDING to APPROVED from BSP.

**Expected behavior**
HSM templates should be updated when status changes from PENDING to APPROVED

**Comment by pankaj-ag** [comment]
This is fixed. 
We will make more improvements in other issues.
