### ISSUE TITLE
Need a CORS proxy endpoint to handle cross origin requests in frontend

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific#921]
**Is your feature request related to a problem? Please describe.**
Currently, if we send a cross-origin request to check the validity of a media URL through the frontend it gives a CORS error

**Describe the solution you'd like**
Need a CORS proxy URL in the  backend that fetches cross-origin data and sends it back to the frontend

**References**
We are using https://github.com/Rob--W/cors-anywhere CORS proxy server currently, but it has a limit of 50 requests per minute.

**Comment by dlobo** [comment]
We should just let the backend do the needful and extend the floweditor api to make a check for this and return true/false

**Comment by pankaj-ag** [comment]
This is complete. Closing this one now.
