### ISSUE TITLE
Not able to sent sticker from glific

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#938]

**Comment by AkhileshNegi** [comment]
@pankaj-ag   As checked currently animated WebP or animated stickers are not supported and there are guidelines for stickers that can be sent through whatsapp. Please find the below link
![image](https://user-images.githubusercontent.com/40158831/104813088-dcbb4d80-582c-11eb-9a38-7a5d92dd2c10.png)

https://medium.com/@sachinaroracse/creating-whatsapp-stickers-application-in-android-studio-e3f6c74a19c7
