### ISSUE TITLE
Groups in Glific

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#960]
@abhi1203, @pankaj-ag  Assign this document to you for review from a Product functionality perspective. 

**How Groups is used in Glific?**
https://glific.slab.com/posts/how-groups-is-used-in-glific-6kveksfm

**Comment by pankaj-ag** [comment]
Mohit we are going to rename this as collection soon. So please take care of that.

**Comment by abhi1203** [comment]
@mohitsharma-22 document wise i think we can structure it with sub headings:
Create a collection
Add beneficiaries to collection (manually and automatically from flows)
Assign staff to collection
Send message to collection

**Comment by mohitsharma-22** [comment]
@pankaj-ag Sure, we will modify it once groups will be renamed from groups in production.

Thanks, @abhi1203 for the structure suggestion. I have added the subheadings to the document. Let me know if any other suggestions for this document.

**Comment by mohitsharma-22** [comment]
@abhi1203 I have updated the document for collections. Please have a look and let me know if you have any feedback.
https://glific.slab.com/posts/how-collections-is-used-in-glific-6kveksfm

**Comment by pankaj-ag** [comment]
@mohitgusain looks good to me.
