### ISSUE TITLE
Create Reports for New Organization

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#965]
@pankaj-ag Moved the article of the creating report to the slab. Assign it to you for review. Please suggest if you need any modification in it.

**Create Reports for New Organization**
https://glific.slab.com/posts/create-reports-for-new-organization-vzlvtpuw

**Comment by pankaj-ag** [comment]
@mohitsharma-22 looks good to me. I think we might need to update the link when @akash-y will ship the latest version.
