### ISSUE TITLE
Update the Validate Media URL to validate the attachment size

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific#986]
**Is your feature request related to a problem? Please describe.**
Update the Validate Media URL to validate the size of the attachment and provide a response to display a valid error.

**Describe the solution you'd like**
The size varies from media to media, for say the maximum size supported for audio is 16MB and for the document is 100MB. Please check following 

Media Type | Max Size
audio | 16 MB
document | 100 MB
image | 5 MB
sticker | 100 KB
video | 16 MB

Reference - https://developers.facebook.com/docs/whatsapp/api/media/

**Comment by pankaj-ag** [comment]
@DigneshGujarathi what about video and image ?

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi what about video and image ?

I have updated the issue.

**Comment by pankaj-ag** [comment]
This is fixed closing the issue now.
