### ISSUE TITLE
How to check Webhook Logs in Glific?

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#994]
@pankaj-ag Assign this document to you for review. Let me know if you have feedback or suggestions.

**How to check Webhook Logs in Glific?**
https://glific.slab.com/posts/hsm-templates-afhp1px5

**Comment by pankaj-ag** [comment]
@mohitsharma-22 looks like a wrong link. 
Let me know If I am missing something here.

**Comment by mohitsharma-22** [comment]
@pankaj-ag My bad. Please find the correct link. 
https://glific.slab.com/posts/how-to-check-webhook-logs-in-glific-nllntvgc

**Comment by pankaj-ag** [comment]
Looks good to me.
